        # ---- ДОБАВЬ ЭТИ СЛОВА В СПИСОК "A1": [...] в файле bot.py ----
WORDS_A1 = [
        {"word": "apple", "transcription": "/ˈæpəl/", "translation": "яблоко", "part_of_speech": "noun", "example": "I eat an apple every day.", "example_ru": "Я ем яблоко каждый день."},
        {"word": "banana", "transcription": "/bəˈnɑːnə/", "translation": "банан", "part_of_speech": "noun", "example": "She likes bananas.", "example_ru": "Ей нравятся бананы."},
        {"word": "orange", "transcription": "/ˈɒrɪndʒ/", "translation": "апельсин; оранжевый", "part_of_speech": "noun/adjective", "example": "The orange is sweet.", "example_ru": "Апельсин сладкий."},
        {"word": "milk", "transcription": "/mɪlk/", "translation": "молоко", "part_of_speech": "noun", "example": "I drink milk every morning.", "example_ru": "Я пью молоко каждое утро."},
        {"word": "bread", "transcription": "/bred/", "translation": "хлеб", "part_of_speech": "noun", "example": "We need bread from the shop.", "example_ru": "Нам нужен хлеб из магазина."},
        {"word": "egg", "transcription": "/eɡ/", "translation": "яйцо", "part_of_speech": "noun", "example": "I have two eggs for breakfast.", "example_ru": "У меня два яйца на завтрак."},
        {"word": "tea", "transcription": "/tiː/", "translation": "чай", "part_of_speech": "noun", "example": "Would you like some tea?", "example_ru": "Хочешь чаю?"},
        {"word": "coffee", "transcription": "/ˈkɒfi/", "translation": "кофе", "part_of_speech": "noun", "example": "He drinks coffee in the morning.", "example_ru": "Он пьёт кофе по утрам."},
        {"word": "rice", "transcription": "/raɪs/", "translation": "рис", "part_of_speech": "noun", "example": "We eat rice for dinner.", "example_ru": "Мы едим рис на ужин."},
        {"word": "fish", "transcription": "/fɪʃ/", "translation": "рыба", "part_of_speech": "noun", "example": "I like fish and chips.", "example_ru": "Мне нравится рыба с картошкой."},
        {"word": "meat", "transcription": "/miːt/", "translation": "мясо", "part_of_speech": "noun", "example": "He eats meat every day.", "example_ru": "Он ест мясо каждый день."},
        {"word": "soup", "transcription": "/suːp/", "translation": "суп", "part_of_speech": "noun", "example": "The soup is very hot.", "example_ru": "Суп очень горячий."},
        {"word": "cake", "transcription": "/keɪk/", "translation": "торт, пирог", "part_of_speech": "noun", "example": "She made a birthday cake.", "example_ru": "Она испекла торт на день рождения."},
        {"word": "sugar", "transcription": "/ˈʃʊɡər/", "translation": "сахар", "part_of_speech": "noun", "example": "Do you want sugar in your tea?", "example_ru": "Тебе сахар в чай?"},
        {"word": "salt", "transcription": "/sɔːlt/", "translation": "соль", "part_of_speech": "noun", "example": "Pass me the salt, please.", "example_ru": "Передай мне соль, пожалуйста."},
        {"word": "butter", "transcription": "/ˈbʌtər/", "translation": "масло (сливочное)", "part_of_speech": "noun", "example": "I put butter on my bread.", "example_ru": "Я намазываю масло на хлеб."},
        {"word": "cheese", "transcription": "/tʃiːz/", "translation": "сыр", "part_of_speech": "noun", "example": "I love cheese pizza.", "example_ru": "Я люблю пиццу с сыром."},
        {"word": "chicken", "transcription": "/ˈtʃɪkɪn/", "translation": "курица; цыплёнок", "part_of_speech": "noun", "example": "We had chicken for lunch.", "example_ru": "На обед у нас была курица."},
        {"word": "potato", "transcription": "/pəˈteɪtəʊ/", "translation": "картофель", "part_of_speech": "noun", "example": "I like fried potatoes.", "example_ru": "Мне нравится жареная картошка."},
        {"word": "tomato", "transcription": "/təˈmɑːtəʊ/", "translation": "помидор", "part_of_speech": "noun", "example": "This tomato is red and juicy.", "example_ru": "Этот помидор красный и сочный."},
        {"word": "mother", "transcription": "/ˈmʌðər/", "translation": "мать, мама", "part_of_speech": "noun", "example": "My mother is a teacher.", "example_ru": "Моя мама — учитель."},
        {"word": "father", "transcription": "/ˈfɑːðər/", "translation": "отец, папа", "part_of_speech": "noun", "example": "My father works in a bank.", "example_ru": "Мой папа работает в банке."},
        {"word": "brother", "transcription": "/ˈbrʌðər/", "translation": "брат", "part_of_speech": "noun", "example": "I have one brother.", "example_ru": "У меня есть один брат."},
        {"word": "sister", "transcription": "/ˈsɪstər/", "translation": "сестра", "part_of_speech": "noun", "example": "My sister is ten years old.", "example_ru": "Моей сестре десять лет."},
        {"word": "baby", "transcription": "/ˈbeɪbi/", "translation": "малыш, младенец", "part_of_speech": "noun", "example": "The baby is sleeping.", "example_ru": "Малыш спит."},
        {"word": "child", "transcription": "/tʃaɪld/", "translation": "ребёнок", "part_of_speech": "noun", "example": "Every child loves toys.", "example_ru": "Каждый ребёнок любит игрушки."},
        {"word": "family", "transcription": "/ˈfæməli/", "translation": "семья", "part_of_speech": "noun", "example": "My family is big.", "example_ru": "Моя семья большая."},
        {"word": "boy", "transcription": "/bɔɪ/", "translation": "мальчик", "part_of_speech": "noun", "example": "The boy is playing football.", "example_ru": "Мальчик играет в футбол."},
        {"word": "girl", "transcription": "/ɡɜːrl/", "translation": "девочка, девушка", "part_of_speech": "noun", "example": "The girl has long hair.", "example_ru": "У девочки длинные волосы."},
        {"word": "people", "transcription": "/ˈpiːpəl/", "translation": "люди", "part_of_speech": "noun", "example": "Many people live in this city.", "example_ru": "В этом городе живёт много людей."},
        {"word": "bed", "transcription": "/bed/", "translation": "кровать", "part_of_speech": "noun", "example": "I go to bed at ten.", "example_ru": "Я ложусь спать в десять."},
        {"word": "chair", "transcription": "/tʃeər/", "translation": "стул", "part_of_speech": "noun", "example": "Please sit on the chair.", "example_ru": "Пожалуйста, сядь на стул."},
        {"word": "table", "transcription": "/ˈteɪbəl/", "translation": "стол", "part_of_speech": "noun", "example": "The book is on the table.", "example_ru": "Книга на столе."},
        {"word": "door", "transcription": "/dɔːr/", "translation": "дверь", "part_of_speech": "noun", "example": "Please close the door.", "example_ru": "Пожалуйста, закрой дверь."},
        {"word": "window", "transcription": "/ˈwɪndəʊ/", "translation": "окно", "part_of_speech": "noun", "example": "Open the window, please.", "example_ru": "Открой окно, пожалуйста."},
        {"word": "floor", "transcription": "/flɔːr/", "translation": "пол; этаж", "part_of_speech": "noun", "example": "The cat is on the floor.", "example_ru": "Кошка на полу."},
        {"word": "wall", "transcription": "/wɔːl/", "translation": "стена", "part_of_speech": "noun", "example": "There is a picture on the wall.", "example_ru": "На стене висит картина."},
        {"word": "room", "transcription": "/ruːm/", "translation": "комната", "part_of_speech": "noun", "example": "My room is small but cosy.", "example_ru": "Моя комната маленькая, но уютная."},
        {"word": "kitchen", "transcription": "/ˈkɪtʃɪn/", "translation": "кухня", "part_of_speech": "noun", "example": "Mum is in the kitchen.", "example_ru": "Мама на кухне."},
        {"word": "bathroom", "transcription": "/ˈbɑːθruːm/", "translation": "ванная комната", "part_of_speech": "noun", "example": "The bathroom is upstairs.", "example_ru": "Ванная наверху."},
        {"word": "garden", "transcription": "/ˈɡɑːrdən/", "translation": "сад, огород", "part_of_speech": "noun", "example": "We grow flowers in the garden.", "example_ru": "Мы выращиваем цветы в саду."},
        {"word": "key", "transcription": "/kiː/", "translation": "ключ", "part_of_speech": "noun", "example": "I lost my key.", "example_ru": "Я потерял ключ."},
        {"word": "lamp", "transcription": "/læmp/", "translation": "лампа", "part_of_speech": "noun", "example": "Turn on the lamp, please.", "example_ru": "Включи лампу, пожалуйста."},
        {"word": "bag", "transcription": "/bæɡ/", "translation": "сумка, пакет", "part_of_speech": "noun", "example": "She has a big red bag.", "example_ru": "У неё большая красная сумка."},
        {"word": "box", "transcription": "/bɒks/", "translation": "коробка, ящик", "part_of_speech": "noun", "example": "Put it in the box.", "example_ru": "Положи это в коробку."},
        {"word": "shirt", "transcription": "/ʃɜːrt/", "translation": "рубашка", "part_of_speech": "noun", "example": "He wears a white shirt.", "example_ru": "Он носит белую рубашку."},
        {"word": "dress", "transcription": "/dres/", "translation": "платье", "part_of_speech": "noun", "example": "She has a beautiful dress.", "example_ru": "У неё красивое платье."},
        {"word": "shoes", "transcription": "/ʃuːz/", "translation": "туфли, обувь", "part_of_speech": "noun", "example": "These shoes are too small.", "example_ru": "Эта обувь слишком маленькая."},
        {"word": "hat", "transcription": "/hæt/", "translation": "шляпа, шапка", "part_of_speech": "noun", "example": "Put on your hat, it is cold.", "example_ru": "Надень шапку, холодно."},
        {"word": "coat", "transcription": "/kəʊt/", "translation": "пальто", "part_of_speech": "noun", "example": "I need a warm coat.", "example_ru": "Мне нужно тёплое пальто."},
        {"word": "trousers", "transcription": "/ˈtraʊzərz/", "translation": "брюки, штаны", "part_of_speech": "noun", "example": "He wears black trousers.", "example_ru": "Он носит чёрные брюки."},
        {"word": "glasses", "transcription": "/ˈɡlɑːsɪz/", "translation": "очки", "part_of_speech": "noun", "example": "She wears glasses to read.", "example_ru": "Она носит очки для чтения."},
        {"word": "watch", "transcription": "/wɒtʃ/", "translation": "часы (наручные); смотреть", "part_of_speech": "noun/verb", "example": "I got a new watch.", "example_ru": "Мне купили новые часы."},
        {"word": "bus", "transcription": "/bʌs/", "translation": "автобус", "part_of_speech": "noun", "example": "I take the bus to school.", "example_ru": "Я езжу в школу на автобусе."},
        {"word": "train", "transcription": "/treɪn/", "translation": "поезд", "part_of_speech": "noun", "example": "The train is fast.", "example_ru": "Поезд быстрый."},
        {"word": "plane", "transcription": "/pleɪn/", "translation": "самолёт", "part_of_speech": "noun", "example": "We go by plane.", "example_ru": "Мы летим на самолёте."},
        {"word": "bike", "transcription": "/baɪk/", "translation": "велосипед", "part_of_speech": "noun", "example": "I ride my bike every weekend.", "example_ru": "Я катаюсь на велосипеде каждые выходные."},
        {"word": "taxi", "transcription": "/ˈtæksi/", "translation": "такси", "part_of_speech": "noun", "example": "Let's take a taxi.", "example_ru": "Давай возьмём такси."},
        {"word": "road", "transcription": "/rəʊd/", "translation": "дорога", "part_of_speech": "noun", "example": "The road is long.", "example_ru": "Дорога длинная."},
        {"word": "street", "transcription": "/striːt/", "translation": "улица", "part_of_speech": "noun", "example": "I live on this street.", "example_ru": "Я живу на этой улице."},
        {"word": "city", "transcription": "/ˈsɪti/", "translation": "город (большой)", "part_of_speech": "noun", "example": "London is a big city.", "example_ru": "Лондон — большой город."},
        {"word": "town", "transcription": "/taʊn/", "translation": "город (маленький), посёлок", "part_of_speech": "noun", "example": "I live in a small town.", "example_ru": "Я живу в маленьком городе."},
        {"word": "shop", "transcription": "/ʃɒp/", "translation": "магазин", "part_of_speech": "noun", "example": "Let's go to the shop.", "example_ru": "Давай зайдём в магазин."},
        {"word": "park", "transcription": "/pɑːrk/", "translation": "парк", "part_of_speech": "noun", "example": "Children play in the park.", "example_ru": "Дети играют в парке."},
        {"word": "bank", "transcription": "/bæŋk/", "translation": "банк", "part_of_speech": "noun", "example": "The bank is on the main street.", "example_ru": "Банк находится на главной улице."},
        {"word": "hotel", "transcription": "/həʊˈtel/", "translation": "отель, гостиница", "part_of_speech": "noun", "example": "We stay at a nice hotel.", "example_ru": "Мы остановились в хорошем отеле."},
        {"word": "airport", "transcription": "/ˈeərpɔːrt/", "translation": "аэропорт", "part_of_speech": "noun", "example": "The airport is very big.", "example_ru": "Аэропорт очень большой."},
        {"word": "phone", "transcription": "/fəʊn/", "translation": "телефон", "part_of_speech": "noun", "example": "My phone is out of battery.", "example_ru": "У моего телефона сел аккумулятор."},
        {"word": "computer", "transcription": "/kəmˈpjuːtər/", "translation": "компьютер", "part_of_speech": "noun", "example": "I work on a computer.", "example_ru": "Я работаю за компьютером."},
        {"word": "television", "transcription": "/ˈtelɪvɪʒən/", "translation": "телевизор", "part_of_speech": "noun", "example": "We watch television in the evening.", "example_ru": "Мы смотрим телевизор вечером."},
        {"word": "radio", "transcription": "/ˈreɪdiəʊ/", "translation": "радио", "part_of_speech": "noun", "example": "I listen to the radio.", "example_ru": "Я слушаю радио."},
        {"word": "camera", "transcription": "/ˈkæmərə/", "translation": "фотоаппарат, камера", "part_of_speech": "noun", "example": "She takes photos with her camera.", "example_ru": "Она фотографирует своим фотоаппаратом."},
        {"word": "music", "transcription": "/ˈmjuːzɪk/", "translation": "музыка", "part_of_speech": "noun", "example": "I love listening to music.", "example_ru": "Я люблю слушать музыку."},
        {"word": "film", "transcription": "/fɪlm/", "translation": "фильм", "part_of_speech": "noun", "example": "Let's watch a film tonight.", "example_ru": "Давай посмотрим фильм сегодня вечером."},
        {"word": "game", "transcription": "/ɡeɪm/", "translation": "игра", "part_of_speech": "noun", "example": "We play a board game.", "example_ru": "Мы играем в настольную игру."},
        {"word": "sport", "transcription": "/spɔːrt/", "translation": "спорт", "part_of_speech": "noun", "example": "Sport is good for health.", "example_ru": "Спорт полезен для здоровья."},
        {"word": "ball", "transcription": "/bɔːl/", "translation": "мяч, шар", "part_of_speech": "noun", "example": "Kick the ball!", "example_ru": "Ударь по мячу!"},
        {"word": "red", "transcription": "/red/", "translation": "красный", "part_of_speech": "adjective", "example": "She has a red dress.", "example_ru": "У неё красное платье."},
        {"word": "blue", "transcription": "/bluː/", "translation": "синий, голубой", "part_of_speech": "adjective", "example": "The sky is blue.", "example_ru": "Небо голубое."},
        {"word": "green", "transcription": "/ɡriːn/", "translation": "зелёный", "part_of_speech": "adjective", "example": "The grass is green.", "example_ru": "Трава зелёная."},
        {"word": "yellow", "transcription": "/ˈjeləʊ/", "translation": "жёлтый", "part_of_speech": "adjective", "example": "Bananas are yellow.", "example_ru": "Бананы жёлтые."},
        {"word": "black", "transcription": "/blæk/", "translation": "чёрный", "part_of_speech": "adjective", "example": "He has a black cat.", "example_ru": "У него чёрная кошка."},
        {"word": "white", "transcription": "/waɪt/", "translation": "белый", "part_of_speech": "adjective", "example": "Snow is white.", "example_ru": "Снег белый."},
        {"word": "pink", "transcription": "/pɪŋk/", "translation": "розовый", "part_of_speech": "adjective", "example": "She likes pink flowers.", "example_ru": "Ей нравятся розовые цветы."},
        {"word": "brown", "transcription": "/braʊn/", "translation": "коричневый", "part_of_speech": "adjective", "example": "He has brown eyes.", "example_ru": "У него карие глаза."},
        {"word": "hot", "transcription": "/hɒt/", "translation": "горячий, жаркий", "part_of_speech": "adjective", "example": "It is hot today.", "example_ru": "Сегодня жарко."},
        {"word": "cold", "transcription": "/kəʊld/", "translation": "холодный, холод", "part_of_speech": "adjective", "example": "The water is cold.", "example_ru": "Вода холодная."},
        {"word": "warm", "transcription": "/wɔːrm/", "translation": "тёплый", "part_of_speech": "adjective", "example": "It is warm in spring.", "example_ru": "Весной тепло."},
        {"word": "fast", "transcription": "/fɑːst/", "translation": "быстрый, быстро", "part_of_speech": "adjective/adverb", "example": "He is a fast runner.", "example_ru": "Он быстрый бегун."},
        {"word": "slow", "transcription": "/sləʊ/", "translation": "медленный, медленно", "part_of_speech": "adjective/adverb", "example": "The turtle is slow.", "example_ru": "Черепаха медленная."},
        {"word": "tall", "transcription": "/tɔːl/", "translation": "высокий", "part_of_speech": "adjective", "example": "My brother is very tall.", "example_ru": "Мой брат очень высокий."},
        {"word": "short", "transcription": "/ʃɔːrt/", "translation": "короткий; низкого роста", "part_of_speech": "adjective", "example": "She has short hair.", "example_ru": "У неё короткие волосы."},
        {"word": "long", "transcription": "/lɒŋ/", "translation": "длинный, долгий", "part_of_speech": "adjective", "example": "It is a long road.", "example_ru": "Это длинная дорога."},
        {"word": "fat", "transcription": "/fæt/", "translation": "толстый", "part_of_speech": "adjective", "example": "The cat is fat.", "example_ru": "Кошка толстая."},
        {"word": "thin", "transcription": "/θɪn/", "translation": "тонкий, худой", "part_of_speech": "adjective", "example": "This book is thin.", "example_ru": "Эта книга тонкая."},
        {"word": "beautiful", "transcription": "/ˈbjuːtɪfəl/", "translation": "красивый", "part_of_speech": "adjective", "example": "What a beautiful flower!", "example_ru": "Какой красивый цветок!"},
        {"word": "ugly", "transcription": "/ˈʌɡli/", "translation": "некрасивый, уродливый", "part_of_speech": "adjective", "example": "That is an ugly building.", "example_ru": "Это некрасивое здание."},
        {"word": "young", "transcription": "/jʌŋ/", "translation": "молодой", "part_of_speech": "adjective", "example": "She is young and smart.", "example_ru": "Она молодая и умная."},
        {"word": "tired", "transcription": "/ˈtaɪərd/", "translation": "усталый", "part_of_speech": "adjective", "example": "I am very tired today.", "example_ru": "Я сегодня очень устал."},
        {"word": "hungry", "transcription": "/ˈhʌŋɡri/", "translation": "голодный", "part_of_speech": "adjective", "example": "I am hungry, let's eat.", "example_ru": "Я голоден, давай поедим."},
        {"word": "thirsty", "transcription": "/ˈθɜːrsti/", "translation": "жаждущий, хочу пить", "part_of_speech": "adjective", "example": "I am thirsty, give me water.", "example_ru": "Я хочу пить, дай мне воды."},
        {"word": "sad", "transcription": "/sæd/", "translation": "грустный, печальный", "part_of_speech": "adjective", "example": "Why are you sad?", "example_ru": "Почему ты грустишь?"},
        {"word": "funny", "transcription": "/ˈfʌni/", "translation": "смешной, забавный", "part_of_speech": "adjective", "example": "That joke is very funny.", "example_ru": "Эта шутка очень смешная."},
        {"word": "easy", "transcription": "/ˈiːzi/", "translation": "лёгкий, простой", "part_of_speech": "adjective", "example": "This exercise is easy.", "example_ru": "Это упражнение лёгкое."},
        {"word": "hard", "transcription": "/hɑːrd/", "translation": "твёрдый; трудный", "part_of_speech": "adjective", "example": "This test is hard.", "example_ru": "Этот тест трудный."},
        {"word": "right", "transcription": "/raɪt/", "translation": "правильный; правый", "part_of_speech": "adjective", "example": "That is the right answer.", "example_ru": "Это правильный ответ."},
        {"word": "wrong", "transcription": "/rɒŋ/", "translation": "неправильный", "part_of_speech": "adjective", "example": "Sorry, that is wrong.", "example_ru": "Извини, это неправильно."},
        {"word": "clean", "transcription": "/kliːn/", "translation": "чистый", "part_of_speech": "adjective", "example": "Your hands are clean.", "example_ru": "Твои руки чистые."},
        {"word": "dirty", "transcription": "/ˈdɜːrti/", "translation": "грязный", "part_of_speech": "adjective", "example": "My shoes are dirty.", "example_ru": "Мои ботинки грязные."},
        {"word": "full", "transcription": "/fʊl/", "translation": "полный, сытый", "part_of_speech": "adjective", "example": "The glass is full.", "example_ru": "Стакан полный."},
        {"word": "empty", "transcription": "/ˈempti/", "translation": "пустой", "part_of_speech": "adjective", "example": "The bottle is empty.", "example_ru": "Бутылка пустая."},
        {"word": "open", "transcription": "/ˈəʊpən/", "translation": "открытый; открывать", "part_of_speech": "adjective/verb", "example": "The shop is open.", "example_ru": "Магазин открыт."},
        {"word": "closed", "transcription": "/kləʊzd/", "translation": "закрытый", "part_of_speech": "adjective", "example": "The door is closed.", "example_ru": "Дверь закрыта."},
        {"word": "free", "transcription": "/friː/", "translation": "свободный; бесплатный", "part_of_speech": "adjective", "example": "Are you free this evening?", "example_ru": "Ты свободен сегодня вечером?"},
        {"word": "sure", "transcription": "/ʃʊər/", "translation": "уверенный, конечно", "part_of_speech": "adjective", "example": "Are you sure about that?", "example_ru": "Ты уверен в этом?"},
        {"word": "walk", "transcription": "/wɔːk/", "translation": "идти пешком, гулять", "part_of_speech": "verb", "example": "I walk to school.", "example_ru": "Я хожу в школу пешком."},
        {"word": "sleep", "transcription": "/sliːp/", "translation": "спать", "part_of_speech": "verb", "example": "I sleep eight hours a night.", "example_ru": "Я сплю восемь часов ночью."},
        {"word": "drink", "transcription": "/drɪŋk/", "translation": "пить", "part_of_speech": "verb", "example": "Drink more water.", "example_ru": "Пей больше воды."},
        {"word": "read", "transcription": "/riːd/", "translation": "читать", "part_of_speech": "verb", "example": "I read every night.", "example_ru": "Я читаю каждый вечер."},
        {"word": "write", "transcription": "/raɪt/", "translation": "писать", "part_of_speech": "verb", "example": "Write your name here.", "example_ru": "Напиши своё имя здесь."},
        {"word": "speak", "transcription": "/spiːk/", "translation": "говорить, разговаривать", "part_of_speech": "verb", "example": "Do you speak English?", "example_ru": "Ты говоришь по-английски?"},
        {"word": "listen", "transcription": "/ˈlɪsən/", "translation": "слушать", "part_of_speech": "verb", "example": "Listen to the teacher.", "example_ru": "Слушай учителя."},
        {"word": "know", "transcription": "/nəʊ/", "translation": "знать", "part_of_speech": "verb", "example": "I know the answer.", "example_ru": "Я знаю ответ."},
        {"word": "think", "transcription": "/θɪŋk/", "translation": "думать", "part_of_speech": "verb", "example": "Think before you speak.", "example_ru": "Думай, прежде чем говорить."},
        {"word": "want", "transcription": "/wɒnt/", "translation": "хотеть", "part_of_speech": "verb", "example": "I want a cup of tea.", "example_ru": "Я хочу чашку чая."},
        {"word": "need", "transcription": "/niːd/", "translation": "нуждаться, нужно", "part_of_speech": "verb", "example": "I need your help.", "example_ru": "Мне нужна твоя помощь."},
        {"word": "have", "transcription": "/hæv/", "translation": "иметь, у меня есть", "part_of_speech": "verb", "example": "I have a sister.", "example_ru": "У меня есть сестра."},
        {"word": "give", "transcription": "/ɡɪv/", "translation": "давать", "part_of_speech": "verb", "example": "Give me the book.", "example_ru": "Дай мне книгу."},
        {"word": "take", "transcription": "/teɪk/", "translation": "брать, взять", "part_of_speech": "verb", "example": "Take your umbrella.", "example_ru": "Возьми зонт."},
        {"word": "come", "transcription": "/kʌm/", "translation": "приходить, приезжать", "part_of_speech": "verb", "example": "Come here, please.", "example_ru": "Иди сюда, пожалуйста."},
        {"word": "get", "transcription": "/ɡet/", "translation": "получать; становиться", "part_of_speech": "verb", "example": "I get up at seven.", "example_ru": "Я встаю в семь."},
        {"word": "make", "transcription": "/meɪk/", "translation": "делать, создавать", "part_of_speech": "verb", "example": "I make my bed every morning.", "example_ru": "Я застилаю кровать каждое утро."},
        {"word": "put", "transcription": "/pʊt/", "translation": "класть, ставить", "part_of_speech": "verb", "example": "Put the bag on the table.", "example_ru": "Положи сумку на стол."},
        {"word": "find", "transcription": "/faɪnd/", "translation": "находить", "part_of_speech": "verb", "example": "I can't find my keys.", "example_ru": "Я не могу найти ключи."},
        {"word": "help", "transcription": "/help/", "translation": "помогать; помощь", "part_of_speech": "verb/noun", "example": "Can you help me?", "example_ru": "Ты можешь мне помочь?"},
        {"word": "open", "transcription": "/ˈəʊpən/", "translation": "открывать", "part_of_speech": "verb", "example": "Open the window.", "example_ru": "Открой окно."},
        {"word": "close", "transcription": "/kləʊz/", "translation": "закрывать", "part_of_speech": "verb", "example": "Close the door.", "example_ru": "Закрой дверь."},
        {"word": "sit", "transcription": "/sɪt/", "translation": "сидеть, садиться", "part_of_speech": "verb", "example": "Sit down, please.", "example_ru": "Садитесь, пожалуйста."},
        {"word": "stand", "transcription": "/stænd/", "translation": "стоять", "part_of_speech": "verb", "example": "Stand up!", "example_ru": "Встань!"},
        {"word": "stop", "transcription": "/stɒp/", "translation": "останавливаться, прекращать", "part_of_speech": "verb", "example": "Stop talking!", "example_ru": "Прекрати разговаривать!"},
        {"word": "start", "transcription": "/stɑːrt/", "translation": "начинать", "part_of_speech": "verb", "example": "Let's start the lesson.", "example_ru": "Давайте начнём урок."},
        {"word": "play", "transcription": "/pleɪ/", "translation": "играть", "part_of_speech": "verb", "example": "Children love to play.", "example_ru": "Дети любят играть."},
        {"word": "swim", "transcription": "/swɪm/", "translation": "плавать", "part_of_speech": "verb", "example": "I swim every summer.", "example_ru": "Я плаваю каждое лето."},
        {"word": "draw", "transcription": "/drɔː/", "translation": "рисовать", "part_of_speech": "verb", "example": "She loves to draw.", "example_ru": "Она любит рисовать."},
        {"word": "sing", "transcription": "/sɪŋ/", "translation": "петь", "part_of_speech": "verb", "example": "He sings very well.", "example_ru": "Он очень хорошо поёт."},
        {"word": "dance", "transcription": "/dɑːns/", "translation": "танцевать; танец", "part_of_speech": "verb/noun", "example": "I love to dance.", "example_ru": "Я люблю танцевать."},
        {"word": "cook", "transcription": "/kʊk/", "translation": "готовить (еду)", "part_of_speech": "verb", "example": "My mum cooks very well.", "example_ru": "Моя мама очень хорошо готовит."},
        {"word": "buy", "transcription": "/baɪ/", "translation": "покупать", "part_of_speech": "verb", "example": "I buy bread every day.", "example_ru": "Я покупаю хлеб каждый день."},
        {"word": "pay", "transcription": "/peɪ/", "translation": "платить", "part_of_speech": "verb", "example": "I pay by card.", "example_ru": "Я плачу картой."},
        {"word": "call", "transcription": "/kɔːl/", "translation": "звонить; называть", "part_of_speech": "verb", "example": "Call me later.", "example_ru": "Позвони мне позже."},
        {"word": "ask", "transcription": "/ɑːsk/", "translation": "спрашивать, просить", "part_of_speech": "verb", "example": "Ask the teacher.", "example_ru": "Спроси учителя."},
        {"word": "tell", "transcription": "/tel/", "translation": "говорить, рассказывать", "part_of_speech": "verb", "example": "Tell me your name.", "example_ru": "Скажи мне своё имя."},
        {"word": "show", "transcription": "/ʃəʊ/", "translation": "показывать", "part_of_speech": "verb", "example": "Show me your homework.", "example_ru": "Покажи мне домашнюю работу."},
        {"word": "love", "transcription": "/lʌv/", "translation": "любить; любовь", "part_of_speech": "verb/noun", "example": "I love my family.", "example_ru": "Я люблю свою семью."},
        {"word": "hate", "transcription": "/heɪt/", "translation": "ненавидеть", "part_of_speech": "verb", "example": "I hate cold weather.", "example_ru": "Я ненавижу холодную погоду."},
        {"word": "try", "transcription": "/traɪ/", "translation": "пробовать, стараться", "part_of_speech": "verb", "example": "Try this cake!", "example_ru": "Попробуй этот торт!"},
        {"word": "use", "transcription": "/juːz/", "translation": "использовать", "part_of_speech": "verb", "example": "Use a pencil.", "example_ru": "Используй карандаш."},
        {"word": "turn", "transcription": "/tɜːrn/", "translation": "поворачивать; очередь", "part_of_speech": "verb/noun", "example": "Turn left here.", "example_ru": "Повернись налево здесь."},
        {"word": "carry", "transcription": "/ˈkæri/", "translation": "нести, носить", "part_of_speech": "verb", "example": "Can you carry this bag?", "example_ru": "Ты можешь нести эту сумку?"},
        {"word": "cut", "transcription": "/kʌt/", "translation": "резать", "part_of_speech": "verb", "example": "Cut the bread.", "example_ru": "Нарежь хлеб."},
        {"word": "wash", "transcription": "/wɒʃ/", "translation": "мыть", "part_of_speech": "verb", "example": "Wash your hands.", "example_ru": "Помой руки."},
        {"word": "clean", "transcription": "/kliːn/", "translation": "убирать, чистить", "part_of_speech": "verb", "example": "Clean your room.", "example_ru": "Убери свою комнату."},
        {"word": "live", "transcription": "/lɪv/", "translation": "жить", "part_of_speech": "verb", "example": "Where do you live?", "example_ru": "Где ты живёшь?"},
        {"word": "study", "transcription": "/ˈstʌdi/", "translation": "учиться, изучать", "part_of_speech": "verb", "example": "I study English every day.", "example_ru": "Я изучаю английский каждый день."},
        {"word": "teach", "transcription": "/tiːtʃ/", "translation": "учить, преподавать", "part_of_speech": "verb", "example": "She teaches maths.", "example_ru": "Она преподаёт математику."},
        {"word": "learn", "transcription": "/lɜːrn/", "translation": "учиться, узнавать", "part_of_speech": "verb", "example": "I want to learn Spanish.", "example_ru": "Я хочу выучить испанский."},
        {"word": "morning", "transcription": "/ˈmɔːrnɪŋ/", "translation": "утро", "part_of_speech": "noun", "example": "Good morning!", "example_ru": "Доброе утро!"},
        {"word": "afternoon", "transcription": "/ˌɑːftərˈnuːn/", "translation": "полдень, вторая половина дня", "part_of_speech": "noun", "example": "See you this afternoon.", "example_ru": "Увидимся сегодня днём."},
        {"word": "evening", "transcription": "/ˈiːvnɪŋ/", "translation": "вечер", "part_of_speech": "noun", "example": "Good evening!", "example_ru": "Добрый вечер!"},
        {"word": "night", "transcription": "/naɪt/", "translation": "ночь", "part_of_speech": "noun", "example": "Good night!", "example_ru": "Спокойной ночи!"},
        {"word": "today", "transcription": "/təˈdeɪ/", "translation": "сегодня", "part_of_speech": "adverb", "example": "What day is today?", "example_ru": "Какой сегодня день?"},
        {"word": "tomorrow", "transcription": "/təˈmɒrəʊ/", "translation": "завтра", "part_of_speech": "adverb", "example": "See you tomorrow!", "example_ru": "Увидимся завтра!"},
        {"word": "yesterday", "transcription": "/ˈjestərdeɪ/", "translation": "вчера", "part_of_speech": "adverb", "example": "I was sick yesterday.", "example_ru": "Вчера я был болен."},
        {"word": "week", "transcription": "/wiːk/", "translation": "неделя", "part_of_speech": "noun", "example": "I work five days a week.", "example_ru": "Я работаю пять дней в неделю."},
        {"word": "month", "transcription": "/mʌnθ/", "translation": "месяц", "part_of_speech": "noun", "example": "There are twelve months in a year.", "example_ru": "В году двенадцать месяцев."},
        {"word": "hour", "transcription": "/aʊər/", "translation": "час", "part_of_speech": "noun", "example": "I wait for one hour.", "example_ru": "Я жду один час."},
        {"word": "minute", "transcription": "/ˈmɪnɪt/", "translation": "минута", "part_of_speech": "noun", "example": "Wait a minute!", "example_ru": "Подожди минуту!"},
        {"word": "now", "transcription": "/naʊ/", "translation": "сейчас, теперь", "part_of_speech": "adverb", "example": "Come here now.", "example_ru": "Иди сюда сейчас."},
        {"word": "always", "transcription": "/ˈɔːlweɪz/", "translation": "всегда", "part_of_speech": "adverb", "example": "She always smiles.", "example_ru": "Она всегда улыбается."},
        {"word": "never", "transcription": "/ˈnevər/", "translation": "никогда", "part_of_speech": "adverb", "example": "I never eat meat.", "example_ru": "Я никогда не ем мясо."},
        {"word": "sometimes", "transcription": "/ˈsʌmtaɪmz/", "translation": "иногда", "part_of_speech": "adverb", "example": "I sometimes cook dinner.", "example_ru": "Иногда я готовлю ужин."},
        {"word": "often", "transcription": "/ˈɒfən/", "translation": "часто", "part_of_speech": "adverb", "example": "I often go to the park.", "example_ru": "Я часто хожу в парк."},
        {"word": "again", "transcription": "/əˈɡen/", "translation": "снова, опять", "part_of_speech": "adverb", "example": "Say that again, please.", "example_ru": "Скажи это снова, пожалуйста."},
        {"word": "also", "transcription": "/ˈɔːlsəʊ/", "translation": "тоже, также", "part_of_speech": "adverb", "example": "I also like tea.", "example_ru": "Я тоже люблю чай."},
        {"word": "very", "transcription": "/ˈveri/", "translation": "очень", "part_of_speech": "adverb", "example": "I am very happy.", "example_ru": "Я очень счастлив."},
        {"word": "too", "transcription": "/tuː/", "translation": "слишком; тоже", "part_of_speech": "adverb", "example": "This soup is too hot.", "example_ru": "Этот суп слишком горячий."},
        {"word": "here", "transcription": "/hɪər/", "translation": "здесь, сюда", "part_of_speech": "adverb", "example": "Come here!", "example_ru": "Иди сюда!"},
        {"word": "there", "transcription": "/ðeər/", "translation": "там, туда", "part_of_speech": "adverb", "example": "Go there.", "example_ru": "Иди туда."},
        {"word": "maybe", "transcription": "/ˈmeɪbi/", "translation": "может быть", "part_of_speech": "adverb", "example": "Maybe I will come.", "example_ru": "Может быть, я приду."},
        {"word": "please", "transcription": "/pliːz/", "translation": "пожалуйста", "part_of_speech": "adverb", "example": "Can you help me, please?", "example_ru": "Ты можешь мне помочь, пожалуйста?"},
        {"word": "number", "transcription": "/ˈnʌmbər/", "translation": "число, номер", "part_of_speech": "noun", "example": "What is your phone number?", "example_ru": "Какой у тебя номер телефона?"},
        {"word": "name", "transcription": "/neɪm/", "translation": "имя, название", "part_of_speech": "noun", "example": "What is your name?", "example_ru": "Как тебя зовут?"},
        {"word": "word", "transcription": "/wɜːrd/", "translation": "слово", "part_of_speech": "noun", "example": "I learn ten words a day.", "example_ru": "Я учу десять слов в день."},
        {"word": "letter", "transcription": "/ˈletər/", "translation": "письмо; буква", "part_of_speech": "noun", "example": "I got a letter from my friend.", "example_ru": "Я получил письмо от друга."},
        {"word": "colour", "transcription": "/ˈkʌlər/", "translation": "цвет", "part_of_speech": "noun", "example": "What is your favourite colour?", "example_ru": "Какой твой любимый цвет?"},
        {"word": "photo", "transcription": "/ˈfəʊtəʊ/", "translation": "фотография", "part_of_speech": "noun", "example": "I took a photo.", "example_ru": "Я сделал фотографию."},
        {"word": "map", "transcription": "/mæp/", "translation": "карта", "part_of_speech": "noun", "example": "Look at the map.", "example_ru": "Посмотри на карту."},
        {"word": "pen", "transcription": "/pen/", "translation": "ручка", "part_of_speech": "noun", "example": "Give me a pen.", "example_ru": "Дай мне ручку."},
        {"word": "pencil", "transcription": "/ˈpensəl/", "translation": "карандаш", "part_of_speech": "noun", "example": "Draw with a pencil.", "example_ru": "Рисуй карандашом."},
        {"word": "paper", "transcription": "/ˈpeɪpər/", "translation": "бумага", "part_of_speech": "noun", "example": "Write it on paper.", "example_ru": "Напиши это на бумаге."},
        {"word": "umbrella", "transcription": "/ʌmˈbrelə/", "translation": "зонт", "part_of_speech": "noun", "example": "Take an umbrella, it will rain.", "example_ru": "Возьми зонт, будет дождь."},
        {"word": "rain", "transcription": "/reɪn/", "translation": "дождь; идти (о дожде)", "part_of_speech": "noun/verb", "example": "I love the rain.", "example_ru": "Я люблю дождь."},
        {"word": "snow", "transcription": "/snəʊ/", "translation": "снег; идти (о снеге)", "part_of_speech": "noun/verb", "example": "Children play in the snow.", "example_ru": "Дети играют в снегу."},
        {"word": "sky", "transcription": "/skaɪ/", "translation": "небо", "part_of_speech": "noun", "example": "The sky is clear today.", "example_ru": "Небо сегодня ясное."},
        {"word": "sea", "transcription": "/siː/", "translation": "море", "part_of_speech": "noun", "example": "We swim in the sea.", "example_ru": "Мы купаемся в море."},
        {"word": "river", "transcription": "/ˈrɪvər/", "translation": "река", "part_of_speech": "noun", "example": "The river is wide.", "example_ru": "Река широкая."},
        {"word": "mountain", "transcription": "/ˈmaʊntɪn/", "translation": "гора", "part_of_speech": "noun", "example": "The mountain is very high.", "example_ru": "Гора очень высокая."},
        {"word": "flower", "transcription": "/ˈflaʊər/", "translation": "цветок", "part_of_speech": "noun", "example": "She gave me a flower.", "example_ru": "Она подарила мне цветок."},
        {"word": "bird", "transcription": "/bɜːrd/", "translation": "птица", "part_of_speech": "noun", "example": "A bird is singing.", "example_ru": "Птица поёт."},
        {"word": "horse", "transcription": "/hɔːrs/", "translation": "лошадь", "part_of_speech": "noun", "example": "She rides a horse.", "example_ru": "Она ездит на лошади."},
        {"word": "cow", "transcription": "/kaʊ/", "translation": "корова", "part_of_speech": "noun", "example": "The cow gives milk.", "example_ru": "Корова даёт молоко."},
        {"word": "pig", "transcription": "/pɪɡ/", "translation": "свинья", "part_of_speech": "noun", "example": "There is a pig on the farm.", "example_ru": "На ферме есть свинья."},
        {"word": "rabbit", "transcription": "/ˈræbɪt/", "translation": "кролик", "part_of_speech": "noun", "example": "My rabbit is white.", "example_ru": "Мой кролик белый."},
        {"word": "lion", "transcription": "/ˈlaɪən/", "translation": "лев", "part_of_speech": "noun", "example": "The lion is the king of animals.", "example_ru": "Лев — царь зверей."},
        {"word": "elephant", "transcription": "/ˈelɪfənt/", "translation": "слон", "part_of_speech": "noun", "example": "Elephants are very big.", "example_ru": "Слоны очень большие."},
        {"word": "bear", "transcription": "/beər/", "translation": "медведь", "part_of_speech": "noun", "example": "The bear lives in the forest.", "example_ru": "Медведь живёт в лесу."},
        {"word": "monkey", "transcription": "/ˈmʌŋki/", "translation": "обезьяна", "part_of_speech": "noun", "example": "The monkey climbs the tree.", "example_ru": "Обезьяна лезет на дерево."},
        {"word": "fish", "transcription": "/fɪʃ/", "translation": "рыба", "part_of_speech": "noun", "example": "I have five fish in my tank.", "example_ru": "В моём аквариуме пять рыбок."},
        {"word": "forest", "transcription": "/ˈfɒrɪst/", "translation": "лес", "part_of_speech": "noun", "example": "We walk in the forest.", "example_ru": "Мы гуляем в лесу."},
        {"word": "island", "transcription": "/ˈaɪlənd/", "translation": "остров", "part_of_speech": "noun", "example": "They live on a small island.", "example_ru": "Они живут на маленьком острове."},
        {"word": "world", "transcription": "/wɜːrld/", "translation": "мир, свет", "part_of_speech": "noun", "example": "I want to see the world.", "example_ru": "Я хочу увидеть мир."},
        {"word": "country", "transcription": "/ˈkʌntri/", "translation": "страна", "part_of_speech": "noun", "example": "What country are you from?", "example_ru": "Из какой ты страны?"},
        {"word": "language", "transcription": "/ˈlæŋɡwɪdʒ/", "translation": "язык (речь)", "part_of_speech": "noun", "example": "English is a world language.", "example_ru": "Английский — мировой язык."},
        {"word": "hello", "transcription": "/həˈləʊ/", "translation": "привет, здравствуй", "part_of_speech": "exclamation", "example": "Hello! How are you?", "example_ru": "Привет! Как дела?"},
        {"word": "bye", "transcription": "/baɪ/", "translation": "пока, до свидания", "part_of_speech": "exclamation", "example": "Bye! See you tomorrow.", "example_ru": "Пока! Увидимся завтра."},
        {"word": "yes", "transcription": "/jes/", "translation": "да", "part_of_speech": "exclamation", "example": "Yes, I agree.", "example_ru": "Да, я согласен."},
        {"word": "no", "transcription": "/nəʊ/", "translation": "нет", "part_of_speech": "exclamation", "example": "No, thank you.", "example_ru": "Нет, спасибо."},
        {"word": "sorry", "transcription": "/ˈsɒri/", "translation": "извини, сожалею", "part_of_speech": "exclamation", "example": "Sorry, I am late.", "example_ru": "Извини, я опоздал."},
        {"word": "thanks", "transcription": "/θæŋks/", "translation": "спасибо", "part_of_speech": "exclamation", "example": "Thanks for your help!", "example_ru": "Спасибо за помощь!"},
        {"word": "okay", "transcription": "/ˌəʊˈkeɪ/", "translation": "хорошо, окей", "part_of_speech": "exclamation", "example": "Okay, let's go!", "example_ru": "Хорошо, пойдём!"},
        {"word": "great", "transcription": "/ɡreɪt/", "translation": "отличный, замечательный", "part_of_speech": "adjective", "example": "That is a great idea!", "example_ru": "Это отличная идея!"},
        {"word": "wow", "transcription": "/waʊ/", "translation": "вау, ого", "part_of_speech": "exclamation", "example": "Wow, that is amazing!", "example_ru": "Ого, это удивительно!"},
        {"word": "one", "transcription": "/wʌn/", "translation": "один", "part_of_speech": "numeral", "example": "I have one brother.", "example_ru": "У меня один брат."},
        {"word": "two", "transcription": "/tuː/", "translation": "два", "part_of_speech": "numeral", "example": "She has two cats.", "example_ru": "У неё две кошки."},
        {"word": "three", "transcription": "/θriː/", "translation": "три", "part_of_speech": "numeral", "example": "There are three books.", "example_ru": "Там три книги."},
        {"word": "four", "transcription": "/fɔːr/", "translation": "четыре", "part_of_speech": "numeral", "example": "We have four seasons.", "example_ru": "У нас четыре времени года."},
        {"word": "five", "transcription": "/faɪv/", "translation": "пять", "part_of_speech": "numeral", "example": "He is five years old.", "example_ru": "Ему пять лет."},
        {"word": "ten", "transcription": "/ten/", "translation": "десять", "part_of_speech": "numeral", "example": "I wait ten minutes.", "example_ru": "Я жду десять минут."},
        {"word": "hundred", "transcription": "/ˈhʌndrəd/", "translation": "сто", "part_of_speech": "numeral", "example": "There are a hundred people here.", "example_ru": "Здесь сто человек."},
        {"word": "second", "transcription": "/ˈsekənd/", "translation": "секунда; второй", "part_of_speech": "noun/adjective", "example": "Wait one second.", "example_ru": "Подожди одну секунду."},
        {"word": "clock", "transcription": "/klɒk/", "translation": "часы (настенные/настольные)", "part_of_speech": "noun", "example": "The clock is on the wall.", "example_ru": "Часы висят на стене."},
        {"word": "calendar", "transcription": "/ˈkælɪndər/", "translation": "календарь", "part_of_speech": "noun", "example": "Check the calendar.", "example_ru": "Посмотри в календарь."},
        {"word": "Monday", "transcription": "/ˈmʌndeɪ/", "translation": "понедельник", "part_of_speech": "noun", "example": "School starts on Monday.", "example_ru": "Школа начинается в понедельник."},
        {"word": "Tuesday", "transcription": "/ˈtjuːzdeɪ/", "translation": "вторник", "part_of_speech": "noun", "example": "I have a lesson on Tuesday.", "example_ru": "В вторник у меня урок."},
        {"word": "Wednesday", "transcription": "/ˈwenzdeɪ/", "translation": "среда", "part_of_speech": "noun", "example": "We meet on Wednesday.", "example_ru": "Мы встречаемся в среду."},
        {"word": "Thursday", "transcription": "/ˈθɜːrzdeɪ/", "translation": "четверг", "part_of_speech": "noun", "example": "Thursday is almost Friday.", "example_ru": "Четверг — почти пятница."},
        {"word": "Friday", "transcription": "/ˈfraɪdeɪ/", "translation": "пятница", "part_of_speech": "noun", "example": "We rest on Friday evening.", "example_ru": "Мы отдыхаем в пятничный вечер."},
        {"word": "Saturday", "transcription": "/ˈsætərdeɪ/", "translation": "суббота", "part_of_speech": "noun", "example": "I sleep long on Saturday.", "example_ru": "В субботу я долго сплю."},
        {"word": "Sunday", "transcription": "/ˈsʌndeɪ/", "translation": "воскресенье", "part_of_speech": "noun", "example": "Sunday is a day of rest.", "example_ru": "Воскресенье — день отдыха."},
        {"word": "January", "transcription": "/ˈdʒænjuəri/", "translation": "январь", "part_of_speech": "noun", "example": "January is cold.", "example_ru": "Январь холодный."},
        {"word": "February", "transcription": "/ˈfebruəri/", "translation": "февраль", "part_of_speech": "noun", "example": "February has 28 days.", "example_ru": "В феврале 28 дней."},
        {"word": "March", "transcription": "/mɑːrtʃ/", "translation": "март", "part_of_speech": "noun", "example": "Spring starts in March.", "example_ru": "Весна начинается в марте."},
        {"word": "April", "transcription": "/ˈeɪprəl/", "translation": "апрель", "part_of_speech": "noun", "example": "It often rains in April.", "example_ru": "В апреле часто идёт дождь."},
        {"word": "May", "transcription": "/meɪ/", "translation": "май", "part_of_speech": "noun", "example": "Flowers bloom in May.", "example_ru": "В мае цветут цветы."},
        {"word": "June", "transcription": "/dʒuːn/", "translation": "июнь", "part_of_speech": "noun", "example": "School ends in June.", "example_ru": "Школа заканчивается в июне."},
        {"word": "July", "transcription": "/dʒuˈlaɪ/", "translation": "июль", "part_of_speech": "noun", "example": "July is the hottest month.", "example_ru": "Июль — самый жаркий месяц."},
        {"word": "August", "transcription": "/ˈɔːɡəst/", "translation": "август", "part_of_speech": "noun", "example": "We go on holiday in August.", "example_ru": "В августе мы едем в отпуск."},
        {"word": "September", "transcription": "/sepˈtembər/", "translation": "сентябрь", "part_of_speech": "noun", "example": "School starts in September.", "example_ru": "Школа начинается в сентябре."},
        {"word": "October", "transcription": "/ɒkˈtəʊbər/", "translation": "октябрь", "part_of_speech": "noun", "example": "Leaves fall in October.", "example_ru": "В октябре падают листья."},
        {"word": "November", "transcription": "/nəʊˈvembər/", "translation": "ноябрь", "part_of_speech": "noun", "example": "November is grey and cold.", "example_ru": "Ноябрь серый и холодный."},
        {"word": "December", "transcription": "/dɪˈsembər/", "translation": "декабрь", "part_of_speech": "noun", "example": "Christmas is in December.", "example_ru": "Рождество в декабре."},
        {"word": "head", "transcription": "/hed/", "translation": "голова", "part_of_speech": "noun", "example": "My head hurts.", "example_ru": "У меня болит голова."},
        {"word": "face", "transcription": "/feɪs/", "translation": "лицо", "part_of_speech": "noun", "example": "Wash your face.", "example_ru": "Умойся."},
        {"word": "eye", "transcription": "/aɪ/", "translation": "глаз", "part_of_speech": "noun", "example": "She has blue eyes.", "example_ru": "У неё голубые глаза."},
        {"word": "ear", "transcription": "/ɪər/", "translation": "ухо", "part_of_speech": "noun", "example": "I hear with my ears.", "example_ru": "Я слышу ушами."},
        {"word": "nose", "transcription": "/nəʊz/", "translation": "нос", "part_of_speech": "noun", "example": "My nose is cold.", "example_ru": "У меня холодный нос."},
        {"word": "mouth", "transcription": "/maʊθ/", "translation": "рот", "part_of_speech": "noun", "example": "Open your mouth.", "example_ru": "Открой рот."},
        {"word": "teeth", "transcription": "/tiːθ/", "translation": "зубы", "part_of_speech": "noun", "example": "Brush your teeth every day.", "example_ru": "Чисти зубы каждый день."},
        {"word": "hair", "transcription": "/heər/", "translation": "волосы", "part_of_speech": "noun", "example": "She has long black hair.", "example_ru": "У неё длинные чёрные волосы."},
        {"word": "hand", "transcription": "/hænd/", "translation": "рука (кисть)", "part_of_speech": "noun", "example": "Give me your hand.", "example_ru": "Дай мне руку."},
        {"word": "arm", "transcription": "/ɑːrm/", "translation": "рука (от плеча)", "part_of_speech": "noun", "example": "He broke his arm.", "example_ru": "Он сломал руку."},
        {"word": "leg", "transcription": "/leɡ/", "translation": "нога (от бедра)", "part_of_speech": "noun", "example": "My leg hurts.", "example_ru": "У меня болит нога."},
        {"word": "foot", "transcription": "/fʊt/", "translation": "стопа, нога", "part_of_speech": "noun", "example": "My foot is sore.", "example_ru": "У меня болит стопа."},
        {"word": "back", "transcription": "/bæk/", "translation": "спина; назад", "part_of_speech": "noun/adverb", "example": "My back hurts from sitting.", "example_ru": "Спина болит от сидения."},
        {"word": "heart", "transcription": "/hɑːrt/", "translation": "сердце", "part_of_speech": "noun", "example": "The heart pumps blood.", "example_ru": "Сердце качает кровь."},
        {"word": "stomach", "transcription": "/ˈstʌmək/", "translation": "желудок, живот", "part_of_speech": "noun", "example": "My stomach hurts.", "example_ru": "У меня болит живот."},
        {"word": "finger", "transcription": "/ˈfɪŋɡər/", "translation": "палец (руки)", "part_of_speech": "noun", "example": "She cut her finger.", "example_ru": "Она порезала палец."},
        {"word": "shoulder", "transcription": "/ˈʃəʊldər/", "translation": "плечо", "part_of_speech": "noun", "example": "He put his hand on my shoulder.", "example_ru": "Он положил руку мне на плечо."},
        {"word": "knee", "transcription": "/niː/", "translation": "колено", "part_of_speech": "noun", "example": "She hurt her knee.", "example_ru": "Она ударила колено."},
        {"word": "stairs", "transcription": "/steərz/", "translation": "лестница", "part_of_speech": "noun", "example": "Walk up the stairs.", "example_ru": "Поднимись по лестнице."},
        {"word": "ceiling", "transcription": "/ˈsiːlɪŋ/", "translation": "потолок", "part_of_speech": "noun", "example": "The ceiling is white.", "example_ru": "Потолок белый."},
        {"word": "toilet", "transcription": "/ˈtɔɪlɪt/", "translation": "туалет", "part_of_speech": "noun", "example": "Where is the toilet?", "example_ru": "Где туалет?"},
        {"word": "towel", "transcription": "/ˈtaʊəl/", "translation": "полотенце", "part_of_speech": "noun", "example": "Use a clean towel.", "example_ru": "Используй чистое полотенце."},
        {"word": "soap", "transcription": "/səʊp/", "translation": "мыло", "part_of_speech": "noun", "example": "Wash with soap.", "example_ru": "Мойся с мылом."},
        {"word": "pillow", "transcription": "/ˈpɪləʊ/", "translation": "подушка", "part_of_speech": "noun", "example": "I have two soft pillows.", "example_ru": "У меня две мягкие подушки."},
        {"word": "blanket", "transcription": "/ˈblæŋkɪt/", "translation": "одеяло", "part_of_speech": "noun", "example": "Pull the blanket over you.", "example_ru": "Натяни на себя одеяло."},
        {"word": "glitter", "transcription": "/ˈɡlɪtər/", "translation": "блестеть; блёстки", "part_of_speech": "verb/noun", "example": "The stars glitter at night.", "example_ru": "Звёзды блестят ночью."},
        {"word": "bin", "transcription": "/bɪn/", "translation": "мусорное ведро", "part_of_speech": "noun", "example": "Throw it in the bin.", "example_ru": "Выброси это в мусорное ведро."},
        {"word": "lock", "transcription": "/lɒk/", "translation": "замок; запирать", "part_of_speech": "noun/verb", "example": "Lock the door before you leave.", "example_ru": "Запри дверь перед уходом."},
        {"word": "light", "transcription": "/laɪt/", "translation": "свет; включать свет", "part_of_speech": "noun/verb", "example": "Turn on the light.", "example_ru": "Включи свет."},
        {"word": "jacket", "transcription": "/ˈdʒækɪt/", "translation": "куртка, пиджак", "part_of_speech": "noun", "example": "Take your jacket, it's cold.", "example_ru": "Возьми куртку, холодно."},
        {"word": "jeans", "transcription": "/dʒiːnz/", "translation": "джинсы", "part_of_speech": "noun", "example": "He wears jeans every day.", "example_ru": "Он носит джинсы каждый день."},
        {"word": "skirt", "transcription": "/skɜːrt/", "translation": "юбка", "part_of_speech": "noun", "example": "She wears a long skirt.", "example_ru": "Она носит длинную юбку."},
        {"word": "socks", "transcription": "/sɒks/", "translation": "носки", "part_of_speech": "noun", "example": "Put on clean socks.", "example_ru": "Надень чистые носки."},
        {"word": "boots", "transcription": "/buːts/", "translation": "ботинки, сапоги", "part_of_speech": "noun", "example": "Wear boots in the snow.", "example_ru": "Носи ботинки в снег."},
        {"word": "scarf", "transcription": "/skɑːrf/", "translation": "шарф", "part_of_speech": "noun", "example": "Wear a scarf in winter.", "example_ru": "Носи шарф зимой."},
        {"word": "gloves", "transcription": "/ɡlʌvz/", "translation": "перчатки", "part_of_speech": "noun", "example": "My hands are cold without gloves.", "example_ru": "Мои руки мёрзнут без перчаток."},
        {"word": "pyjamas", "transcription": "/pəˈdʒɑːməz/", "translation": "пижама", "part_of_speech": "noun", "example": "I wear pyjamas to bed.", "example_ru": "Я сплю в пижаме."},
        {"word": "uniform", "transcription": "/ˈjuːnɪfɔːrm/", "translation": "форма (одежда)", "part_of_speech": "noun", "example": "Pupils wear a school uniform.", "example_ru": "Ученики носят школьную форму."},
        {"word": "tie", "transcription": "/taɪ/", "translation": "галстук; завязывать", "part_of_speech": "noun/verb", "example": "He wears a tie to work.", "example_ru": "Он носит галстук на работу."},
        {"word": "pocket", "transcription": "/ˈpɒkɪt/", "translation": "карман", "part_of_speech": "noun", "example": "Put it in your pocket.", "example_ru": "Положи в карман."},
        {"word": "boat", "transcription": "/bəʊt/", "translation": "лодка", "part_of_speech": "noun", "example": "We crossed the river by boat.", "example_ru": "Мы переплыли реку на лодке."},
        {"word": "ship", "transcription": "/ʃɪp/", "translation": "корабль", "part_of_speech": "noun", "example": "The ship is very big.", "example_ru": "Корабль очень большой."},
        {"word": "truck", "transcription": "/trʌk/", "translation": "грузовик", "part_of_speech": "noun", "example": "A big truck is on the road.", "example_ru": "На дороге большой грузовик."},
        {"word": "motorcycle", "transcription": "/ˈməʊtəsaɪkəl/", "translation": "мотоцикл", "part_of_speech": "noun", "example": "He rides a red motorcycle.", "example_ru": "Он ездит на красном мотоцикле."},
        {"word": "traffic light", "transcription": "/ˈtræfɪk laɪt/", "translation": "светофор", "part_of_speech": "noun", "example": "Stop at the red traffic light.", "example_ru": "Остановись на красном светофоре."},
        {"word": "pavement", "transcription": "/ˈpeɪvmənt/", "translation": "тротуар", "part_of_speech": "noun", "example": "Walk on the pavement.", "example_ru": "Иди по тротуару."},
        {"word": "postbox", "transcription": "/ˈpəʊstbɒks/", "translation": "почтовый ящик", "part_of_speech": "noun", "example": "Put the letter in the postbox.", "example_ru": "Брось письмо в почтовый ящик."},
        {"word": "church", "transcription": "/tʃɜːrtʃ/", "translation": "церковь", "part_of_speech": "noun", "example": "There is a church in the village.", "example_ru": "В деревне есть церковь."},
        {"word": "village", "transcription": "/ˈvɪlɪdʒ/", "translation": "деревня, село", "part_of_speech": "noun", "example": "She grew up in a small village.", "example_ru": "Она выросла в маленькой деревне."},
        {"word": "field", "transcription": "/fiːld/", "translation": "поле", "part_of_speech": "noun", "example": "Cows eat grass in the field.", "example_ru": "Коровы едят траву на поле."},
        {"word": "farm", "transcription": "/fɑːrm/", "translation": "ферма", "part_of_speech": "noun", "example": "My uncle has a farm.", "example_ru": "У моего дяди есть ферма."},
        {"word": "path", "transcription": "/pɑːθ/", "translation": "тропинка, дорожка", "part_of_speech": "noun", "example": "Follow the path through the forest.", "example_ru": "Иди по тропинке через лес."},
        {"word": "flag", "transcription": "/flæɡ/", "translation": "флаг", "part_of_speech": "noun", "example": "The flag is red and white.", "example_ru": "Флаг красно-белый."},
        {"word": "sign", "transcription": "/saɪn/", "translation": "знак, вывеска", "part_of_speech": "noun", "example": "Read the sign on the door.", "example_ru": "Прочитай вывеску на двери."},
        {"word": "lake", "transcription": "/leɪk/", "translation": "озеро", "part_of_speech": "noun", "example": "We swim in the lake.", "example_ru": "Мы купаемся в озере."},
        {"word": "sand", "transcription": "/sænd/", "translation": "песок", "part_of_speech": "noun", "example": "Children play in the sand.", "example_ru": "Дети играют в песке."},
        {"word": "beach", "transcription": "/biːtʃ/", "translation": "пляж", "part_of_speech": "noun", "example": "Let's go to the beach!", "example_ru": "Пойдём на пляж!"},
        {"word": "rock", "transcription": "/rɒk/", "translation": "скала, камень", "part_of_speech": "noun", "example": "Sit on that rock.", "example_ru": "Сядь на тот камень."},
        {"word": "hill", "transcription": "/hɪl/", "translation": "холм", "part_of_speech": "noun", "example": "We climbed up the hill.", "example_ru": "Мы поднялись на холм."},
        {"word": "ground", "transcription": "/ɡraʊnd/", "translation": "земля, почва", "part_of_speech": "noun", "example": "The apple fell to the ground.", "example_ru": "Яблоко упало на землю."},
        {"word": "leaf", "transcription": "/liːf/", "translation": "лист (дерева)", "part_of_speech": "noun", "example": "The leaf is green.", "example_ru": "Лист зелёный."},
        {"word": "branch", "transcription": "/brɑːntʃ/", "translation": "ветка", "part_of_speech": "noun", "example": "A bird sat on the branch.", "example_ru": "Птица сидела на ветке."},
        {"word": "grass", "transcription": "/ɡrɑːs/", "translation": "трава", "part_of_speech": "noun", "example": "The grass is very green.", "example_ru": "Трава очень зелёная."},
        {"word": "fire", "transcription": "/faɪər/", "translation": "огонь, пожар", "part_of_speech": "noun", "example": "Be careful with fire.", "example_ru": "Будь осторожен с огнём."},
        {"word": "moon", "transcription": "/muːn/", "translation": "луна", "part_of_speech": "noun", "example": "The moon is bright tonight.", "example_ru": "Сегодня ночью луна яркая."},
        {"word": "star", "transcription": "/stɑːr/", "translation": "звезда", "part_of_speech": "noun", "example": "I can see many stars.", "example_ru": "Я вижу много звёзд."},
        {"word": "ice", "transcription": "/aɪs/", "translation": "лёд", "part_of_speech": "noun", "example": "The lake is covered in ice.", "example_ru": "Озеро покрыто льдом."},
        {"word": "air", "transcription": "/eər/", "translation": "воздух", "part_of_speech": "noun", "example": "The air is clean here.", "example_ru": "Здесь чистый воздух."},
        {"word": "wolf", "transcription": "/wʊlf/", "translation": "волк", "part_of_speech": "noun", "example": "The wolf lives in the forest.", "example_ru": "Волк живёт в лесу."},
        {"word": "fox", "transcription": "/fɒks/", "translation": "лиса", "part_of_speech": "noun", "example": "The fox is clever.", "example_ru": "Лиса хитрая."},
        {"word": "duck", "transcription": "/dʌk/", "translation": "утка", "part_of_speech": "noun", "example": "Ducks swim on the pond.", "example_ru": "Утки плавают в пруду."},
        {"word": "hen", "transcription": "/hen/", "translation": "курица", "part_of_speech": "noun", "example": "The hen lays eggs.", "example_ru": "Курица несёт яйца."},
        {"word": "sheep", "transcription": "/ʃiːp/", "translation": "овца", "part_of_speech": "noun", "example": "There are sheep on the farm.", "example_ru": "На ферме есть овцы."},
        {"word": "goat", "transcription": "/ɡəʊt/", "translation": "коза", "part_of_speech": "noun", "example": "The goat eats grass.", "example_ru": "Коза ест траву."},
        {"word": "mouse", "transcription": "/maʊs/", "translation": "мышь", "part_of_speech": "noun", "example": "There is a mouse in the kitchen.", "example_ru": "На кухне мышь."},
        {"word": "frog", "transcription": "/frɒɡ/", "translation": "лягушка", "part_of_speech": "noun", "example": "The frog jumps into the pond.", "example_ru": "Лягушка прыгает в пруд."},
        {"word": "butterfly", "transcription": "/ˈbʌtəflaɪ/", "translation": "бабочка", "part_of_speech": "noun", "example": "A butterfly landed on the flower.", "example_ru": "Бабочка села на цветок."},
        {"word": "bee", "transcription": "/biː/", "translation": "пчела", "part_of_speech": "noun", "example": "Bees make honey.", "example_ru": "Пчёлы делают мёд."},
        {"word": "spider", "transcription": "/ˈspaɪdər/", "translation": "паук", "part_of_speech": "noun", "example": "There is a spider on the wall.", "example_ru": "На стене паук."},
        {"word": "turtle", "transcription": "/ˈtɜːrtəl/", "translation": "черепаха", "part_of_speech": "noun", "example": "The turtle is slow.", "example_ru": "Черепаха медленная."},
        {"word": "parrot", "transcription": "/ˈpærət/", "translation": "попугай", "part_of_speech": "noun", "example": "The parrot can talk.", "example_ru": "Попугай умеет говорить."},
        {"word": "hamster", "transcription": "/ˈhæmstər/", "translation": "хомяк", "part_of_speech": "noun", "example": "My hamster runs in a wheel.", "example_ru": "Мой хомяк бегает в колесе."},
        {"word": "tiger", "transcription": "/ˈtaɪɡər/", "translation": "тигр", "part_of_speech": "noun", "example": "The tiger is orange and black.", "example_ru": "Тигр оранжево-чёрный."},
        {"word": "giraffe", "transcription": "/dʒɪˈrɑːf/", "translation": "жираф", "part_of_speech": "noun", "example": "The giraffe has a long neck.", "example_ru": "У жирафа длинная шея."},
        {"word": "zebra", "transcription": "/ˈzebrə/", "translation": "зебра", "part_of_speech": "noun", "example": "A zebra has black and white stripes.", "example_ru": "У зебры чёрно-белые полосы."},
        {"word": "crocodile", "transcription": "/ˈkrɒkədaɪl/", "translation": "крокодил", "part_of_speech": "noun", "example": "The crocodile lives in the river.", "example_ru": "Крокодил живёт в реке."},
        {"word": "honey", "transcription": "/ˈhʌni/", "translation": "мёд", "part_of_speech": "noun", "example": "I put honey in my tea.", "example_ru": "Я кладу мёд в чай."},
        {"word": "jam", "transcription": "/dʒæm/", "translation": "варенье, джем", "part_of_speech": "noun", "example": "I love strawberry jam.", "example_ru": "Я люблю клубничное варенье."},
        {"word": "biscuit", "transcription": "/ˈbɪskɪt/", "translation": "печенье", "part_of_speech": "noun", "example": "Have a biscuit with your tea.", "example_ru": "Возьми печенье к чаю."},
        {"word": "chocolate", "transcription": "/ˈtʃɒklɪt/", "translation": "шоколад", "part_of_speech": "noun", "example": "I love dark chocolate.", "example_ru": "Я люблю тёмный шоколад."},
        {"word": "ice cream", "transcription": "/ˈaɪs kriːm/", "translation": "мороженое", "part_of_speech": "noun", "example": "I want chocolate ice cream.", "example_ru": "Я хочу шоколадное мороженое."},
        {"word": "salad", "transcription": "/ˈsæləd/", "translation": "салат", "part_of_speech": "noun", "example": "I eat salad every day.", "example_ru": "Я ем салат каждый день."},
        {"word": "sandwich", "transcription": "/ˈsænwɪdʒ/", "translation": "бутерброд, сэндвич", "part_of_speech": "noun", "example": "I made a cheese sandwich.", "example_ru": "Я сделал бутерброд с сыром."},
        {"word": "pizza", "transcription": "/ˈpiːtsə/", "translation": "пицца", "part_of_speech": "noun", "example": "Pizza is my favourite food.", "example_ru": "Пицца — моя любимая еда."},
        {"word": "pasta", "transcription": "/ˈpæstə/", "translation": "паста, макароны", "part_of_speech": "noun", "example": "I cook pasta twice a week.", "example_ru": "Я готовлю пасту дважды в неделю."},
        {"word": "onion", "transcription": "/ˈʌnjən/", "translation": "лук (репчатый)", "part_of_speech": "noun", "example": "Onion makes me cry.", "example_ru": "Лук заставляет меня плакать."},
        {"word": "carrot", "transcription": "/ˈkærət/", "translation": "морковь", "part_of_speech": "noun", "example": "Rabbits love carrots.", "example_ru": "Кролики любят морковь."},
        {"word": "corn", "transcription": "/kɔːrn/", "translation": "кукуруза", "part_of_speech": "noun", "example": "We grill corn in summer.", "example_ru": "Мы жарим кукурузу летом."},
        {"word": "lemon", "transcription": "/ˈlemən/", "translation": "лимон", "part_of_speech": "noun", "example": "Lemon is sour.", "example_ru": "Лимон кислый."},
        {"word": "grape", "transcription": "/ɡreɪp/", "translation": "виноград", "part_of_speech": "noun", "example": "These grapes are sweet.", "example_ru": "Этот виноград сладкий."},
        {"word": "strawberry", "transcription": "/ˈstrɔːbəri/", "translation": "клубника", "part_of_speech": "noun", "example": "I love fresh strawberries.", "example_ru": "Я люблю свежую клубнику."},
        {"word": "watermelon", "transcription": "/ˈwɔːtəmelən/", "translation": "арбуз", "part_of_speech": "noun", "example": "Watermelon is good in summer.", "example_ru": "Арбуз хорош летом."},
        {"word": "pear", "transcription": "/peər/", "translation": "груша", "part_of_speech": "noun", "example": "The pear is ripe and sweet.", "example_ru": "Груша спелая и сладкая."},
        {"word": "peach", "transcription": "/piːtʃ/", "translation": "персик", "part_of_speech": "noun", "example": "Peaches are my favourite fruit.", "example_ru": "Персики — мои любимые фрукты."},
        {"word": "cucumber", "transcription": "/ˈkjuːkʌmbər/", "translation": "огурец", "part_of_speech": "noun", "example": "I put cucumber in my salad.", "example_ru": "Я кладу огурец в салат."},
        {"word": "mushroom", "transcription": "/ˈmʌʃruːm/", "translation": "гриб", "part_of_speech": "noun", "example": "I like mushroom soup.", "example_ru": "Мне нравится грибной суп."},
        {"word": "yoghurt", "transcription": "/ˈjɒɡət/", "translation": "йогурт", "part_of_speech": "noun", "example": "I eat yoghurt for breakfast.", "example_ru": "На завтрак я ем йогурт."},
        {"word": "oil", "transcription": "/ɔɪl/", "translation": "масло (растительное)", "part_of_speech": "noun", "example": "Fry in a little oil.", "example_ru": "Жарь на небольшом количестве масла."},
        {"word": "flour", "transcription": "/flaʊər/", "translation": "мука", "part_of_speech": "noun", "example": "I need flour to bake bread.", "example_ru": "Мне нужна мука, чтобы испечь хлеб."},
        {"word": "notebook", "transcription": "/ˈnəʊtbʊk/", "translation": "тетрадь", "part_of_speech": "noun", "example": "Write in your notebook.", "example_ru": "Пиши в тетрадь."},
        {"word": "ruler", "transcription": "/ˈruːlər/", "translation": "линейка", "part_of_speech": "noun", "example": "Use a ruler to draw a line.", "example_ru": "Используй линейку, чтобы нарисовать линию."},
        {"word": "eraser", "transcription": "/ɪˈreɪzər/", "translation": "ластик", "part_of_speech": "noun", "example": "Use the eraser to fix mistakes.", "example_ru": "Используй ластик, чтобы исправить ошибки."},
        {"word": "scissors", "transcription": "/ˈsɪzərz/", "translation": "ножницы", "part_of_speech": "noun", "example": "Cut the paper with scissors.", "example_ru": "Разрежь бумагу ножницами."},
        {"word": "glue", "transcription": "/ɡluː/", "translation": "клей; клеить", "part_of_speech": "noun/verb", "example": "Glue the pieces together.", "example_ru": "Склей кусочки вместе."},
        {"word": "pot", "transcription": "/pɒt/", "translation": "горшок, кастрюля", "part_of_speech": "noun", "example": "Cook rice in a pot.", "example_ru": "Вари рис в кастрюле."},
        {"word": "globe", "transcription": "/ɡləʊb/", "translation": "глобус; земной шар", "part_of_speech": "noun", "example": "Find Russia on the globe.", "example_ru": "Найди Россию на глобусе."},
        {"word": "page", "transcription": "/peɪdʒ/", "translation": "страница", "part_of_speech": "noun", "example": "Open the book to page ten.", "example_ru": "Открой книгу на десятой странице."},
        {"word": "sentence", "transcription": "/ˈsentəns/", "translation": "предложение (грам.)", "part_of_speech": "noun", "example": "Write a sentence.", "example_ru": "Напиши предложение."},
        {"word": "bench", "transcription": "/bentʃ/", "translation": "скамейка", "part_of_speech": "noun", "example": "Sit on the bench.", "example_ru": "Сядь на скамейку."},
        {"word": "jump", "transcription": "/dʒʌmp/", "translation": "прыгать", "part_of_speech": "verb", "example": "The frog can jump high.", "example_ru": "Лягушка умеет высоко прыгать."},
        {"word": "climb", "transcription": "/klaɪm/", "translation": "лазать, карабкаться", "part_of_speech": "verb", "example": "He climbed up the tree.", "example_ru": "Он залез на дерево."},
        {"word": "fly", "transcription": "/flaɪ/", "translation": "летать", "part_of_speech": "verb", "example": "Birds fly in the sky.", "example_ru": "Птицы летают в небе."},
        {"word": "fall", "transcription": "/fɔːl/", "translation": "падать", "part_of_speech": "verb", "example": "Don't fall off the bike.", "example_ru": "Не упади с велосипеда."},
        {"word": "hit", "transcription": "/hɪt/", "translation": "ударять, бить", "part_of_speech": "verb", "example": "He hit the ball hard.", "example_ru": "Он сильно ударил по мячу."},
        {"word": "throw", "transcription": "/θrəʊ/", "translation": "бросать", "part_of_speech": "verb", "example": "Throw the ball to me.", "example_ru": "Брось мне мяч."},
        {"word": "catch", "transcription": "/kætʃ/", "translation": "ловить", "part_of_speech": "verb", "example": "Catch the ball!", "example_ru": "Поймай мяч!"},
        {"word": "kick", "transcription": "/kɪk/", "translation": "пинать, ударять ногой", "part_of_speech": "verb", "example": "Kick the ball into the goal.", "example_ru": "Ударь мяч в ворота."},
        {"word": "count", "transcription": "/kaʊnt/", "translation": "считать, подсчитывать", "part_of_speech": "verb", "example": "Count from one to ten.", "example_ru": "Считай от одного до десяти."},
        {"word": "point", "transcription": "/pɔɪnt/", "translation": "указывать; точка", "part_of_speech": "verb/noun", "example": "Point to the correct answer.", "example_ru": "Укажи на правильный ответ."},
        {"word": "smile", "transcription": "/smaɪl/", "translation": "улыбаться; улыбка", "part_of_speech": "verb/noun", "example": "She always smiles.", "example_ru": "Она всегда улыбается."},
        {"word": "laugh", "transcription": "/lɑːf/", "translation": "смеяться", "part_of_speech": "verb", "example": "We all laugh at the joke.", "example_ru": "Мы все смеёмся над шуткой."},
        {"word": "cry", "transcription": "/kraɪ/", "translation": "плакать", "part_of_speech": "verb", "example": "The baby is crying.", "example_ru": "Малыш плачет."},
        {"word": "shout", "transcription": "/ʃaʊt/", "translation": "кричать", "part_of_speech": "verb", "example": "Don't shout in class.", "example_ru": "Не кричи на уроке."},
        {"word": "whisper", "transcription": "/ˈwɪspər/", "translation": "шептать; шёпот", "part_of_speech": "verb/noun", "example": "She whispered the answer.", "example_ru": "Она прошептала ответ."},
        {"word": "hug", "transcription": "/hʌɡ/", "translation": "обнимать; объятие", "part_of_speech": "verb/noun", "example": "She gave me a big hug.", "example_ru": "Она крепко меня обняла."},
        {"word": "wake up", "transcription": "/weɪk ʌp/", "translation": "просыпаться", "part_of_speech": "verb", "example": "I wake up at seven.", "example_ru": "Я просыпаюсь в семь."},
        {"word": "get dressed", "transcription": "/ɡet drest/", "translation": "одеваться", "part_of_speech": "verb", "example": "Get dressed quickly!", "example_ru": "Одевайся быстро!"},
        {"word": "brush", "transcription": "/brʌʃ/", "translation": "чистить щёткой; щётка", "part_of_speech": "verb/noun", "example": "Brush your teeth.", "example_ru": "Почисти зубы."},
        {"word": "cross", "transcription": "/krɒs/", "translation": "пересекать; злой", "part_of_speech": "verb/adjective", "example": "Cross the road carefully.", "example_ru": "Переходи дорогу осторожно."},
        {"word": "wait", "transcription": "/weɪt/", "translation": "ждать", "part_of_speech": "verb", "example": "Wait here for me.", "example_ru": "Жди меня здесь."},
        {"word": "lift", "transcription": "/lɪft/", "translation": "поднимать; лифт", "part_of_speech": "verb/noun", "example": "Lift the box carefully.", "example_ru": "Подними коробку осторожно."},
        {"word": "drop", "transcription": "/drɒp/", "translation": "ронять; капля", "part_of_speech": "verb/noun", "example": "Don't drop the glass.", "example_ru": "Не урони стакан."},
        {"word": "mix", "transcription": "/mɪks/", "translation": "смешивать", "part_of_speech": "verb", "example": "Mix the flour and sugar.", "example_ru": "Смешай муку и сахар."},
        {"word": "break", "transcription": "/breɪk/", "translation": "ломать; перерыв", "part_of_speech": "verb/noun", "example": "Don't break the window.", "example_ru": "Не ломай окно."},
        {"word": "fix", "transcription": "/fɪks/", "translation": "чинить, исправлять", "part_of_speech": "verb", "example": "Can you fix my bike?", "example_ru": "Ты можешь починить мой велосипед?"},
        {"word": "build", "transcription": "/bɪld/", "translation": "строить", "part_of_speech": "verb", "example": "They build a sandcastle.", "example_ru": "Они строят замок из песка."},
        {"word": "paint", "transcription": "/peɪnt/", "translation": "краска; красить", "part_of_speech": "noun/verb", "example": "Paint the wall white.", "example_ru": "Покрась стену в белый цвет."},
        {"word": "print", "transcription": "/prɪnt/", "translation": "печатать; распечатывать", "part_of_speech": "verb/noun", "example": "Print the document.", "example_ru": "Распечатай документ."},
        {"word": "bake", "transcription": "/beɪk/", "translation": "печь, выпекать", "part_of_speech": "verb", "example": "She bakes bread every Sunday.", "example_ru": "Она печёт хлеб каждое воскресенье."},
        {"word": "pour", "transcription": "/pɔːr/", "translation": "наливать", "part_of_speech": "verb", "example": "Pour the water into the glass.", "example_ru": "Налей воду в стакан."},
        {"word": "taste", "transcription": "/teɪst/", "translation": "пробовать на вкус; вкус", "part_of_speech": "verb/noun", "example": "Taste this soup.", "example_ru": "Попробуй этот суп."},
        {"word": "loud", "transcription": "/laʊd/", "translation": "громкий", "part_of_speech": "adjective", "example": "The music is too loud.", "example_ru": "Музыка слишком громкая."},
        {"word": "quiet", "transcription": "/ˈkwaɪət/", "translation": "тихий, бесшумный", "part_of_speech": "adjective", "example": "Please be quiet.", "example_ru": "Пожалуйста, помолчи."},
        {"word": "soft", "transcription": "/sɒft/", "translation": "мягкий", "part_of_speech": "adjective", "example": "The pillow is very soft.", "example_ru": "Подушка очень мягкая."},
        {"word": "stone", "transcription": "/stəʊn/", "translation": "камень", "part_of_speech": "noun", "example": "He threw a stone into the river.", "example_ru": "Он бросил камень в реку."},
        {"word": "heavy", "transcription": "/ˈhevi/", "translation": "тяжёлый", "part_of_speech": "adjective", "example": "This bag is very heavy.", "example_ru": "Эта сумка очень тяжёлая."},
        {"word": "round", "transcription": "/raʊnd/", "translation": "круглый", "part_of_speech": "adjective", "example": "The table is round.", "example_ru": "Стол круглый."},
        {"word": "flat", "transcription": "/flæt/", "translation": "плоский, ровный", "part_of_speech": "adjective", "example": "The road is flat.", "example_ru": "Дорога ровная."},
        {"word": "sharp", "transcription": "/ʃɑːrp/", "translation": "острый", "part_of_speech": "adjective", "example": "The knife is sharp.", "example_ru": "Нож острый."},
        {"word": "sweet", "transcription": "/swiːt/", "translation": "сладкий", "part_of_speech": "adjective", "example": "This cake is very sweet.", "example_ru": "Этот торт очень сладкий."},
        {"word": "sour", "transcription": "/saʊər/", "translation": "кислый", "part_of_speech": "adjective", "example": "The lemon is sour.", "example_ru": "Лимон кислый."},
        {"word": "salty", "transcription": "/ˈsɔːlti/", "translation": "солёный", "part_of_speech": "adjective", "example": "The soup is too salty.", "example_ru": "Суп слишком солёный."},
        {"word": "wet", "transcription": "/wet/", "translation": "мокрый, влажный", "part_of_speech": "adjective", "example": "My shoes are wet.", "example_ru": "Мои туфли мокрые."},
        {"word": "dry", "transcription": "/draɪ/", "translation": "сухой", "part_of_speech": "adjective", "example": "The clothes are dry now.", "example_ru": "Одежда теперь сухая."},
        {"word": "dark", "transcription": "/dɑːrk/", "translation": "тёмный", "part_of_speech": "adjective", "example": "It is dark outside.", "example_ru": "На улице темно."},
        {"word": "deep", "transcription": "/diːp/", "translation": "глубокий", "part_of_speech": "adjective", "example": "The lake is very deep.", "example_ru": "Озеро очень глубокое."},
        {"word": "wide", "transcription": "/waɪd/", "translation": "широкий", "part_of_speech": "adjective", "example": "The river is wide.", "example_ru": "Река широкая."},
        {"word": "narrow", "transcription": "/ˈnærəʊ/", "translation": "узкий", "part_of_speech": "adjective", "example": "The street is narrow.", "example_ru": "Улица узкая."},
        {"word": "sick", "transcription": "/sɪk/", "translation": "больной, плохо", "part_of_speech": "adjective", "example": "I feel sick today.", "example_ru": "Сегодня мне плохо."},
        {"word": "strong", "transcription": "/strɒŋ/", "translation": "сильный", "part_of_speech": "adjective", "example": "He is very strong.", "example_ru": "Он очень сильный."},
        {"word": "weak", "transcription": "/wiːk/", "translation": "слабый", "part_of_speech": "adjective", "example": "I feel weak after the illness.", "example_ru": "После болезни я чувствую себя слабым."},
        {"word": "neat", "transcription": "/niːt/", "translation": "аккуратный, чистый", "part_of_speech": "adjective", "example": "Keep your room neat.", "example_ru": "Держи комнату в порядке."},
        {"word": "messy", "transcription": "/ˈmesi/", "translation": "грязный, беспорядочный", "part_of_speech": "adjective", "example": "Your room is very messy.", "example_ru": "В твоей комнате очень беспорядок."},
        {"word": "noisy", "transcription": "/ˈnɔɪzi/", "translation": "шумный", "part_of_speech": "adjective", "example": "The street is noisy.", "example_ru": "Улица шумная."},
        {"word": "clever", "transcription": "/ˈklevər/", "translation": "умный, сообразительный", "part_of_speech": "adjective", "example": "She is a clever girl.", "example_ru": "Она умная девочка."},
        {"word": "brave", "transcription": "/breɪv/", "translation": "смелый, храбрый", "part_of_speech": "adjective", "example": "The firefighter is very brave.", "example_ru": "Пожарный очень смелый."},
        {"word": "shy", "transcription": "/ʃaɪ/", "translation": "застенчивый", "part_of_speech": "adjective", "example": "He is shy around new people.", "example_ru": "Он застенчив с новыми людьми."},
        {"word": "kind", "transcription": "/kaɪnd/", "translation": "добрый", "part_of_speech": "adjective", "example": "She is very kind to everyone.", "example_ru": "Она очень добра ко всем."},
        {"word": "lucky", "transcription": "/ˈlʌki/", "translation": "удачливый, счастливый", "part_of_speech": "adjective", "example": "You are very lucky!", "example_ru": "Тебе очень повезло!"},
        {"word": "favourite", "transcription": "/ˈfeɪvərɪt/", "translation": "любимый", "part_of_speech": "adjective", "example": "What is your favourite colour?", "example_ru": "Какой твой любимый цвет?"},
        {"word": "under", "transcription": "/ˈʌndər/", "translation": "под", "part_of_speech": "preposition", "example": "The cat is under the table.", "example_ru": "Кошка под столом."},
        {"word": "above", "transcription": "/əˈbʌv/", "translation": "над, выше", "part_of_speech": "preposition", "example": "The lamp is above the table.", "example_ru": "Лампа над столом."},
        {"word": "behind", "transcription": "/bɪˈhaɪnd/", "translation": "за, позади", "part_of_speech": "preposition", "example": "Stand behind me.", "example_ru": "Встань позади меня."},
        {"word": "between", "transcription": "/bɪˈtwiːn/", "translation": "между", "part_of_speech": "preposition", "example": "Sit between me and her.", "example_ru": "Сядь между мной и ней."},
        {"word": "inside", "transcription": "/ˌɪnˈsaɪd/", "translation": "внутри, внутрь", "part_of_speech": "preposition/adverb", "example": "Come inside, it is cold.", "example_ru": "Заходи внутрь, холодно."},
        {"word": "outside", "transcription": "/ˌaʊtˈsaɪd/", "translation": "снаружи, на улице", "part_of_speech": "preposition/adverb", "example": "Wait outside.", "example_ru": "Подожди снаружи."},
        {"word": "near", "transcription": "/nɪər/", "translation": "близко, рядом", "part_of_speech": "preposition/adverb", "example": "The school is near my house.", "example_ru": "Школа рядом с моим домом."},
        {"word": "far", "transcription": "/fɑːr/", "translation": "далеко", "part_of_speech": "adverb", "example": "The shop is not far.", "example_ru": "Магазин недалеко."},
        {"word": "left", "transcription": "/left/", "translation": "левый, налево", "part_of_speech": "adjective/adverb", "example": "Turn left at the corner.", "example_ru": "На углу поверни налево."},
        {"word": "spell", "transcription": "/spel/", "translation": "писать по буквам", "part_of_speech": "verb", "example": "How do you spell your name?", "example_ru": "Как пишется твоё имя?"},
        {"word": "straight", "transcription": "/streɪt/", "translation": "прямо, прямой", "part_of_speech": "adverb/adjective", "example": "Go straight ahead.", "example_ru": "Иди прямо."},
        {"word": "up", "transcription": "/ʌp/", "translation": "вверх, наверху", "part_of_speech": "adverb/preposition", "example": "Go up the stairs.", "example_ru": "Поднимись по лестнице."},
        {"word": "down", "transcription": "/daʊn/", "translation": "вниз, внизу", "part_of_speech": "adverb/preposition", "example": "Come down for dinner.", "example_ru": "Спустись на ужин."},
        {"word": "across", "transcription": "/əˈkrɒs/", "translation": "через, напротив", "part_of_speech": "preposition/adverb", "example": "Walk across the street.", "example_ru": "Перейди через улицу."},
        {"word": "along", "transcription": "/əˈlɒŋ/", "translation": "вдоль", "part_of_speech": "preposition/adverb", "example": "Walk along the river.", "example_ru": "Иди вдоль реки."},
        {"word": "about", "transcription": "/əˈbaʊt/", "translation": "о, около, примерно", "part_of_speech": "preposition/adverb", "example": "Tell me about your day.", "example_ru": "Расскажи мне о своём дне."},
        {"word": "with", "transcription": "/wɪð/", "translation": "с, вместе с", "part_of_speech": "preposition", "example": "I go to school with my friend.", "example_ru": "Я хожу в школу с другом."},
        {"word": "without", "transcription": "/wɪˈðaʊt/", "translation": "без", "part_of_speech": "preposition", "example": "Don't go without your hat.", "example_ru": "Не уходи без шапки."},
        {"word": "before", "transcription": "/bɪˈfɔːr/", "translation": "до, перед", "part_of_speech": "preposition/conjunction", "example": "Wash your hands before eating.", "example_ru": "Мой руки перед едой."},
        {"word": "after", "transcription": "/ˈɑːftər/", "translation": "после", "part_of_speech": "preposition/conjunction", "example": "Rest after school.", "example_ru": "Отдохни после школы."},
        {"word": "while", "transcription": "/waɪl/", "translation": "пока, в то время как", "part_of_speech": "conjunction", "example": "I listen while I cook.", "example_ru": "Я слушаю, пока готовлю."},
        {"word": "because", "transcription": "/bɪˈkɒz/", "translation": "потому что", "part_of_speech": "conjunction", "example": "I am happy because it is Friday.", "example_ru": "Я рад, потому что сегодня пятница."},
        {"word": "but", "transcription": "/bʌt/", "translation": "но, однако", "part_of_speech": "conjunction", "example": "I like coffee but not tea.", "example_ru": "Я люблю кофе, но не чай."},
        {"word": "and", "transcription": "/ænd/", "translation": "и", "part_of_speech": "conjunction", "example": "I have a cat and a dog.", "example_ru": "У меня есть кошка и собака."},
        {"word": "or", "transcription": "/ɔːr/", "translation": "или", "part_of_speech": "conjunction", "example": "Tea or coffee?", "example_ru": "Чай или кофе?"},
        {"word": "so", "transcription": "/səʊ/", "translation": "поэтому; так", "part_of_speech": "conjunction/adverb", "example": "It is late, so I go to bed.", "example_ru": "Уже поздно, поэтому я иду спать."},
        {"word": "if", "transcription": "/ɪf/", "translation": "если", "part_of_speech": "conjunction", "example": "If it rains, take an umbrella.", "example_ru": "Если идёт дождь, возьми зонт."},
        {"word": "when", "transcription": "/wen/", "translation": "когда", "part_of_speech": "conjunction", "example": "Call me when you arrive.", "example_ru": "Позвони мне, когда приедешь."},
        {"word": "how", "transcription": "/haʊ/", "translation": "как", "part_of_speech": "adverb", "example": "How are you?", "example_ru": "Как ты?"},
        {"word": "why", "transcription": "/waɪ/", "translation": "почему", "part_of_speech": "adverb", "example": "Why are you sad?", "example_ru": "Почему ты грустишь?"},
        {"word": "where", "transcription": "/weər/", "translation": "где, куда", "part_of_speech": "adverb", "example": "Where do you live?", "example_ru": "Где ты живёшь?"},
        {"word": "what", "transcription": "/wɒt/", "translation": "что, какой", "part_of_speech": "pronoun/determiner", "example": "What is your name?", "example_ru": "Как тебя зовут?"},
        {"word": "who", "transcription": "/huː/", "translation": "кто", "part_of_speech": "pronoun", "example": "Who is that?", "example_ru": "Кто это?"},
        {"word": "which", "transcription": "/wɪtʃ/", "translation": "который, какой", "part_of_speech": "pronoun/determiner", "example": "Which one do you prefer?", "example_ru": "Который из них ты предпочитаешь?"},
        {"word": "birthday", "transcription": "/ˈbɜːrθdeɪ/", "translation": "день рождения", "part_of_speech": "noun", "example": "Happy birthday!", "example_ru": "С днём рождения!"},
        {"word": "present", "transcription": "/ˈprezənt/", "translation": "подарок; настоящий", "part_of_speech": "noun/adjective", "example": "I got a nice present.", "example_ru": "Я получил красивый подарок."},
        {"word": "gift", "transcription": "/ɡɪft/", "translation": "подарок, дар", "part_of_speech": "noun", "example": "This gift is for you.", "example_ru": "Этот подарок для тебя."},
        {"word": "party", "transcription": "/ˈpɑːrti/", "translation": "вечеринка", "part_of_speech": "noun", "example": "I have a birthday party today.", "example_ru": "Сегодня у меня вечеринка на день рождения."},
        {"word": "candle", "transcription": "/ˈkændəl/", "translation": "свеча", "part_of_speech": "noun", "example": "Blow out the candle.", "example_ru": "Задуй свечу."},
        {"word": "prize", "transcription": "/praɪz/", "translation": "приз, награда", "part_of_speech": "noun", "example": "She won first prize.", "example_ru": "Она выиграла первый приз."},
        {"word": "money", "transcription": "/ˈmʌni/", "translation": "деньги", "part_of_speech": "noun", "example": "I saved my money.", "example_ru": "Я сэкономил свои деньги."},
        {"word": "price", "transcription": "/praɪs/", "translation": "цена", "part_of_speech": "noun", "example": "What is the price?", "example_ru": "Какова цена?"},
        {"word": "coin", "transcription": "/kɔɪn/", "translation": "монета", "part_of_speech": "noun", "example": "I found a coin on the floor.", "example_ru": "Я нашёл монету на полу."},
        {"word": "stamp", "transcription": "/stæmp/", "translation": "марка; штамп", "part_of_speech": "noun", "example": "Put a stamp on the envelope.", "example_ru": "Наклей марку на конверт."},
        {"word": "envelope", "transcription": "/ˈenvələʊp/", "translation": "конверт", "part_of_speech": "noun", "example": "Put the letter in an envelope.", "example_ru": "Положи письмо в конверт."},
        {"word": "message", "transcription": "/ˈmesɪdʒ/", "translation": "сообщение", "part_of_speech": "noun", "example": "I got your message.", "example_ru": "Я получил твоё сообщение."},
        {"word": "password", "transcription": "/ˈpɑːswɜːrd/", "translation": "пароль", "part_of_speech": "noun", "example": "Enter your password.", "example_ru": "Введи пароль."},
        {"word": "address", "transcription": "/əˈdres/", "translation": "адрес", "part_of_speech": "noun", "example": "Write your address here.", "example_ru": "Напиши свой адрес здесь."},
        {"word": "journey", "transcription": "/ˈdʒɜːrni/", "translation": "путешествие, поездка", "part_of_speech": "noun", "example": "The journey took three hours.", "example_ru": "Путешествие заняло три часа."},
        {"word": "trip", "transcription": "/trɪp/", "translation": "поездка, экскурсия", "part_of_speech": "noun", "example": "We planned a trip to the mountains.", "example_ru": "Мы запланировали поездку в горы."},
        {"word": "holiday", "transcription": "/ˈhɒlɪdeɪ/", "translation": "праздник; каникулы", "part_of_speech": "noun", "example": "We go to the sea on holiday.", "example_ru": "На каникулах мы едем к морю."},
        {"word": "weekend", "transcription": "/ˌwiːkˈend/", "translation": "выходные", "part_of_speech": "noun", "example": "I rest at the weekend.", "example_ru": "На выходных я отдыхаю."},
        {"word": "midnight", "transcription": "/ˈmɪdnaɪt/", "translation": "полночь", "part_of_speech": "noun", "example": "The party ends at midnight.", "example_ru": "Вечеринка заканчивается в полночь."},
        {"word": "noon", "transcription": "/nuːn/", "translation": "полдень", "part_of_speech": "noun", "example": "We eat lunch at noon.", "example_ru": "В полдень мы обедаем."},
        {"word": "cupboard", "transcription": "/ˈkʌbərd/", "translation": "шкаф, буфет", "part_of_speech": "noun", "example": "The cups are in the cupboard.", "example_ru": "Чашки в шкафу."},
        {"word": "sunflower", "transcription": "/ˈsʌnflaʊər/", "translation": "подсолнух", "part_of_speech": "noun", "example": "Sunflowers turn towards the sun.", "example_ru": "Подсолнухи поворачиваются к солнцу."},
        {"word": "plant", "transcription": "/plɑːnt/", "translation": "растение; сажать", "part_of_speech": "noun/verb", "example": "Water the plant every day.", "example_ru": "Поливай растение каждый день."},
        {"word": "pond", "transcription": "/pɒnd/", "translation": "пруд", "part_of_speech": "noun", "example": "Ducks swim in the pond.", "example_ru": "Утки плавают в пруду."},
        {"word": "net", "transcription": "/net/", "translation": "сеть, сетка", "part_of_speech": "noun", "example": "The ball went into the net.", "example_ru": "Мяч попал в сетку."},
        {"word": "line", "transcription": "/laɪn/", "translation": "линия, очередь", "part_of_speech": "noun", "example": "Draw a straight line.", "example_ru": "Нарисуй прямую линию."},
        {"word": "shape", "transcription": "/ʃeɪp/", "translation": "форма", "part_of_speech": "noun", "example": "What shape is this?", "example_ru": "Какая это форма?"},
        {"word": "circle", "transcription": "/ˈsɜːrkəl/", "translation": "круг", "part_of_speech": "noun", "example": "Draw a circle.", "example_ru": "Нарисуй круг."},
]