        # ---- ДОБАВЬ ЭТИ СЛОВА В СПИСОК "A1": [...] в файле bot.py ----
WORDS_A1 = [
        {"word": "apple", "transcription": "/ˈæpəl/", "translation": "яблоко", "part_of_speech": "noun", "example": "I eat an apple every day.", "example_ru": "Я ем яблоко каждый день."},
        {"word": "banana", "transcription": "/bəˈnɑːnə/", "translation": "банан", "part_of_speech": "noun", "example": "She likes bananas.", "example_ru": "Ей нравятся бананы."},
        {"word": "orange", "transcription": "/ˈɒrɪndʒ/", "translation": "апельсин; оранжевый", "part_of_speech": "noun/adjective", "example": "The orange is sweet.", "example_ru": "Апельсин сладкий."},
        {"word": "milk", "transcription": "/mɪlk/", "translation": "молоко", "part_of_speech": "noun", "example": "I drink milk every morning.", "example_ru": "Я пью молоко каждое утро."},
        {"word": "bread", "transcription": "/bred/", "translation": "хлеб", "part_of_speech": "noun", "example": "We need bread from the shop.", "example_ru": "Нам нужен хлеб из магазина."},
        {"word": "egg", "transcription": "/eɡ/", "translation": "яйцо", "part_of_speech": "noun", "example": "I have two eggs for breakfast.", "example_ru": "У меня два яйца на завтрак."},
        {"word": "tea", "transcription": "/tiː/", "translation": "чай", "part_of_speech": "noun", "example": "Would you like some tea?", "example_ru": "Хочешь чаю?"},
        {"word": "coffee", "transcription": "/ˈkɒfi/", "translation": "кофе", "part_of_speech": "noun", "example": "He drinks coffee in the morning.", "example_ru": "Он пьёт кофе по утрам."},
        {"word": "rice", "transcription": "/raɪs/", "translation": "рис", "part_of_speech": "noun", "example": "We eat rice for dinner.", "example_ru": "Мы едим рис на ужин."},
        {"word": "fish", "transcription": "/fɪʃ/", "translation": "рыба", "part_of_speech": "noun", "example": "I like fish and chips.", "example_ru": "Мне нравится рыба с картошкой."},
        {"word": "meat", "transcription": "/miːt/", "translation": "мясо", "part_of_speech": "noun", "example": "He eats meat every day.", "example_ru": "Он ест мясо каждый день."},
        {"word": "soup", "transcription": "/suːp/", "translation": "суп", "part_of_speech": "noun", "example": "The soup is very hot.", "example_ru": "Суп очень горячий."},
        {"word": "cake", "transcription": "/keɪk/", "translation": "торт, пирог", "part_of_speech": "noun", "example": "She made a birthday cake.", "example_ru": "Она испекла торт на день рождения."},
        {"word": "sugar", "transcription": "/ˈʃʊɡər/", "translation": "сахар", "part_of_speech": "noun", "example": "Do you want sugar in your tea?", "example_ru": "Тебе сахар в чай?"},
        {"word": "salt", "transcription": "/sɔːlt/", "translation": "соль", "part_of_speech": "noun", "example": "Pass me the salt, please.", "example_ru": "Передай мне соль, пожалуйста."},
        {"word": "butter", "transcription": "/ˈbʌtər/", "translation": "масло (сливочное)", "part_of_speech": "noun", "example": "I put butter on my bread.", "example_ru": "Я намазываю масло на хлеб."},
        {"word": "cheese", "transcription": "/tʃiːz/", "translation": "сыр", "part_of_speech": "noun", "example": "I love cheese pizza.", "example_ru": "Я люблю пиццу с сыром."},
        {"word": "chicken", "transcription": "/ˈtʃɪkɪn/", "translation": "курица; цыплёнок", "part_of_speech": "noun", "example": "We had chicken for lunch.", "example_ru": "На обед у нас была курица."},
        {"word": "potato", "transcription": "/pəˈteɪtəʊ/", "translation": "картофель", "part_of_speech": "noun", "example": "I like fried potatoes.", "example_ru": "Мне нравится жареная картошка."},
        {"word": "tomato", "transcription": "/təˈmɑːtəʊ/", "translation": "помидор", "part_of_speech": "noun", "example": "This tomato is red and juicy.", "example_ru": "Этот помидор красный и сочный."},
        {"word": "mother", "transcription": "/ˈmʌðər/", "translation": "мать, мама", "part_of_speech": "noun", "example": "My mother is a teacher.", "example_ru": "Моя мама — учитель."},
        {"word": "father", "transcription": "/ˈfɑːðər/", "translation": "отец, папа", "part_of_speech": "noun", "example": "My father works in a bank.", "example_ru": "Мой папа работает в банке."},
        {"word": "brother", "transcription": "/ˈbrʌðər/", "translation": "брат", "part_of_speech": "noun", "example": "I have one brother.", "example_ru": "У меня есть один брат."},
        {"word": "sister", "transcription": "/ˈsɪstər/", "translation": "сестра", "part_of_speech": "noun", "example": "My sister is ten years old.", "example_ru": "Моей сестре десять лет."},
        {"word": "baby", "transcription": "/ˈbeɪbi/", "translation": "малыш, младенец", "part_of_speech": "noun", "example": "The baby is sleeping.", "example_ru": "Малыш спит."},
        {"word": "child", "transcription": "/tʃaɪld/", "translation": "ребёнок", "part_of_speech": "noun", "example": "Every child loves toys.", "example_ru": "Каждый ребёнок любит игрушки."},
        {"word": "family", "transcription": "/ˈfæməli/", "translation": "семья", "part_of_speech": "noun", "example": "My family is big.", "example_ru": "Моя семья большая."},
        {"word": "boy", "transcription": "/bɔɪ/", "translation": "мальчик", "part_of_speech": "noun", "example": "The boy is playing football.", "example_ru": "Мальчик играет в футбол."},
        {"word": "girl", "transcription": "/ɡɜːrl/", "translation": "девочка, девушка", "part_of_speech": "noun", "example": "The girl has long hair.", "example_ru": "У девочки длинные волосы."},
        {"word": "people", "transcription": "/ˈpiːpəl/", "translation": "люди", "part_of_speech": "noun", "example": "Many people live in this city.", "example_ru": "В этом городе живёт много людей."},
        {"word": "bed", "transcription": "/bed/", "translation": "кровать", "part_of_speech": "noun", "example": "I go to bed at ten.", "example_ru": "Я ложусь спать в десять."},
        {"word": "chair", "transcription": "/tʃeər/", "translation": "стул", "part_of_speech": "noun", "example": "Please sit on the chair.", "example_ru": "Пожалуйста, сядь на стул."},
        {"word": "table", "transcription": "/ˈteɪbəl/", "translation": "стол", "part_of_speech": "noun", "example": "The book is on the table.", "example_ru": "Книга на столе."},
        {"word": "door", "transcription": "/dɔːr/", "translation": "дверь", "part_of_speech": "noun", "example": "Please close the door.", "example_ru": "Пожалуйста, закрой дверь."},
        {"word": "window", "transcription": "/ˈwɪndəʊ/", "translation": "окно", "part_of_speech": "noun", "example": "Open the window, please.", "example_ru": "Открой окно, пожалуйста."},
        {"word": "floor", "transcription": "/flɔːr/", "translation": "пол; этаж", "part_of_speech": "noun", "example": "The cat is on the floor.", "example_ru": "Кошка на полу."},
        {"word": "wall", "transcription": "/wɔːl/", "translation": "стена", "part_of_speech": "noun", "example": "There is a picture on the wall.", "example_ru": "На стене висит картина."},
        {"word": "room", "transcription": "/ruːm/", "translation": "комната", "part_of_speech": "noun", "example": "My room is small but cosy.", "example_ru": "Моя комната маленькая, но уютная."},
        {"word": "kitchen", "transcription": "/ˈkɪtʃɪn/", "translation": "кухня", "part_of_speech": "noun", "example": "Mum is in the kitchen.", "example_ru": "Мама на кухне."},
        {"word": "bathroom", "transcription": "/ˈbɑːθruːm/", "translation": "ванная комната", "part_of_speech": "noun", "example": "The bathroom is upstairs.", "example_ru": "Ванная наверху."},
        {"word": "garden", "transcription": "/ˈɡɑːrdən/", "translation": "сад, огород", "part_of_speech": "noun", "example": "We grow flowers in the garden.", "example_ru": "Мы выращиваем цветы в саду."},
        {"word": "key", "transcription": "/kiː/", "translation": "ключ", "part_of_speech": "noun", "example": "I lost my key.", "example_ru": "Я потерял ключ."},
        {"word": "lamp", "transcription": "/læmp/", "translation": "лампа", "part_of_speech": "noun", "example": "Turn on the lamp, please.", "example_ru": "Включи лампу, пожалуйста."},
        {"word": "bag", "transcription": "/bæɡ/", "translation": "сумка, пакет", "part_of_speech": "noun", "example": "She has a big red bag.", "example_ru": "У неё большая красная сумка."},
        {"word": "box", "transcription": "/bɒks/", "translation": "коробка, ящик", "part_of_speech": "noun", "example": "Put it in the box.", "example_ru": "Положи это в коробку."},
        {"word": "shirt", "transcription": "/ʃɜːrt/", "translation": "рубашка", "part_of_speech": "noun", "example": "He wears a white shirt.", "example_ru": "Он носит белую рубашку."},
        {"word": "dress", "transcription": "/dres/", "translation": "платье", "part_of_speech": "noun", "example": "She has a beautiful dress.", "example_ru": "У неё красивое платье."},
        {"word": "shoes", "transcription": "/ʃuːz/", "translation": "туфли, обувь", "part_of_speech": "noun", "example": "These shoes are too small.", "example_ru": "Эта обувь слишком маленькая."},
        {"word": "hat", "transcription": "/hæt/", "translation": "шляпа, шапка", "part_of_speech": "noun", "example": "Put on your hat, it is cold.", "example_ru": "Надень шапку, холодно."},
        {"word": "coat", "transcription": "/kəʊt/", "translation": "пальто", "part_of_speech": "noun", "example": "I need a warm coat.", "example_ru": "Мне нужно тёплое пальто."},
        {"word": "trousers", "transcription": "/ˈtraʊzərz/", "translation": "брюки, штаны", "part_of_speech": "noun", "example": "He wears black trousers.", "example_ru": "Он носит чёрные брюки."},
        {"word": "glasses", "transcription": "/ˈɡlɑːsɪz/", "translation": "очки", "part_of_speech": "noun", "example": "She wears glasses to read.", "example_ru": "Она носит очки для чтения."},
        {"word": "watch", "transcription": "/wɒtʃ/", "translation": "часы (наручные); смотреть", "part_of_speech": "noun/verb", "example": "I got a new watch.", "example_ru": "Мне купили новые часы."},
        {"word": "bus", "transcription": "/bʌs/", "translation": "автобус", "part_of_speech": "noun", "example": "I take the bus to school.", "example_ru": "Я езжу в школу на автобусе."},
        {"word": "train", "transcription": "/treɪn/", "translation": "поезд", "part_of_speech": "noun", "example": "The train is fast.", "example_ru": "Поезд быстрый."},
        {"word": "plane", "transcription": "/pleɪn/", "translation": "самолёт", "part_of_speech": "noun", "example": "We go by plane.", "example_ru": "Мы летим на самолёте."},
        {"word": "bike", "transcription": "/baɪk/", "translation": "велосипед", "part_of_speech": "noun", "example": "I ride my bike every weekend.", "example_ru": "Я катаюсь на велосипеде каждые выходные."},
        {"word": "taxi", "transcription": "/ˈtæksi/", "translation": "такси", "part_of_speech": "noun", "example": "Let's take a taxi.", "example_ru": "Давай возьмём такси."},
        {"word": "road", "transcription": "/rəʊd/", "translation": "дорога", "part_of_speech": "noun", "example": "The road is long.", "example_ru": "Дорога длинная."},
        {"word": "street", "transcription": "/striːt/", "translation": "улица", "part_of_speech": "noun", "example": "I live on this street.", "example_ru": "Я живу на этой улице."},
        {"word": "city", "transcription": "/ˈsɪti/", "translation": "город (большой)", "part_of_speech": "noun", "example": "London is a big city.", "example_ru": "Лондон — большой город."},
        {"word": "town", "transcription": "/taʊn/", "translation": "город (маленький), посёлок", "part_of_speech": "noun", "example": "I live in a small town.", "example_ru": "Я живу в маленьком городе."},
        {"word": "shop", "transcription": "/ʃɒp/", "translation": "магазин", "part_of_speech": "noun", "example": "Let's go to the shop.", "example_ru": "Давай зайдём в магазин."},
        {"word": "park", "transcription": "/pɑːrk/", "translation": "парк", "part_of_speech": "noun", "example": "Children play in the park.", "example_ru": "Дети играют в парке."},
        {"word": "bank", "transcription": "/bæŋk/", "translation": "банк", "part_of_speech": "noun", "example": "The bank is on the main street.", "example_ru": "Банк находится на главной улице."},
        {"word": "hotel", "transcription": "/həʊˈtel/", "translation": "отель, гостиница", "part_of_speech": "noun", "example": "We stay at a nice hotel.", "example_ru": "Мы остановились в хорошем отеле."},
        {"word": "airport", "transcription": "/ˈeərpɔːrt/", "translation": "аэропорт", "part_of_speech": "noun", "example": "The airport is very big.", "example_ru": "Аэропорт очень большой."},
        {"word": "phone", "transcription": "/fəʊn/", "translation": "телефон", "part_of_speech": "noun", "example": "My phone is out of battery.", "example_ru": "У моего телефона сел аккумулятор."},
        {"word": "computer", "transcription": "/kəmˈpjuːtər/", "translation": "компьютер", "part_of_speech": "noun", "example": "I work on a computer.", "example_ru": "Я работаю за компьютером."},
        {"word": "television", "transcription": "/ˈtelɪvɪʒən/", "translation": "телевизор", "part_of_speech": "noun", "example": "We watch television in the evening.", "example_ru": "Мы смотрим телевизор вечером."},
        {"word": "radio", "transcription": "/ˈreɪdiəʊ/", "translation": "радио", "part_of_speech": "noun", "example": "I listen to the radio.", "example_ru": "Я слушаю радио."},
        {"word": "camera", "transcription": "/ˈkæmərə/", "translation": "фотоаппарат, камера", "part_of_speech": "noun", "example": "She takes photos with her camera.", "example_ru": "Она фотографирует своим фотоаппаратом."},
        {"word": "music", "transcription": "/ˈmjuːzɪk/", "translation": "музыка", "part_of_speech": "noun", "example": "I love listening to music.", "example_ru": "Я люблю слушать музыку."},
        {"word": "film", "transcription": "/fɪlm/", "translation": "фильм", "part_of_speech": "noun", "example": "Let's watch a film tonight.", "example_ru": "Давай посмотрим фильм сегодня вечером."},
        {"word": "game", "transcription": "/ɡeɪm/", "translation": "игра", "part_of_speech": "noun", "example": "We play a board game.", "example_ru": "Мы играем в настольную игру."},
        {"word": "sport", "transcription": "/spɔːrt/", "translation": "спорт", "part_of_speech": "noun", "example": "Sport is good for health.", "example_ru": "Спорт полезен для здоровья."},
        {"word": "ball", "transcription": "/bɔːl/", "translation": "мяч, шар", "part_of_speech": "noun", "example": "Kick the ball!", "example_ru": "Ударь по мячу!"},
        {"word": "red", "transcription": "/red/", "translation": "красный", "part_of_speech": "adjective", "example": "She has a red dress.", "example_ru": "У неё красное платье."},
        {"word": "blue", "transcription": "/bluː/", "translation": "синий, голубой", "part_of_speech": "adjective", "example": "The sky is blue.", "example_ru": "Небо голубое."},
        {"word": "green", "transcription": "/ɡriːn/", "translation": "зелёный", "part_of_speech": "adjective", "example": "The grass is green.", "example_ru": "Трава зелёная."},
        {"word": "yellow", "transcription": "/ˈjeləʊ/", "translation": "жёлтый", "part_of_speech": "adjective", "example": "Bananas are yellow.", "example_ru": "Бананы жёлтые."},
        {"word": "black", "transcription": "/blæk/", "translation": "чёрный", "part_of_speech": "adjective", "example": "He has a black cat.", "example_ru": "У него чёрная кошка."},
        {"word": "white", "transcription": "/waɪt/", "translation": "белый", "part_of_speech": "adjective", "example": "Snow is white.", "example_ru": "Снег белый."},
        {"word": "pink", "transcription": "/pɪŋk/", "translation": "розовый", "part_of_speech": "adjective", "example": "She likes pink flowers.", "example_ru": "Ей нравятся розовые цветы."},
        {"word": "brown", "transcription": "/braʊn/", "translation": "коричневый", "part_of_speech": "adjective", "example": "He has brown eyes.", "example_ru": "У него карие глаза."},
        {"word": "hot", "transcription": "/hɒt/", "translation": "горячий, жаркий", "part_of_speech": "adjective", "example": "It is hot today.", "example_ru": "Сегодня жарко."},
        {"word": "cold", "transcription": "/kəʊld/", "translation": "холодный, холод", "part_of_speech": "adjective", "example": "The water is cold.", "example_ru": "Вода холодная."},
        {"word": "warm", "transcription": "/wɔːrm/", "translation": "тёплый", "part_of_speech": "adjective", "example": "It is warm in spring.", "example_ru": "Весной тепло."},
        {"word": "fast", "transcription": "/fɑːst/", "translation": "быстрый, быстро", "part_of_speech": "adjective/adverb", "example": "He is a fast runner.", "example_ru": "Он быстрый бегун."},
        {"word": "slow", "transcription": "/sləʊ/", "translation": "медленный, медленно", "part_of_speech": "adjective/adverb", "example": "The turtle is slow.", "example_ru": "Черепаха медленная."},
        {"word": "tall", "transcription": "/tɔːl/", "translation": "высокий", "part_of_speech": "adjective", "example": "My brother is very tall.", "example_ru": "Мой брат очень высокий."},
        {"word": "short", "transcription": "/ʃɔːrt/", "translation": "короткий; низкого роста", "part_of_speech": "adjective", "example": "She has short hair.", "example_ru": "У неё короткие волосы."},
        {"word": "long", "transcription": "/lɒŋ/", "translation": "длинный, долгий", "part_of_speech": "adjective", "example": "It is a long road.", "example_ru": "Это длинная дорога."},
        {"word": "fat", "transcription": "/fæt/", "translation": "толстый", "part_of_speech": "adjective", "example": "The cat is fat.", "example_ru": "Кошка толстая."},
        {"word": "thin", "transcription": "/θɪn/", "translation": "тонкий, худой", "part_of_speech": "adjective", "example": "This book is thin.", "example_ru": "Эта книга тонкая."},
        {"word": "beautiful", "transcription": "/ˈbjuːtɪfəl/", "translation": "красивый", "part_of_speech": "adjective", "example": "What a beautiful flower!", "example_ru": "Какой красивый цветок!"},
        {"word": "ugly", "transcription": "/ˈʌɡli/", "translation": "некрасивый, уродливый", "part_of_speech": "adjective", "example": "That is an ugly building.", "example_ru": "Это некрасивое здание."},
        {"word": "young", "transcription": "/jʌŋ/", "translation": "молодой", "part_of_speech": "adjective", "example": "She is young and smart.", "example_ru": "Она молодая и умная."},
        {"word": "tired", "transcription": "/ˈtaɪərd/", "translation": "усталый", "part_of_speech": "adjective", "example": "I am very tired today.", "example_ru": "Я сегодня очень устал."},
        {"word": "hungry", "transcription": "/ˈhʌŋɡri/", "translation": "голодный", "part_of_speech": "adjective", "example": "I am hungry, let's eat.", "example_ru": "Я голоден, давай поедим."},
        {"word": "thirsty", "transcription": "/ˈθɜːrsti/", "translation": "жаждущий, хочу пить", "part_of_speech": "adjective", "example": "I am thirsty, give me water.", "example_ru": "Я хочу пить, дай мне воды."},
        {"word": "sad", "transcription": "/sæd/", "translation": "грустный, печальный", "part_of_speech": "adjective", "example": "Why are you sad?", "example_ru": "Почему ты грустишь?"},
        {"word": "funny", "transcription": "/ˈfʌni/", "translation": "смешной, забавный", "part_of_speech": "adjective", "example": "That joke is very funny.", "example_ru": "Эта шутка очень смешная."},
        {"word": "easy", "transcription": "/ˈiːzi/", "translation": "лёгкий, простой", "part_of_speech": "adjective", "example": "This exercise is easy.", "example_ru": "Это упражнение лёгкое."},
        {"word": "hard", "transcription": "/hɑːrd/", "translation": "твёрдый; трудный", "part_of_speech": "adjective", "example": "This test is hard.", "example_ru": "Этот тест трудный."},
        {"word": "right", "transcription": "/raɪt/", "translation": "правильный; правый", "part_of_speech": "adjective", "example": "That is the right answer.", "example_ru": "Это правильный ответ."},
        {"word": "wrong", "transcription": "/rɒŋ/", "translation": "неправильный", "part_of_speech": "adjective", "example": "Sorry, that is wrong.", "example_ru": "Извини, это неправильно."},
        {"word": "clean", "transcription": "/kliːn/", "translation": "чистый", "part_of_speech": "adjective", "example": "Your hands are clean.", "example_ru": "Твои руки чистые."},
        {"word": "dirty", "transcription": "/ˈdɜːrti/", "translation": "грязный", "part_of_speech": "adjective", "example": "My shoes are dirty.", "example_ru": "Мои ботинки грязные."},
        {"word": "full", "transcription": "/fʊl/", "translation": "полный, сытый", "part_of_speech": "adjective", "example": "The glass is full.", "example_ru": "Стакан полный."},
        {"word": "empty", "transcription": "/ˈempti/", "translation": "пустой", "part_of_speech": "adjective", "example": "The bottle is empty.", "example_ru": "Бутылка пустая."},
        {"word": "open", "transcription": "/ˈəʊpən/", "translation": "открытый; открывать", "part_of_speech": "adjective/verb", "example": "The shop is open.", "example_ru": "Магазин открыт."},
        {"word": "closed", "transcription": "/kləʊzd/", "translation": "закрытый", "part_of_speech": "adjective", "example": "The door is closed.", "example_ru": "Дверь закрыта."},
        {"word": "free", "transcription": "/friː/", "translation": "свободный; бесплатный", "part_of_speech": "adjective", "example": "Are you free this evening?", "example_ru": "Ты свободен сегодня вечером?"},
        {"word": "sure", "transcription": "/ʃʊər/", "translation": "уверенный, конечно", "part_of_speech": "adjective", "example": "Are you sure about that?", "example_ru": "Ты уверен в этом?"},
        {"word": "walk", "transcription": "/wɔːk/", "translation": "идти пешком, гулять", "part_of_speech": "verb", "example": "I walk to school.", "example_ru": "Я хожу в школу пешком."},
        {"word": "sleep", "transcription": "/sliːp/", "translation": "спать", "part_of_speech": "verb", "example": "I sleep eight hours a night.", "example_ru": "Я сплю восемь часов ночью."},
        {"word": "drink", "transcription": "/drɪŋk/", "translation": "пить", "part_of_speech": "verb", "example": "Drink more water.", "example_ru": "Пей больше воды."},
        {"word": "read", "transcription": "/riːd/", "translation": "читать", "part_of_speech": "verb", "example": "I read every night.", "example_ru": "Я читаю каждый вечер."},
        {"word": "write", "transcription": "/raɪt/", "translation": "писать", "part_of_speech": "verb", "example": "Write your name here.", "example_ru": "Напиши своё имя здесь."},
        {"word": "speak", "transcription": "/spiːk/", "translation": "говорить, разговаривать", "part_of_speech": "verb", "example": "Do you speak English?", "example_ru": "Ты говоришь по-английски?"},
        {"word": "listen", "transcription": "/ˈlɪsən/", "translation": "слушать", "part_of_speech": "verb", "example": "Listen to the teacher.", "example_ru": "Слушай учителя."},
        {"word": "know", "transcription": "/nəʊ/", "translation": "знать", "part_of_speech": "verb", "example": "I know the answer.", "example_ru": "Я знаю ответ."},
        {"word": "think", "transcription": "/θɪŋk/", "translation": "думать", "part_of_speech": "verb", "example": "Think before you speak.", "example_ru": "Думай, прежде чем говорить."},
        {"word": "want", "transcription": "/wɒnt/", "translation": "хотеть", "part_of_speech": "verb", "example": "I want a cup of tea.", "example_ru": "Я хочу чашку чая."},
        {"word": "need", "transcription": "/niːd/", "translation": "нуждаться, нужно", "part_of_speech": "verb", "example": "I need your help.", "example_ru": "Мне нужна твоя помощь."},
        {"word": "have", "transcription": "/hæv/", "translation": "иметь, у меня есть", "part_of_speech": "verb", "example": "I have a sister.", "example_ru": "У меня есть сестра."},
        {"word": "give", "transcription": "/ɡɪv/", "translation": "давать", "part_of_speech": "verb", "example": "Give me the book.", "example_ru": "Дай мне книгу."},
        {"word": "take", "transcription": "/teɪk/", "translation": "брать, взять", "part_of_speech": "verb", "example": "Take your umbrella.", "example_ru": "Возьми зонт."},
        {"word": "come", "transcription": "/kʌm/", "translation": "приходить, приезжать", "part_of_speech": "verb", "example": "Come here, please.", "example_ru": "Иди сюда, пожалуйста."},
        {"word": "get", "transcription": "/ɡet/", "translation": "получать; становиться", "part_of_speech": "verb", "example": "I get up at seven.", "example_ru": "Я встаю в семь."},
        {"word": "make", "transcription": "/meɪk/", "translation": "делать, создавать", "part_of_speech": "verb", "example": "I make my bed every morning.", "example_ru": "Я застилаю кровать каждое утро."},
        {"word": "put", "transcription": "/pʊt/", "translation": "класть, ставить", "part_of_speech": "verb", "example": "Put the bag on the table.", "example_ru": "Положи сумку на стол."},
        {"word": "find", "transcription": "/faɪnd/", "translation": "находить", "part_of_speech": "verb", "example": "I can't find my keys.", "example_ru": "Я не могу найти ключи."},
        {"word": "help", "transcription": "/help/", "translation": "помогать; помощь", "part_of_speech": "verb/noun", "example": "Can you help me?", "example_ru": "Ты можешь мне помочь?"},
        {"word": "open", "transcription": "/ˈəʊpən/", "translation": "открывать", "part_of_speech": "verb", "example": "Open the window.", "example_ru": "Открой окно."},
        {"word": "close", "transcription": "/kləʊz/", "translation": "закрывать", "part_of_speech": "verb", "example": "Close the door.", "example_ru": "Закрой дверь."},
        {"word": "sit", "transcription": "/sɪt/", "translation": "сидеть, садиться", "part_of_speech": "verb", "example": "Sit down, please.", "example_ru": "Садитесь, пожалуйста."},
        {"word": "stand", "transcription": "/stænd/", "translation": "стоять", "part_of_speech": "verb", "example": "Stand up!", "example_ru": "Встань!"},
        {"word": "stop", "transcription": "/stɒp/", "translation": "останавливаться, прекращать", "part_of_speech": "verb", "example": "Stop talking!", "example_ru": "Прекрати разговаривать!"},
        {"word": "start", "transcription": "/stɑːrt/", "translation": "начинать", "part_of_speech": "verb", "example": "Let's start the lesson.", "example_ru": "Давайте начнём урок."},
        {"word": "play", "transcription": "/pleɪ/", "translation": "играть", "part_of_speech": "verb", "example": "Children love to play.", "example_ru": "Дети любят играть."},
        {"word": "swim", "transcription": "/swɪm/", "translation": "плавать", "part_of_speech": "verb", "example": "I swim every summer.", "example_ru": "Я плаваю каждое лето."},
        {"word": "draw", "transcription": "/drɔː/", "translation": "рисовать", "part_of_speech": "verb", "example": "She loves to draw.", "example_ru": "Она любит рисовать."},
        {"word": "sing", "transcription": "/sɪŋ/", "translation": "петь", "part_of_speech": "verb", "example": "He sings very well.", "example_ru": "Он очень хорошо поёт."},
        {"word": "dance", "transcription": "/dɑːns/", "translation": "танцевать; танец", "part_of_speech": "verb/noun", "example": "I love to dance.", "example_ru": "Я люблю танцевать."},
        {"word": "cook", "transcription": "/kʊk/", "translation": "готовить (еду)", "part_of_speech": "verb", "example": "My mum cooks very well.", "example_ru": "Моя мама очень хорошо готовит."},
        {"word": "buy", "transcription": "/baɪ/", "translation": "покупать", "part_of_speech": "verb", "example": "I buy bread every day.", "example_ru": "Я покупаю хлеб каждый день."},
        {"word": "pay", "transcription": "/peɪ/", "translation": "платить", "part_of_speech": "verb", "example": "I pay by card.", "example_ru": "Я плачу картой."},
        {"word": "call", "transcription": "/kɔːl/", "translation": "звонить; называть", "part_of_speech": "verb", "example": "Call me later.", "example_ru": "Позвони мне позже."},
        {"word": "ask", "transcription": "/ɑːsk/", "translation": "спрашивать, просить", "part_of_speech": "verb", "example": "Ask the teacher.", "example_ru": "Спроси учителя."},
        {"word": "tell", "transcription": "/tel/", "translation": "говорить, рассказывать", "part_of_speech": "verb", "example": "Tell me your name.", "example_ru": "Скажи мне своё имя."},
        {"word": "show", "transcription": "/ʃəʊ/", "translation": "показывать", "part_of_speech": "verb", "example": "Show me your homework.", "example_ru": "Покажи мне домашнюю работу."},
        {"word": "love", "transcription": "/lʌv/", "translation": "любить; любовь", "part_of_speech": "verb/noun", "example": "I love my family.", "example_ru": "Я люблю свою семью."},
        {"word": "hate", "transcription": "/heɪt/", "translation": "ненавидеть", "part_of_speech": "verb", "example": "I hate cold weather.", "example_ru": "Я ненавижу холодную погоду."},
        {"word": "try", "transcription": "/traɪ/", "translation": "пробовать, стараться", "part_of_speech": "verb", "example": "Try this cake!", "example_ru": "Попробуй этот торт!"},
        {"word": "use", "transcription": "/juːz/", "translation": "использовать", "part_of_speech": "verb", "example": "Use a pencil.", "example_ru": "Используй карандаш."},
        {"word": "turn", "transcription": "/tɜːrn/", "translation": "поворачивать; очередь", "part_of_speech": "verb/noun", "example": "Turn left here.", "example_ru": "Повернись налево здесь."},
        {"word": "carry", "transcription": "/ˈkæri/", "translation": "нести, носить", "part_of_speech": "verb", "example": "Can you carry this bag?", "example_ru": "Ты можешь нести эту сумку?"},
        {"word": "cut", "transcription": "/kʌt/", "translation": "резать", "part_of_speech": "verb", "example": "Cut the bread.", "example_ru": "Нарежь хлеб."},
        {"word": "wash", "transcription": "/wɒʃ/", "translation": "мыть", "part_of_speech": "verb", "example": "Wash your hands.", "example_ru": "Помой руки."},
        {"word": "clean", "transcription": "/kliːn/", "translation": "убирать, чистить", "part_of_speech": "verb", "example": "Clean your room.", "example_ru": "Убери свою комнату."},
        {"word": "live", "transcription": "/lɪv/", "translation": "жить", "part_of_speech": "verb", "example": "Where do you live?", "example_ru": "Где ты живёшь?"},
        {"word": "study", "transcription": "/ˈstʌdi/", "translation": "учиться, изучать", "part_of_speech": "verb", "example": "I study English every day.", "example_ru": "Я изучаю английский каждый день."},
        {"word": "teach", "transcription": "/tiːtʃ/", "translation": "учить, преподавать", "part_of_speech": "verb", "example": "She teaches maths.", "example_ru": "Она преподаёт математику."},
        {"word": "learn", "transcription": "/lɜːrn/", "translation": "учиться, узнавать", "part_of_speech": "verb", "example": "I want to learn Spanish.", "example_ru": "Я хочу выучить испанский."},
        {"word": "morning", "transcription": "/ˈmɔːrnɪŋ/", "translation": "утро", "part_of_speech": "noun", "example": "Good morning!", "example_ru": "Доброе утро!"},
        {"word": "afternoon", "transcription": "/ˌɑːftərˈnuːn/", "translation": "полдень, вторая половина дня", "part_of_speech": "noun", "example": "See you this afternoon.", "example_ru": "Увидимся сегодня днём."},
        {"word": "evening", "transcription": "/ˈiːvnɪŋ/", "translation": "вечер", "part_of_speech": "noun", "example": "Good evening!", "example_ru": "Добрый вечер!"},
        {"word": "night", "transcription": "/naɪt/", "translation": "ночь", "part_of_speech": "noun", "example": "Good night!", "example_ru": "Спокойной ночи!"},
        {"word": "today", "transcription": "/təˈdeɪ/", "translation": "сегодня", "part_of_speech": "adverb", "example": "What day is today?", "example_ru": "Какой сегодня день?"},
        {"word": "tomorrow", "transcription": "/təˈmɒrəʊ/", "translation": "завтра", "part_of_speech": "adverb", "example": "See you tomorrow!", "example_ru": "Увидимся завтра!"},
        {"word": "yesterday", "transcription": "/ˈjestərdeɪ/", "translation": "вчера", "part_of_speech": "adverb", "example": "I was sick yesterday.", "example_ru": "Вчера я был болен."},
        {"word": "week", "transcription": "/wiːk/", "translation": "неделя", "part_of_speech": "noun", "example": "I work five days a week.", "example_ru": "Я работаю пять дней в неделю."},
        {"word": "month", "transcription": "/mʌnθ/", "translation": "месяц", "part_of_speech": "noun", "example": "There are twelve months in a year.", "example_ru": "В году двенадцать месяцев."},
        {"word": "hour", "transcription": "/aʊər/", "translation": "час", "part_of_speech": "noun", "example": "I wait for one hour.", "example_ru": "Я жду один час."},
        {"word": "minute", "transcription": "/ˈmɪnɪt/", "translation": "минута", "part_of_speech": "noun", "example": "Wait a minute!", "example_ru": "Подожди минуту!"},
        {"word": "now", "transcription": "/naʊ/", "translation": "сейчас, теперь", "part_of_speech": "adverb", "example": "Come here now.", "example_ru": "Иди сюда сейчас."},
        {"word": "always", "transcription": "/ˈɔːlweɪz/", "translation": "всегда", "part_of_speech": "adverb", "example": "She always smiles.", "example_ru": "Она всегда улыбается."},
        {"word": "never", "transcription": "/ˈnevər/", "translation": "никогда", "part_of_speech": "adverb", "example": "I never eat meat.", "example_ru": "Я никогда не ем мясо."},
        {"word": "sometimes", "transcription": "/ˈsʌmtaɪmz/", "translation": "иногда", "part_of_speech": "adverb", "example": "I sometimes cook dinner.", "example_ru": "Иногда я готовлю ужин."},
        {"word": "often", "transcription": "/ˈɒfən/", "translation": "часто", "part_of_speech": "adverb", "example": "I often go to the park.", "example_ru": "Я часто хожу в парк."},
        {"word": "again", "transcription": "/əˈɡen/", "translation": "снова, опять", "part_of_speech": "adverb", "example": "Say that again, please.", "example_ru": "Скажи это снова, пожалуйста."},
        {"word": "also", "transcription": "/ˈɔːlsəʊ/", "translation": "тоже, также", "part_of_speech": "adverb", "example": "I also like tea.", "example_ru": "Я тоже люблю чай."},
        {"word": "very", "transcription": "/ˈveri/", "translation": "очень", "part_of_speech": "adverb", "example": "I am very happy.", "example_ru": "Я очень счастлив."},
        {"word": "too", "transcription": "/tuː/", "translation": "слишком; тоже", "part_of_speech": "adverb", "example": "This soup is too hot.", "example_ru": "Этот суп слишком горячий."},
        {"word": "here", "transcription": "/hɪər/", "translation": "здесь, сюда", "part_of_speech": "adverb", "example": "Come here!", "example_ru": "Иди сюда!"},
        {"word": "there", "transcription": "/ðeər/", "translation": "там, туда", "part_of_speech": "adverb", "example": "Go there.", "example_ru": "Иди туда."},
        {"word": "maybe", "transcription": "/ˈmeɪbi/", "translation": "может быть", "part_of_speech": "adverb", "example": "Maybe I will come.", "example_ru": "Может быть, я приду."},
        {"word": "please", "transcription": "/pliːz/", "translation": "пожалуйста", "part_of_speech": "adverb", "example": "Can you help me, please?", "example_ru": "Ты можешь мне помочь, пожалуйста?"},
        {"word": "number", "transcription": "/ˈnʌmbər/", "translation": "число, номер", "part_of_speech": "noun", "example": "What is your phone number?", "example_ru": "Какой у тебя номер телефона?"},
        {"word": "name", "transcription": "/neɪm/", "translation": "имя, название", "part_of_speech": "noun", "example": "What is your name?", "example_ru": "Как тебя зовут?"},
        {"word": "word", "transcription": "/wɜːrd/", "translation": "слово", "part_of_speech": "noun", "example": "I learn ten words a day.", "example_ru": "Я учу десять слов в день."},
        {"word": "letter", "transcription": "/ˈletər/", "translation": "письмо; буква", "part_of_speech": "noun", "example": "I got a letter from my friend.", "example_ru": "Я получил письмо от друга."},
        {"word": "colour", "transcription": "/ˈkʌlər/", "translation": "цвет", "part_of_speech": "noun", "example": "What is your favourite colour?", "example_ru": "Какой твой любимый цвет?"},
        {"word": "photo", "transcription": "/ˈfəʊtəʊ/", "translation": "фотография", "part_of_speech": "noun", "example": "I took a photo.", "example_ru": "Я сделал фотографию."},
        {"word": "map", "transcription": "/mæp/", "translation": "карта", "part_of_speech": "noun", "example": "Look at the map.", "example_ru": "Посмотри на карту."},
        {"word": "pen", "transcription": "/pen/", "translation": "ручка", "part_of_speech": "noun", "example": "Give me a pen.", "example_ru": "Дай мне ручку."},
        {"word": "pencil", "transcription": "/ˈpensəl/", "translation": "карандаш", "part_of_speech": "noun", "example": "Draw with a pencil.", "example_ru": "Рисуй карандашом."},
        {"word": "paper", "transcription": "/ˈpeɪpər/", "translation": "бумага", "part_of_speech": "noun", "example": "Write it on paper.", "example_ru": "Напиши это на бумаге."},
        {"word": "umbrella", "transcription": "/ʌmˈbrelə/", "translation": "зонт", "part_of_speech": "noun", "example": "Take an umbrella, it will rain.", "example_ru": "Возьми зонт, будет дождь."},
        {"word": "rain", "transcription": "/reɪn/", "translation": "дождь; идти (о дожде)", "part_of_speech": "noun/verb", "example": "I love the rain.", "example_ru": "Я люблю дождь."},
        {"word": "snow", "transcription": "/snəʊ/", "translation": "снег; идти (о снеге)", "part_of_speech": "noun/verb", "example": "Children play in the snow.", "example_ru": "Дети играют в снегу."},
        {"word": "sky", "transcription": "/skaɪ/", "translation": "небо", "part_of_speech": "noun", "example": "The sky is clear today.", "example_ru": "Небо сегодня ясное."},
        {"word": "sea", "transcription": "/siː/", "translation": "море", "part_of_speech": "noun", "example": "We swim in the sea.", "example_ru": "Мы купаемся в море."},
        {"word": "river", "transcription": "/ˈrɪvər/", "translation": "река", "part_of_speech": "noun", "example": "The river is wide.", "example_ru": "Река широкая."},
        {"word": "mountain", "transcription": "/ˈmaʊntɪn/", "translation": "гора", "part_of_speech": "noun", "example": "The mountain is very high.", "example_ru": "Гора очень высокая."},
        {"word": "flower", "transcription": "/ˈflaʊər/", "translation": "цветок", "part_of_speech": "noun", "example": "She gave me a flower.", "example_ru": "Она подарила мне цветок."},
        {"word": "bird", "transcription": "/bɜːrd/", "translation": "птица", "part_of_speech": "noun", "example": "A bird is singing.", "example_ru": "Птица поёт."},
        {"word": "horse", "transcription": "/hɔːrs/", "translation": "лошадь", "part_of_speech": "noun", "example": "She rides a horse.", "example_ru": "Она ездит на лошади."},
        {"word": "cow", "transcription": "/kaʊ/", "translation": "корова", "part_of_speech": "noun", "example": "The cow gives milk.", "example_ru": "Корова даёт молоко."},
        {"word": "pig", "transcription": "/pɪɡ/", "translation": "свинья", "part_of_speech": "noun", "example": "There is a pig on the farm.", "example_ru": "На ферме есть свинья."},
        {"word": "rabbit", "transcription": "/ˈræbɪt/", "translation": "кролик", "part_of_speech": "noun", "example": "My rabbit is white.", "example_ru": "Мой кролик белый."},
        {"word": "lion", "transcription": "/ˈlaɪən/", "translation": "лев", "part_of_speech": "noun", "example": "The lion is the king of animals.", "example_ru": "Лев — царь зверей."},
        {"word": "elephant", "transcription": "/ˈelɪfənt/", "translation": "слон", "part_of_speech": "noun", "example": "Elephants are very big.", "example_ru": "Слоны очень большие."},
        {"word": "bear", "transcription": "/beər/", "translation": "медведь", "part_of_speech": "noun", "example": "The bear lives in the forest.", "example_ru": "Медведь живёт в лесу."},
        {"word": "monkey", "transcription": "/ˈmʌŋki/", "translation": "обезьяна", "part_of_speech": "noun", "example": "The monkey climbs the tree.", "example_ru": "Обезьяна лезет на дерево."},
        {"word": "fish", "transcription": "/fɪʃ/", "translation": "рыба", "part_of_speech": "noun", "example": "I have five fish in my tank.", "example_ru": "В моём аквариуме пять рыбок."},
        {"word": "forest", "transcription": "/ˈfɒrɪst/", "translation": "лес", "part_of_speech": "noun", "example": "We walk in the forest.", "example_ru": "Мы гуляем в лесу."},
        {"word": "island", "transcription": "/ˈaɪlənd/", "translation": "остров", "part_of_speech": "noun", "example": "They live on a small island.", "example_ru": "Они живут на маленьком острове."},
        {"word": "world", "transcription": "/wɜːrld/", "translation": "мир, свет", "part_of_speech": "noun", "example": "I want to see the world.", "example_ru": "Я хочу увидеть мир."},
        {"word": "country", "transcription": "/ˈkʌntri/", "translation": "страна", "part_of_speech": "noun", "example": "What country are you from?", "example_ru": "Из какой ты страны?"},
        {"word": "language", "transcription": "/ˈlæŋɡwɪdʒ/", "translation": "язык (речь)", "part_of_speech": "noun", "example": "English is a world language.", "example_ru": "Английский — мировой язык."},
        {"word": "hello", "transcription": "/həˈləʊ/", "translation": "привет, здравствуй", "part_of_speech": "exclamation", "example": "Hello! How are you?", "example_ru": "Привет! Как дела?"},
        {"word": "bye", "transcription": "/baɪ/", "translation": "пока, до свидания", "part_of_speech": "exclamation", "example": "Bye! See you tomorrow.", "example_ru": "Пока! Увидимся завтра."},
        {"word": "yes", "transcription": "/jes/", "translation": "да", "part_of_speech": "exclamation", "example": "Yes, I agree.", "example_ru": "Да, я согласен."},
        {"word": "no", "transcription": "/nəʊ/", "translation": "нет", "part_of_speech": "exclamation", "example": "No, thank you.", "example_ru": "Нет, спасибо."},
        {"word": "sorry", "transcription": "/ˈsɒri/", "translation": "извини, сожалею", "part_of_speech": "exclamation", "example": "Sorry, I am late.", "example_ru": "Извини, я опоздал."},
        {"word": "thanks", "transcription": "/θæŋks/", "translation": "спасибо", "part_of_speech": "exclamation", "example": "Thanks for your help!", "example_ru": "Спасибо за помощь!"},
        {"word": "okay", "transcription": "/ˌəʊˈkeɪ/", "translation": "хорошо, окей", "part_of_speech": "exclamation", "example": "Okay, let's go!", "example_ru": "Хорошо, пойдём!"},
        {"word": "great", "transcription": "/ɡreɪt/", "translation": "отличный, замечательный", "part_of_speech": "adjective", "example": "That is a great idea!", "example_ru": "Это отличная идея!"},
        {"word": "wow", "transcription": "/waʊ/", "translation": "вау, ого", "part_of_speech": "exclamation", "example": "Wow, that is amazing!", "example_ru": "Ого, это удивительно!"},
     ]