# Этот файл — шаблон. Слова для A2 уже есть в bot.py, просто перенеси их сюда по тому же принципу.

WORDS_A2 = [
    {"word": "travel", "transcription": "/ˈtrævəl/", "translation": "путешествовать; путешествие", "part_of_speech": "verb/noun", "example": "I love to travel.", "example_ru": "Я люблю путешествовать."},
    {"word": "weather", "transcription": "/ˈweðər/", "translation": "погода", "part_of_speech": "noun", "example": "The weather is cold today.", "example_ru": "Сегодня холодная погода."},
    {"word": "hospital", "transcription": "/ˈhɒspɪtl/", "translation": "больница", "part_of_speech": "noun", "example": "She works at the hospital.", "example_ru": "Она работает в больнице."},
    {"word": "angry", "transcription": "/ˈæŋɡri/", "translation": "злой, сердитый", "part_of_speech": "adjective", "example": "He was angry about the mistake.", "example_ru": "Он злился из-за ошибки."},
    {"word": "careful", "transcription": "/ˈkeərfəl/", "translation": "осторожный", "part_of_speech": "adjective", "example": "Be careful on the road.", "example_ru": "Будь осторожен на дороге."},
    {"word": "explain", "transcription": "/ɪkˈspleɪn/", "translation": "объяснять", "part_of_speech": "verb", "example": "Can you explain this word?", "example_ru": "Ты можешь объяснить это слово?"},
    {"word": "choose", "transcription": "/tʃuːz/", "translation": "выбирать", "part_of_speech": "verb", "example": "Choose your favourite colour.", "example_ru": "Выбери свой любимый цвет."},
    {"word": "dream", "transcription": "/driːm/", "translation": "мечта; мечтать", "part_of_speech": "noun/verb", "example": "I dream of visiting Paris.", "example_ru": "Я мечтаю посетить Париж."},
    {"word": "quiet", "transcription": "/ˈkwaɪət/", "translation": "тихий, спокойный", "part_of_speech": "adjective", "example": "The library is very quiet.", "example_ru": "В библиотеке очень тихо."},
    {"word": "busy", "transcription": "/ˈbɪzi/", "translation": "занятой", "part_of_speech": "adjective", "example": "I am busy at work today.", "example_ru": "Я сегодня занят на работе."},
    {"word": "forget", "transcription": "/fərˈɡet/", "translation": "забывать", "part_of_speech": "verb", "example": "Don't forget your keys!", "example_ru": "Не забудь свои ключи!"},
    {"word": "remember", "transcription": "/rɪˈmembər/", "translation": "помнить, вспоминать", "part_of_speech": "verb", "example": "I remember her name.", "example_ru": "Я помню её имя."},
    {"word": "enjoy", "transcription": "/ɪnˈdʒɔɪ/", "translation": "наслаждаться", "part_of_speech": "verb", "example": "I enjoy reading books.", "example_ru": "Я люблю читать книги."},
    {"word": "safe", "transcription": "/seɪf/", "translation": "безопасный", "part_of_speech": "adjective", "example": "This area is safe at night.", "example_ru": "Этот район безопасен ночью."},
    {"word": "strange", "transcription": "/streɪndʒ/", "translation": "странный", "part_of_speech": "adjective", "example": "That is a strange noise.", "example_ru": "Это странный звук."},
    {"word": "wait", "transcription": "/weɪt/", "translation": "ждать", "part_of_speech": "verb", "example": "Please wait a moment.", "example_ru": "Пожалуйста, подожди минуту."},
    {"word": "meet", "transcription": "/miːt/", "translation": "встречать, знакомиться", "part_of_speech": "verb", "example": "Nice to meet you!", "example_ru": "Приятно познакомиться!"},
    {"word": "difficult", "transcription": "/ˈdɪfɪkəlt/", "translation": "трудный, сложный", "part_of_speech": "adjective", "example": "This exam is very difficult.", "example_ru": "Этот экзамен очень трудный."},
    {"word": "early", "transcription": "/ˈɜːrli/", "translation": "ранний; рано", "part_of_speech": "adjective/adverb", "example": "She wakes up early.", "example_ru": "Она рано просыпается."},
    {"word": "practice", "transcription": "/ˈpræktɪs/", "translation": "практика; практиковать", "part_of_speech": "noun/verb", "example": "Practice makes perfect.", "example_ru": "Практика ведёт к совершенству."},
    {"word": "hope", "transcription": "/hoʊp/", "translation": "надеяться; надежда", "part_of_speech": "verb/noun", "example": "I hope you feel better soon.", "example_ru": "Я надеюсь, ты скоро поправишься."},
    {"word": "surprise", "transcription": "/sərˈpraɪz/", "translation": "сюрприз; удивлять", "part_of_speech": "noun/verb", "example": "What a nice surprise!", "example_ru": "Какой приятный сюрприз!"},
    {"word": "ticket", "transcription": "/ˈtɪkɪt/", "translation": "билет", "part_of_speech": "noun", "example": "I bought two tickets for the train.", "example_ru": "Я купил два билета на поезд."},
    {"word": "message", "transcription": "/ˈmesɪdʒ/", "translation": "сообщение", "part_of_speech": "noun", "example": "Did you get my message?", "example_ru": "Ты получил моё сообщение?"},
    {"word": "question", "transcription": "/ˈkwestʃən/", "translation": "вопрос", "part_of_speech": "noun", "example": "Do you have any questions?", "example_ru": "У тебя есть вопросы?"},
    {"word": "answer", "transcription": "/ˈɑːnsər/", "translation": "ответ; отвечать", "part_of_speech": "noun/verb", "example": "What is the answer?", "example_ru": "Какой ответ?"},
    {"word": "bring", "transcription": "/brɪŋ/", "translation": "приносить, привозить", "part_of_speech": "verb", "example": "Please bring me some water.", "example_ru": "Пожалуйста, принеси мне воды."},
    {"word": "market", "transcription": "/ˈmɑːrkɪt/", "translation": "рынок, магазин", "part_of_speech": "noun", "example": "We buy vegetables at the market.", "example_ru": "Мы покупаем овощи на рынке."},
    {"word": "late", "transcription": "/leɪt/", "translation": "поздний; опаздывать", "part_of_speech": "adjective/verb", "example": "Don't be late for school.", "example_ru": "Не опаздывай в школу."},
    {"word": "neighbour", "transcription": "/ˈneɪbər/", "translation": "сосед, соседка", "part_of_speech": "noun", "example": "My neighbour is very friendly.", "example_ru": "Мой сосед очень дружелюбный."},
    {"word": "colleague", "transcription": "/ˈkɒliːɡ/", "translation": "коллега", "part_of_speech": "noun", "example": "I have lunch with my colleagues.", "example_ru": "Я обедаю с коллегами."},
    {"word": "boss", "transcription": "/bɒs/", "translation": "начальник, босс", "part_of_speech": "noun", "example": "My boss is strict but fair.", "example_ru": "Мой начальник строгий, но справедливый."},
    {"word": "guest", "transcription": "/ɡest/", "translation": "гость", "part_of_speech": "noun", "example": "We have guests for dinner.", "example_ru": "У нас гости на ужин."},
    {"word": "couple", "transcription": "/ˈkʌpəl/", "translation": "пара; несколько", "part_of_speech": "noun", "example": "They are a lovely couple.", "example_ru": "Они прекрасная пара."},
    {"word": "adult", "transcription": "/ˈædʌlt/", "translation": "взрослый", "part_of_speech": "noun/adjective", "example": "This film is for adults only.", "example_ru": "Этот фильм только для взрослых."},
    {"word": "teenager", "transcription": "/ˈtiːneɪdʒər/", "translation": "подросток", "part_of_speech": "noun", "example": "She is a typical teenager.", "example_ru": "Она типичный подросток."},
    {"word": "husband", "transcription": "/ˈhʌzbənd/", "translation": "муж", "part_of_speech": "noun", "example": "Her husband is a doctor.", "example_ru": "Её муж врач."},
    {"word": "wife", "transcription": "/waɪf/", "translation": "жена", "part_of_speech": "noun", "example": "His wife is a teacher.", "example_ru": "Его жена учитель."},
    {"word": "grandma", "transcription": "/ˈɡrænmɑː/", "translation": "бабушка", "part_of_speech": "noun", "example": "My grandma makes great soup.", "example_ru": "Моя бабушка делает отличный суп."},
    {"word": "grandpa", "transcription": "/ˈɡrænpɑː/", "translation": "дедушка", "part_of_speech": "noun", "example": "Grandpa tells great stories.", "example_ru": "Дедушка рассказывает отличные истории."},
    {"word": "doctor", "transcription": "/ˈdɒktər/", "translation": "врач, доктор", "part_of_speech": "noun", "example": "I need to see a doctor.", "example_ru": "Мне нужно попасть к врачу."},
    {"word": "medicine", "transcription": "/ˈmedɪsɪn/", "translation": "лекарство; медицина", "part_of_speech": "noun", "example": "Take this medicine twice a day.", "example_ru": "Принимай это лекарство дважды в день."},
    {"word": "headache", "transcription": "/ˈhedeɪk/", "translation": "головная боль", "part_of_speech": "noun", "example": "I have a terrible headache.", "example_ru": "У меня ужасная головная боль."},
    {"word": "fever", "transcription": "/ˈfiːvər/", "translation": "жар, температура", "part_of_speech": "noun", "example": "The child has a fever.", "example_ru": "У ребёнка жар."},
    {"word": "cough", "transcription": "/kɒf/", "translation": "кашель; кашлять", "part_of_speech": "noun/verb", "example": "He has a bad cough.", "example_ru": "У него сильный кашель."},
    {"word": "pharmacy", "transcription": "/ˈfɑːrməsi/", "translation": "аптека", "part_of_speech": "noun", "example": "The pharmacy is open 24 hours.", "example_ru": "Аптека работает круглосуточно."},
    {"word": "healthy", "transcription": "/ˈhelθi/", "translation": "здоровый", "part_of_speech": "adjective", "example": "Try to eat healthy food.", "example_ru": "Старайся есть здоровую еду."},
    {"word": "ill", "transcription": "/ɪl/", "translation": "больной, нездоровый", "part_of_speech": "adjective", "example": "She is ill and stays in bed.", "example_ru": "Она больна и лежит в кровати."},
    {"word": "pain", "transcription": "/peɪn/", "translation": "боль", "part_of_speech": "noun", "example": "He felt a sharp pain.", "example_ru": "Он почувствовал острую боль."},
    {"word": "exercise", "transcription": "/ˈeksəsaɪz/", "translation": "упражнение; заниматься", "part_of_speech": "noun/verb", "example": "Regular exercise keeps you fit.", "example_ru": "Регулярные упражнения поддерживают форму."},
    {"word": "restaurant", "transcription": "/ˈrestrɒnt/", "translation": "ресторан", "part_of_speech": "noun", "example": "Let's go to a restaurant.", "example_ru": "Давай пойдём в ресторан."},
    {"word": "menu", "transcription": "/ˈmenjuː/", "translation": "меню", "part_of_speech": "noun", "example": "Can I see the menu, please?", "example_ru": "Можно мне меню, пожалуйста?"},
    {"word": "waiter", "transcription": "/ˈweɪtər/", "translation": "официант", "part_of_speech": "noun", "example": "The waiter brought our food.", "example_ru": "Официант принёс нашу еду."},
    {"word": "order", "transcription": "/ˈɔːrdər/", "translation": "заказ; заказывать", "part_of_speech": "noun/verb", "example": "I would like to order a pizza.", "example_ru": "Я бы хотел заказать пиццу."},
    {"word": "delicious", "transcription": "/dɪˈlɪʃəs/", "translation": "вкусный, восхитительный", "part_of_speech": "adjective", "example": "This cake is delicious!", "example_ru": "Этот торт восхитительный!"},
    {"word": "dessert", "transcription": "/dɪˈzɜːrt/", "translation": "десерт", "part_of_speech": "noun", "example": "What would you like for dessert?", "example_ru": "Что вы хотите на десерт?"},
    {"word": "vegetable", "transcription": "/ˈvedʒtəbl/", "translation": "овощ", "part_of_speech": "noun", "example": "Eat more vegetables every day.", "example_ru": "Ешь больше овощей каждый день."},
    {"word": "fruit", "transcription": "/fruːt/", "translation": "фрукт", "part_of_speech": "noun", "example": "I eat fruit for breakfast.", "example_ru": "Я ем фрукты на завтрак."},
    {"word": "juice", "transcription": "/dʒuːs/", "translation": "сок", "part_of_speech": "noun", "example": "A glass of orange juice, please.", "example_ru": "Стакан апельсинового сока, пожалуйста."},
    {"word": "bottle", "transcription": "/ˈbɒtəl/", "translation": "бутылка", "part_of_speech": "noun", "example": "Bring a bottle of water.", "example_ru": "Принеси бутылку воды."},
    {"word": "plate", "transcription": "/pleɪt/", "translation": "тарелка", "part_of_speech": "noun", "example": "The plate is on the table.", "example_ru": "Тарелка на столе."},
    {"word": "fork", "transcription": "/fɔːrk/", "translation": "вилка", "part_of_speech": "noun", "example": "Use a fork to eat pasta.", "example_ru": "Используй вилку для пасты."},
    {"word": "spoon", "transcription": "/spuːn/", "translation": "ложка", "part_of_speech": "noun", "example": "Stir with a spoon.", "example_ru": "Помешай ложкой."},
    {"word": "knife", "transcription": "/naɪf/", "translation": "нож", "part_of_speech": "noun", "example": "Be careful with the knife.", "example_ru": "Будь осторожен с ножом."},
    {"word": "snack", "transcription": "/snæk/", "translation": "перекус", "part_of_speech": "noun/verb", "example": "I had a snack between meals.", "example_ru": "Я перекусил между приёмами пищи."},
    {"word": "lunch", "transcription": "/lʌntʃ/", "translation": "обед", "part_of_speech": "noun", "example": "What did you have for lunch?", "example_ru": "Что ты ел на обед?"},
    {"word": "dinner", "transcription": "/ˈdɪnər/", "translation": "ужин", "part_of_speech": "noun", "example": "Dinner is ready!", "example_ru": "Ужин готов!"},
    {"word": "breakfast", "transcription": "/ˈbrekfəst/", "translation": "завтрак", "part_of_speech": "noun", "example": "I never skip breakfast.", "example_ru": "Я никогда не пропускаю завтрак."},
    {"word": "flat", "transcription": "/flæt/", "translation": "квартира", "part_of_speech": "noun", "example": "We live in a small flat.", "example_ru": "Мы живём в маленькой квартире."},
    {"word": "address", "transcription": "/əˈdres/", "translation": "адрес", "part_of_speech": "noun", "example": "What is your home address?", "example_ru": "Какой у тебя домашний адрес?"},
    {"word": "living room", "transcription": "/ˈlɪvɪŋ ruːm/", "translation": "гостиная", "part_of_speech": "noun", "example": "We watch TV in the living room.", "example_ru": "Мы смотрим телевизор в гостиной."},
    {"word": "bedroom", "transcription": "/ˈbedruːm/", "translation": "спальня", "part_of_speech": "noun", "example": "The bedroom is upstairs.", "example_ru": "Спальня наверху."},
    {"word": "sofa", "transcription": "/ˈsəʊfə/", "translation": "диван", "part_of_speech": "noun", "example": "He fell asleep on the sofa.", "example_ru": "Он заснул на диване."},
    {"word": "shelf", "transcription": "/ʃelf/", "translation": "полка", "part_of_speech": "noun", "example": "The books are on the shelf.", "example_ru": "Книги на полке."},
    {"word": "mirror", "transcription": "/ˈmɪrər/", "translation": "зеркало", "part_of_speech": "noun", "example": "She looks in the mirror.", "example_ru": "Она смотрится в зеркало."},
    {"word": "carpet", "transcription": "/ˈkɑːrpɪt/", "translation": "ковёр", "part_of_speech": "noun", "example": "There is a big carpet in the room.", "example_ru": "В комнате большой ковёр."},
    {"word": "fridge", "transcription": "/frɪdʒ/", "translation": "холодильник", "part_of_speech": "noun", "example": "Put the milk in the fridge.", "example_ru": "Поставь молоко в холодильник."},
    {"word": "rubbish", "transcription": "/ˈrʌbɪʃ/", "translation": "мусор", "part_of_speech": "noun", "example": "Take out the rubbish, please.", "example_ru": "Вынеси мусор, пожалуйста."},
    {"word": "office", "transcription": "/ˈɒfɪs/", "translation": "офис", "part_of_speech": "noun", "example": "I work in a small office.", "example_ru": "Я работаю в небольшом офисе."},
    {"word": "meeting", "transcription": "/ˈmiːtɪŋ/", "translation": "встреча, собрание", "part_of_speech": "noun", "example": "We have a meeting at nine.", "example_ru": "У нас встреча в девять."},
    {"word": "salary", "transcription": "/ˈsæləri/", "translation": "зарплата", "part_of_speech": "noun", "example": "His salary is quite good.", "example_ru": "У него неплохая зарплата."},
    {"word": "interview", "transcription": "/ˈɪntəvjuː/", "translation": "собеседование; интервью", "part_of_speech": "noun", "example": "She has a job interview tomorrow.", "example_ru": "Завтра у неё собеседование."},
    {"word": "company", "transcription": "/ˈkʌmpəni/", "translation": "компания", "part_of_speech": "noun", "example": "He works for a big company.", "example_ru": "Он работает в большой компании."},
    {"word": "job", "transcription": "/dʒɒb/", "translation": "работа, должность", "part_of_speech": "noun", "example": "I found a new job.", "example_ru": "Я нашёл новую работу."},
    {"word": "career", "transcription": "/kəˈrɪər/", "translation": "карьера", "part_of_speech": "noun", "example": "She has a great career.", "example_ru": "У неё отличная карьера."},
    {"word": "university", "transcription": "/ˌjuːnɪˈvɜːrsɪti/", "translation": "университет", "part_of_speech": "noun", "example": "He studies at university.", "example_ru": "Он учится в университете."},
    {"word": "subject", "transcription": "/ˈsʌbdʒɪkt/", "translation": "предмет, тема", "part_of_speech": "noun", "example": "What is your favourite subject?", "example_ru": "Какой твой любимый предмет?"},
    {"word": "exam", "transcription": "/ɪɡˈzæm/", "translation": "экзамен", "part_of_speech": "noun", "example": "I have an exam on Friday.", "example_ru": "В пятницу у меня экзамен."},
    {"word": "lesson", "transcription": "/ˈlesən/", "translation": "урок, занятие", "part_of_speech": "noun", "example": "The lesson starts at eight.", "example_ru": "Урок начинается в восемь."},
    {"word": "homework", "transcription": "/ˈhəʊmwɜːrk/", "translation": "домашнее задание", "part_of_speech": "noun", "example": "Did you do your homework?", "example_ru": "Ты сделал домашнее задание?"},
    {"word": "grade", "transcription": "/ɡreɪd/", "translation": "оценка, класс", "part_of_speech": "noun", "example": "She got a good grade.", "example_ru": "Она получила хорошую оценку."},
    {"word": "library", "transcription": "/ˈlaɪbrəri/", "translation": "библиотека", "part_of_speech": "noun", "example": "I borrowed a book from the library.", "example_ru": "Я взял книгу в библиотеке."},
    {"word": "dictionary", "transcription": "/ˈdɪkʃənri/", "translation": "словарь", "part_of_speech": "noun", "example": "Look it up in the dictionary.", "example_ru": "Посмотри это в словаре."},
    {"word": "traffic", "transcription": "/ˈtræfɪk/", "translation": "дорожное движение, пробки", "part_of_speech": "noun", "example": "The traffic is terrible today.", "example_ru": "Сегодня ужасные пробки."},
    {"word": "station", "transcription": "/ˈsteɪʃən/", "translation": "вокзал, станция", "part_of_speech": "noun", "example": "Meet me at the station.", "example_ru": "Встреть меня на вокзале."},
    {"word": "underground", "transcription": "/ˈʌndəɡraʊnd/", "translation": "метро", "part_of_speech": "noun", "example": "Take the underground to the centre.", "example_ru": "Доедь до центра на метро."},
    {"word": "direction", "transcription": "/dɪˈrekʃən/", "translation": "направление", "part_of_speech": "noun", "example": "Go in that direction.", "example_ru": "Иди в том направлении."},
    {"word": "corner", "transcription": "/ˈkɔːrnər/", "translation": "угол, поворот", "part_of_speech": "noun", "example": "Turn left at the corner.", "example_ru": "Поверни налево на углу."},
    {"word": "bridge", "transcription": "/brɪdʒ/", "translation": "мост", "part_of_speech": "noun", "example": "Cross the bridge.", "example_ru": "Перейди мост."},
    {"word": "square", "transcription": "/skweər/", "translation": "площадь; квадрат", "part_of_speech": "noun", "example": "Meet me at the main square.", "example_ru": "Встретимся на главной площади."},
    {"word": "opposite", "transcription": "/ˈɒpəzɪt/", "translation": "напротив, противоположный", "part_of_speech": "preposition/adjective", "example": "The cafe is opposite the bank.", "example_ru": "Кафе напротив банка."},
    {"word": "hobby", "transcription": "/ˈhɒbi/", "translation": "хобби, увлечение", "part_of_speech": "noun", "example": "What is your hobby?", "example_ru": "Какое у тебя хобби?"},
    {"word": "concert", "transcription": "/ˈkɒnsət/", "translation": "концерт", "part_of_speech": "noun", "example": "We went to a concert last night.", "example_ru": "Вчера вечером мы ходили на концерт."},
    {"word": "theatre", "transcription": "/ˈθɪətər/", "translation": "театр", "part_of_speech": "noun", "example": "I love going to the theatre.", "example_ru": "Я люблю ходить в театр."},
    {"word": "cinema", "transcription": "/ˈsɪnəmə/", "translation": "кино, кинотеатр", "part_of_speech": "noun", "example": "Shall we go to the cinema?", "example_ru": "Может, сходим в кино?"},
    {"word": "museum", "transcription": "/mjuːˈziːəm/", "translation": "музей", "part_of_speech": "noun", "example": "Let's visit the history museum.", "example_ru": "Давай посетим исторический музей."},
    {"word": "festival", "transcription": "/ˈfestɪvəl/", "translation": "фестиваль, праздник", "part_of_speech": "noun", "example": "The music festival was amazing.", "example_ru": "Музыкальный фестиваль был потрясающим."},
    {"word": "party", "transcription": "/ˈpɑːrti/", "translation": "вечеринка, праздник", "part_of_speech": "noun", "example": "Are you coming to the party?", "example_ru": "Ты придёшь на вечеринку?"},
    {"word": "holiday", "transcription": "/ˈhɒlɪdeɪ/", "translation": "праздник; отпуск", "part_of_speech": "noun", "example": "We went to Spain for our holiday.", "example_ru": "Мы поехали в Испанию в отпуск."},
    {"word": "camping", "transcription": "/ˈkæmpɪŋ/", "translation": "кемпинг, поход с палаткой", "part_of_speech": "noun", "example": "We go camping every summer.", "example_ru": "Мы ходим в поход каждое лето."},
    {"word": "picnic", "transcription": "/ˈpɪknɪk/", "translation": "пикник", "part_of_speech": "noun", "example": "Let's have a picnic in the park.", "example_ru": "Давай устроим пикник в парке."},
    {"word": "painting", "transcription": "/ˈpeɪntɪŋ/", "translation": "картина; рисование", "part_of_speech": "noun", "example": "She has a talent for painting.", "example_ru": "У неё есть талант к рисованию."},
    {"word": "swimming", "transcription": "/ˈswɪmɪŋ/", "translation": "плавание", "part_of_speech": "noun", "example": "Swimming is great exercise.", "example_ru": "Плавание — отличная физическая нагрузка."},
    {"word": "hiking", "transcription": "/ˈhaɪkɪŋ/", "translation": "пеший туризм, походы", "part_of_speech": "noun", "example": "We love hiking in the mountains.", "example_ru": "Мы любим походы в горы."},
    {"word": "season", "transcription": "/ˈsiːzən/", "translation": "сезон, время года", "part_of_speech": "noun", "example": "What is your favourite season?", "example_ru": "Какое твоё любимое время года?"},
    {"word": "spring", "transcription": "/sprɪŋ/", "translation": "весна", "part_of_speech": "noun", "example": "Flowers bloom in spring.", "example_ru": "Весной цветут цветы."},
    {"word": "summer", "transcription": "/ˈsʌmər/", "translation": "лето", "part_of_speech": "noun", "example": "I love swimming in summer.", "example_ru": "Я люблю купаться летом."},
    {"word": "autumn", "transcription": "/ˈɔːtəm/", "translation": "осень", "part_of_speech": "noun", "example": "Leaves fall in autumn.", "example_ru": "Осенью падают листья."},
    {"word": "winter", "transcription": "/ˈwɪntər/", "translation": "зима", "part_of_speech": "noun", "example": "Winters here are very cold.", "example_ru": "Зимы здесь очень холодные."},
    {"word": "temperature", "transcription": "/ˈtemprɪtʃər/", "translation": "температура", "part_of_speech": "noun", "example": "The temperature is minus ten.", "example_ru": "Температура минус десять."},
    {"word": "cloud", "transcription": "/klaʊd/", "translation": "облако", "part_of_speech": "noun", "example": "There are dark clouds in the sky.", "example_ru": "На небе тёмные облака."},
    {"word": "wind", "transcription": "/wɪnd/", "translation": "ветер", "part_of_speech": "noun", "example": "The wind is very strong today.", "example_ru": "Сегодня очень сильный ветер."},
    {"word": "storm", "transcription": "/stɔːrm/", "translation": "буря, шторм", "part_of_speech": "noun", "example": "There was a big storm last night.", "example_ru": "Прошлой ночью была сильная буря."},
    {"word": "sunshine", "transcription": "/ˈsʌnʃaɪn/", "translation": "солнечный свет", "part_of_speech": "noun", "example": "I love walking in the sunshine.", "example_ru": "Я люблю гулять на солнце."},
    {"word": "fog", "transcription": "/fɒɡ/", "translation": "туман", "part_of_speech": "noun", "example": "There is thick fog this morning.", "example_ru": "Этим утром густой туман."},
    {"word": "pollution", "transcription": "/pəˈluːʃən/", "translation": "загрязнение", "part_of_speech": "noun", "example": "Air pollution is a big problem.", "example_ru": "Загрязнение воздуха — большая проблема."},
    {"word": "price", "transcription": "/praɪs/", "translation": "цена", "part_of_speech": "noun", "example": "What is the price of this jacket?", "example_ru": "Какова цена этой куртки?"},
    {"word": "discount", "transcription": "/ˈdɪskaʊnt/", "translation": "скидка", "part_of_speech": "noun", "example": "There is a 20% discount today.", "example_ru": "Сегодня скидка 20%."},
    {"word": "cash", "transcription": "/kæʃ/", "translation": "наличные деньги", "part_of_speech": "noun", "example": "Do you pay by cash or card?", "example_ru": "Ты платишь наличными или картой?"},
    {"word": "afford", "transcription": "/əˈfɔːrd/", "translation": "позволить себе", "part_of_speech": "verb", "example": "I can't afford a new phone.", "example_ru": "Я не могу позволить себе новый телефон."},
    {"word": "spend", "transcription": "/spend/", "translation": "тратить (деньги/время)", "part_of_speech": "verb", "example": "I spend too much money on food.", "example_ru": "Я трачу слишком много денег на еду."},
    {"word": "save", "transcription": "/seɪv/", "translation": "копить; спасать", "part_of_speech": "verb", "example": "I am saving money for a trip.", "example_ru": "Я коплю деньги на поездку."},
    {"word": "sell", "transcription": "/sel/", "translation": "продавать", "part_of_speech": "verb", "example": "She sells handmade jewellery.", "example_ru": "Она продаёт украшения ручной работы."},
    {"word": "borrow", "transcription": "/ˈbɒrəʊ/", "translation": "брать взаймы", "part_of_speech": "verb", "example": "Can I borrow your pen?", "example_ru": "Можно одолжить твою ручку?"},
    {"word": "lend", "transcription": "/lend/", "translation": "давать взаймы", "part_of_speech": "verb", "example": "Can you lend me some money?", "example_ru": "Ты можешь одолжить мне денег?"},
    {"word": "rent", "transcription": "/rent/", "translation": "аренда; снимать жильё", "part_of_speech": "noun/verb", "example": "We rent a flat in the centre.", "example_ru": "Мы снимаем квартиру в центре."},
    {"word": "nervous", "transcription": "/ˈnɜːrvəs/", "translation": "нервный, взволнованный", "part_of_speech": "adjective", "example": "She felt nervous before the exam.", "example_ru": "Она нервничала перед экзаменом."},
    {"word": "excited", "transcription": "/ɪkˈsaɪtɪd/", "translation": "взволнованный, в восторге", "part_of_speech": "adjective", "example": "The children are excited about the trip.", "example_ru": "Дети в восторге от поездки."},
    {"word": "bored", "transcription": "/bɔːrd/", "translation": "скучающий", "part_of_speech": "adjective", "example": "I feel bored at home.", "example_ru": "Мне скучно дома."},
    {"word": "scared", "transcription": "/skeərd/", "translation": "напуганный", "part_of_speech": "adjective", "example": "She is scared of spiders.", "example_ru": "Она боится пауков."},
    {"word": "proud", "transcription": "/praʊd/", "translation": "гордый", "part_of_speech": "adjective", "example": "I am proud of you.", "example_ru": "Я горжусь тобой."},
    {"word": "relaxed", "transcription": "/rɪˈlækst/", "translation": "расслабленный", "part_of_speech": "adjective", "example": "I feel relaxed after yoga.", "example_ru": "После йоги я чувствую себя расслабленно."},
    {"word": "worried", "transcription": "/ˈwʌrid/", "translation": "обеспокоенный", "part_of_speech": "adjective", "example": "Don't be worried, it is fine.", "example_ru": "Не беспокойся, всё хорошо."},
    {"word": "confident", "transcription": "/ˈkɒnfɪdənt/", "translation": "уверенный в себе", "part_of_speech": "adjective", "example": "She is confident and calm.", "example_ru": "Она уверенная и спокойная."},
    {"word": "friendly", "transcription": "/ˈfrendli/", "translation": "дружелюбный", "part_of_speech": "adjective", "example": "Everyone here is very friendly.", "example_ru": "Все здесь очень дружелюбные."},
    {"word": "kind", "transcription": "/kaɪnd/", "translation": "добрый, любезный", "part_of_speech": "adjective", "example": "She is always kind to others.", "example_ru": "Она всегда добра к другим."},
    {"word": "polite", "transcription": "/pəˈlaɪt/", "translation": "вежливый", "part_of_speech": "adjective", "example": "Always be polite to guests.", "example_ru": "Всегда будь вежлив с гостями."},
    {"word": "rude", "transcription": "/ruːd/", "translation": "грубый, невежливый", "part_of_speech": "adjective", "example": "It is rude to interrupt.", "example_ru": "Прерывать — невежливо."},
    {"word": "clever", "transcription": "/ˈklevər/", "translation": "умный, сообразительный", "part_of_speech": "adjective", "example": "She is a clever student.", "example_ru": "Она умная студентка."},
    {"word": "serious", "transcription": "/ˈsɪəriəs/", "translation": "серьёзный", "part_of_speech": "adjective", "example": "He looks very serious today.", "example_ru": "Сегодня он выглядит очень серьёзно."},
    {"word": "lazy", "transcription": "/ˈleɪzi/", "translation": "ленивый", "part_of_speech": "adjective", "example": "Don't be lazy, do your work.", "example_ru": "Не ленись, делай свою работу."},
    {"word": "patient", "transcription": "/ˈpeɪʃənt/", "translation": "терпеливый; пациент", "part_of_speech": "adjective/noun", "example": "Be patient, it takes time.", "example_ru": "Будь терпелив, это требует времени."},
    {"word": "arrive", "transcription": "/əˈraɪv/", "translation": "прибывать, приезжать", "part_of_speech": "verb", "example": "What time does the train arrive?", "example_ru": "В какое время прибывает поезд?"},
    {"word": "leave", "transcription": "/liːv/", "translation": "уходить; оставлять", "part_of_speech": "verb", "example": "I leave work at six.", "example_ru": "Я ухожу с работы в шесть."},
    {"word": "return", "transcription": "/rɪˈtɜːrn/", "translation": "возвращаться; возврат", "part_of_speech": "verb/noun", "example": "When do you return home?", "example_ru": "Когда ты возвращаешься домой?"},
    {"word": "visit", "transcription": "/ˈvɪzɪt/", "translation": "посещать; визит", "part_of_speech": "verb/noun", "example": "We visit grandma on Sundays.", "example_ru": "По воскресеньям мы навещаем бабушку."},
    {"word": "invite", "transcription": "/ɪnˈvaɪt/", "translation": "приглашать", "part_of_speech": "verb", "example": "I invited her to my birthday.", "example_ru": "Я пригласил её на день рождения."},
    {"word": "send", "transcription": "/send/", "translation": "отправлять, посылать", "part_of_speech": "verb", "example": "Send me the document.", "example_ru": "Отправь мне документ."},
    {"word": "check", "transcription": "/tʃek/", "translation": "проверять", "part_of_speech": "verb/noun", "example": "Check your email every day.", "example_ru": "Проверяй электронную почту каждый день."},
    {"word": "book", "transcription": "/bʊk/", "translation": "бронировать", "part_of_speech": "verb", "example": "I need to book a hotel room.", "example_ru": "Мне нужно забронировать номер в отеле."},
    {"word": "miss", "transcription": "/mɪs/", "translation": "скучать по; пропускать", "part_of_speech": "verb", "example": "I miss my family.", "example_ru": "Я скучаю по семье."},
    {"word": "lose", "transcription": "/luːz/", "translation": "терять; проигрывать", "part_of_speech": "verb", "example": "I always lose my keys.", "example_ru": "Я всегда теряю ключи."},
    {"word": "win", "transcription": "/wɪn/", "translation": "побеждать, выигрывать", "part_of_speech": "verb", "example": "Our team won the match.", "example_ru": "Наша команда выиграла матч."},
    {"word": "happen", "transcription": "/ˈhæpən/", "translation": "происходить, случаться", "part_of_speech": "verb", "example": "What happened to you?", "example_ru": "Что с тобой случилось?"},
    {"word": "decide", "transcription": "/dɪˈsaɪd/", "translation": "решать", "part_of_speech": "verb", "example": "Have you decided yet?", "example_ru": "Ты уже решил?"},
    {"word": "agree", "transcription": "/əˈɡriː/", "translation": "соглашаться", "part_of_speech": "verb", "example": "I agree with you.", "example_ru": "Я с тобой согласен."},
    {"word": "complain", "transcription": "/kəmˈpleɪn/", "translation": "жаловаться", "part_of_speech": "verb", "example": "He always complains about the weather.", "example_ru": "Он всегда жалуется на погоду."},
    {"word": "promise", "transcription": "/ˈprɒmɪs/", "translation": "обещать; обещание", "part_of_speech": "verb/noun", "example": "I promise to be there.", "example_ru": "Обещаю быть там."},
    {"word": "offer", "transcription": "/ˈɒfər/", "translation": "предлагать; предложение", "part_of_speech": "verb/noun", "example": "He offered to help.", "example_ru": "Он предложил помочь."},
    {"word": "refuse", "transcription": "/rɪˈfjuːz/", "translation": "отказывать, отказываться", "part_of_speech": "verb", "example": "She refused to answer.", "example_ru": "Она отказалась отвечать."},
    {"word": "accept", "transcription": "/əkˈsept/", "translation": "принимать, соглашаться", "part_of_speech": "verb", "example": "I accept your offer.", "example_ru": "Я принимаю твоё предложение."},
    {"word": "join", "transcription": "/dʒɔɪn/", "translation": "присоединяться", "part_of_speech": "verb", "example": "Can I join your team?", "example_ru": "Можно мне присоединиться к вашей команде?"},
    {"word": "prepare", "transcription": "/prɪˈpeər/", "translation": "готовить(ся)", "part_of_speech": "verb", "example": "Prepare for the exam.", "example_ru": "Готовься к экзамену."},
    {"word": "share", "transcription": "/ʃeər/", "translation": "делиться; доля", "part_of_speech": "verb/noun", "example": "Share your food with others.", "example_ru": "Поделись едой с другими."},
    {"word": "describe", "transcription": "/dɪˈskraɪb/", "translation": "описывать", "part_of_speech": "verb", "example": "Describe what you see.", "example_ru": "Опиши то, что видишь."},
    {"word": "repeat", "transcription": "/rɪˈpiːt/", "translation": "повторять", "part_of_speech": "verb", "example": "Please repeat that.", "example_ru": "Пожалуйста, повтори это."},
    {"word": "translate", "transcription": "/trænsˈleɪt/", "translation": "переводить", "part_of_speech": "verb", "example": "Can you translate this sentence?", "example_ru": "Ты можешь перевести это предложение?"},
    {"word": "problem", "transcription": "/ˈprɒbləm/", "translation": "проблема", "part_of_speech": "noun", "example": "We have a small problem.", "example_ru": "У нас небольшая проблема."},
    {"word": "idea", "transcription": "/aɪˈdɪə/", "translation": "идея", "part_of_speech": "noun", "example": "That is a great idea!", "example_ru": "Это отличная идея!"},
    {"word": "plan", "transcription": "/plæn/", "translation": "план; планировать", "part_of_speech": "noun/verb", "example": "What is your plan for the weekend?", "example_ru": "Какие у тебя планы на выходные?"},
    {"word": "mistake", "transcription": "/mɪˈsteɪk/", "translation": "ошибка", "part_of_speech": "noun", "example": "Everyone makes mistakes.", "example_ru": "Все совершают ошибки."},
    {"word": "advice", "transcription": "/ədˈvaɪs/", "translation": "совет", "part_of_speech": "noun", "example": "Can you give me some advice?", "example_ru": "Ты можешь дать мне совет?"},
    {"word": "information", "transcription": "/ˌɪnfəˈmeɪʃən/", "translation": "информация", "part_of_speech": "noun", "example": "I need more information.", "example_ru": "Мне нужно больше информации."},
    {"word": "news", "transcription": "/njuːz/", "translation": "новости", "part_of_speech": "noun", "example": "Have you heard the news?", "example_ru": "Ты слышал новости?"},
    {"word": "reason", "transcription": "/ˈriːzən/", "translation": "причина, повод", "part_of_speech": "noun", "example": "What is the reason for this?", "example_ru": "В чём причина этого?"},
    {"word": "result", "transcription": "/rɪˈzʌlt/", "translation": "результат", "part_of_speech": "noun", "example": "What was the result of the test?", "example_ru": "Каков результат теста?"},
    {"word": "difference", "transcription": "/ˈdɪfrəns/", "translation": "разница, отличие", "part_of_speech": "noun", "example": "What is the difference?", "example_ru": "В чём разница?"},
    {"word": "popular", "transcription": "/ˈpɒpjʊlər/", "translation": "популярный", "part_of_speech": "adjective", "example": "Football is very popular here.", "example_ru": "Футбол здесь очень популярен."},
    {"word": "special", "transcription": "/ˈspeʃəl/", "translation": "особый, специальный", "part_of_speech": "adjective", "example": "Today is a special day.", "example_ru": "Сегодня особенный день."},
    {"word": "important", "transcription": "/ɪmˈpɔːrtənt/", "translation": "важный", "part_of_speech": "adjective", "example": "This is very important.", "example_ru": "Это очень важно."},
    {"word": "interesting", "transcription": "/ˈɪntrɪstɪŋ/", "translation": "интересный", "part_of_speech": "adjective", "example": "That is an interesting story.", "example_ru": "Это интересная история."},
    {"word": "boring", "transcription": "/ˈbɔːrɪŋ/", "translation": "скучный", "part_of_speech": "adjective", "example": "The film was boring.", "example_ru": "Фильм был скучным."},
    {"word": "useful", "transcription": "/ˈjuːsfəl/", "translation": "полезный", "part_of_speech": "adjective", "example": "This dictionary is very useful.", "example_ru": "Этот словарь очень полезный."},
    {"word": "possible", "transcription": "/ˈpɒsɪbəl/", "translation": "возможный", "part_of_speech": "adjective", "example": "Is it possible to change the date?", "example_ru": "Можно ли поменять дату?"},
    {"word": "enough", "transcription": "/ɪˈnʌf/", "translation": "достаточно", "part_of_speech": "adverb/adjective", "example": "I have enough money.", "example_ru": "У меня достаточно денег."},
    {"word": "almost", "transcription": "/ˈɔːlməʊst/", "translation": "почти", "part_of_speech": "adverb", "example": "I am almost ready.", "example_ru": "Я почти готов."},
    {"word": "already", "transcription": "/ɔːlˈredi/", "translation": "уже", "part_of_speech": "adverb", "example": "I have already eaten.", "example_ru": "Я уже поел."},
    {"word": "yet", "transcription": "/jet/", "translation": "ещё (в вопросах/отрицаниях)", "part_of_speech": "adverb", "example": "Have you finished yet?", "example_ru": "Ты уже закончил?"},
    {"word": "still", "transcription": "/stɪl/", "translation": "всё ещё", "part_of_speech": "adverb", "example": "Are you still here?", "example_ru": "Ты всё ещё здесь?"},
    {"word": "together", "transcription": "/təˈɡeðər/", "translation": "вместе", "part_of_speech": "adverb", "example": "Let's do it together.", "example_ru": "Давай сделаем это вместе."},
    {"word": "both", "transcription": "/bəʊθ/", "translation": "оба, обе", "part_of_speech": "determiner", "example": "Both answers are correct.", "example_ru": "Оба ответа правильные."},
    {"word": "everyone", "transcription": "/ˈevriwʌn/", "translation": "все, каждый", "part_of_speech": "pronoun", "example": "Everyone loves pizza.", "example_ru": "Все любят пиццу."},
    {"word": "everything", "transcription": "/ˈevriθɪŋ/", "translation": "всё", "part_of_speech": "pronoun", "example": "Everything is ready.", "example_ru": "Всё готово."},
    {"word": "nothing", "transcription": "/ˈnʌθɪŋ/", "translation": "ничего", "part_of_speech": "pronoun", "example": "There is nothing to eat.", "example_ru": "Нечего есть."},
    {"word": "suddenly", "transcription": "/ˈsʌdənli/", "translation": "внезапно, вдруг", "part_of_speech": "adverb", "example": "Suddenly the lights went off.", "example_ru": "Внезапно свет погас."},
    {"word": "finally", "transcription": "/ˈfaɪnəli/", "translation": "наконец, в конце концов", "part_of_speech": "adverb", "example": "We finally arrived.", "example_ru": "Мы наконец прибыли."},
    {"word": "really", "transcription": "/ˈrɪəli/", "translation": "действительно, очень", "part_of_speech": "adverb", "example": "I really like this place.", "example_ru": "Мне очень нравится это место."},
    {"word": "quite", "transcription": "/kwaɪt/", "translation": "довольно, весьма", "part_of_speech": "adverb", "example": "The film was quite good.", "example_ru": "Фильм был довольно хорошим."},
    {"word": "probably", "transcription": "/ˈprɒbəbli/", "translation": "вероятно, наверное", "part_of_speech": "adverb", "example": "He is probably at home.", "example_ru": "Вероятно, он дома."},
    {"word": "similar", "transcription": "/ˈsɪmɪlər/", "translation": "похожий, подобный", "part_of_speech": "adjective", "example": "These two words are similar.", "example_ru": "Эти два слова похожи."},
    {"word": "receive", "transcription": "/rɪˈsiːv/", "translation": "получать", "part_of_speech": "verb", "example": "Did you receive my email?", "example_ru": "Ты получил моё письмо?"},
    {"word": "argue", "transcription": "/ˈɑːrɡjuː/", "translation": "спорить, ссориться", "part_of_speech": "verb", "example": "They argue about everything.", "example_ru": "Они спорят обо всём."},
    {"word": "pronounce", "transcription": "/prəˈnaʊns/", "translation": "произносить", "part_of_speech": "verb", "example": "How do you pronounce this word?", "example_ru": "Как произносится это слово?"},
]

