WORDS_B1 = [
    # ── уже были в боте ───────────────────────────────────────────────────────
    {"word": "achieve", "transcription": "/əˈtʃiːv/", "translation": "достигать, добиваться", "part_of_speech": "verb", "example": "She worked hard to achieve her goals.", "example_ru": "Она усердно работала, чтобы достичь своих целей."},
    {"word": "influence", "transcription": "/ˈɪnfluəns/", "translation": "влиять; влияние", "part_of_speech": "verb/noun", "example": "Music can influence our mood.", "example_ru": "Музыка может влиять на настроение."},
    {"word": "opportunity", "transcription": "/ˌɒpəˈtjuːnɪti/", "translation": "возможность", "part_of_speech": "noun", "example": "This is a great opportunity.", "example_ru": "Это отличная возможность."},
    {"word": "significant", "transcription": "/sɪɡˈnɪfɪkənt/", "translation": "значительный, важный", "part_of_speech": "adjective", "example": "There has been a significant improvement.", "example_ru": "Наблюдалось значительное улучшение."},
    {"word": "consider", "transcription": "/kənˈsɪdər/", "translation": "рассматривать, считать", "part_of_speech": "verb", "example": "Please consider my offer.", "example_ru": "Пожалуйста, рассмотри моё предложение."},
    {"word": "suggest", "transcription": "/səˈdʒest/", "translation": "предлагать, предполагать", "part_of_speech": "verb", "example": "I suggest we leave early.", "example_ru": "Я предлагаю уйти пораньше."},
    {"word": "improve", "transcription": "/ɪmˈpruːv/", "translation": "улучшать(ся)", "part_of_speech": "verb", "example": "You need to improve your writing.", "example_ru": "Тебе нужно улучшить письмо."},
    {"word": "require", "transcription": "/rɪˈkwaɪər/", "translation": "требовать, нуждаться", "part_of_speech": "verb", "example": "This job requires experience.", "example_ru": "Эта работа требует опыта."},
    {"word": "experience", "transcription": "/ɪkˈspɪəriəns/", "translation": "опыт; переживать", "part_of_speech": "noun/verb", "example": "I have experience in teaching.", "example_ru": "У меня есть опыт преподавания."},
    {"word": "purpose", "transcription": "/ˈpɜːrpəs/", "translation": "цель, намерение", "part_of_speech": "noun", "example": "What is the purpose of this meeting?", "example_ru": "Какова цель этой встречи?"},
    {"word": "aware", "transcription": "/əˈweər/", "translation": "осведомлённый, знающий", "part_of_speech": "adjective", "example": "Are you aware of the risks?", "example_ru": "Ты осведомлён о рисках?"},
    {"word": "effort", "transcription": "/ˈefərt/", "translation": "усилие, старание", "part_of_speech": "noun", "example": "It takes a lot of effort.", "example_ru": "Это требует больших усилий."},
    {"word": "despite", "transcription": "/dɪˈspaɪt/", "translation": "несмотря на", "part_of_speech": "preposition", "example": "Despite the rain, we went out.", "example_ru": "Несмотря на дождь, мы вышли."},
    {"word": "benefit", "transcription": "/ˈbenɪfɪt/", "translation": "польза, выгода; получать пользу", "part_of_speech": "noun/verb", "example": "Exercise has many health benefits.", "example_ru": "Упражнения имеют много преимуществ для здоровья."},
    {"word": "develop", "transcription": "/dɪˈveləp/", "translation": "развивать(ся)", "part_of_speech": "verb", "example": "She developed a new skill.", "example_ru": "Она развила новый навык."},
    {"word": "available", "transcription": "/əˈveɪləbl/", "translation": "доступный, имеющийся", "part_of_speech": "adjective", "example": "Is this product available online?", "example_ru": "Этот товар доступен онлайн?"},
    {"word": "provide", "transcription": "/prəˈvaɪd/", "translation": "обеспечивать, предоставлять", "part_of_speech": "verb", "example": "We provide free support.", "example_ru": "Мы предоставляем бесплатную поддержку."},
    {"word": "challenge", "transcription": "/ˈtʃælɪndʒ/", "translation": "вызов, трудность; бросать вызов", "part_of_speech": "noun/verb", "example": "Learning a language is a challenge.", "example_ru": "Изучение языка — это вызов."},
    {"word": "solution", "transcription": "/səˈluːʃən/", "translation": "решение, выход", "part_of_speech": "noun", "example": "We need to find a solution.", "example_ru": "Нам нужно найти решение."},
    {"word": "environment", "transcription": "/ɪnˈvaɪrənmənt/", "translation": "окружающая среда, обстановка", "part_of_speech": "noun", "example": "We must protect the environment.", "example_ru": "Мы должны защищать окружающую среду."},
    {"word": "manage", "transcription": "/ˈmænɪdʒ/", "translation": "управлять, справляться", "part_of_speech": "verb", "example": "Can you manage the project?", "example_ru": "Ты можешь управлять проектом?"},
    {"word": "support", "transcription": "/səˈpɔːrt/", "translation": "поддержка; поддерживать", "part_of_speech": "noun/verb", "example": "Thank you for your support.", "example_ru": "Спасибо за вашу поддержку."},
    {"word": "behaviour", "transcription": "/bɪˈheɪvjər/", "translation": "поведение", "part_of_speech": "noun", "example": "His behaviour was very strange.", "example_ru": "Его поведение было очень странным."},
    {"word": "affect", "transcription": "/əˈfekt/", "translation": "влиять на, затрагивать", "part_of_speech": "verb", "example": "Stress can affect your health.", "example_ru": "Стресс может влиять на здоровье."},
    {"word": "recently", "transcription": "/ˈriːsntli/", "translation": "недавно, в последнее время", "part_of_speech": "adverb", "example": "I recently moved to a new city.", "example_ru": "Я недавно переехал в новый город."},
    {"word": "reduce", "transcription": "/rɪˈdjuːs/", "translation": "сокращать, уменьшать", "part_of_speech": "verb", "example": "We need to reduce costs.", "example_ru": "Нам нужно сократить расходы."},
    {"word": "mention", "transcription": "/ˈmenʃən/", "translation": "упоминать; упоминание", "part_of_speech": "verb/noun", "example": "He didn't mention the problem.", "example_ru": "Он не упомянул проблему."},
    {"word": "involve", "transcription": "/ɪnˈvɒlv/", "translation": "включать, вовлекать", "part_of_speech": "verb", "example": "The project involves a lot of work.", "example_ru": "Проект предполагает много работы."},
    {"word": "therefore", "transcription": "/ˈðeərfɔːr/", "translation": "поэтому, следовательно", "part_of_speech": "adverb", "example": "I was tired, therefore I slept early.", "example_ru": "Я устал, поэтому лёг спать рано."},
    {"word": "according", "transcription": "/əˈkɔːrdɪŋ/", "translation": "согласно, в соответствии", "part_of_speech": "preposition", "example": "According to the report, sales increased.", "example_ru": "Согласно отчёту, продажи выросли."},

    # ── 270 новых слов ────────────────────────────────────────────────────────

    # Общество и жизнь
    {"word": "society", "transcription": "/səˈsaɪəti/", "translation": "общество", "part_of_speech": "noun", "example": "We all have a role in society.", "example_ru": "Мы все играем роль в обществе."},
    {"word": "community", "transcription": "/kəˈmjuːnɪti/", "translation": "сообщество, община", "part_of_speech": "noun", "example": "She works for the local community.", "example_ru": "Она работает для местного сообщества."},
    {"word": "generation", "transcription": "/ˌdʒenəˈreɪʃən/", "translation": "поколение", "part_of_speech": "noun", "example": "Each generation faces new challenges.", "example_ru": "Каждое поколение сталкивается с новыми вызовами."},
    {"word": "culture", "transcription": "/ˈkʌltʃər/", "translation": "культура", "part_of_speech": "noun", "example": "It is important to respect other cultures.", "example_ru": "Важно уважать другие культуры."},
    {"word": "tradition", "transcription": "/trəˈdɪʃən/", "translation": "традиция", "part_of_speech": "noun", "example": "This is an old family tradition.", "example_ru": "Это старая семейная традиция."},
    {"word": "value", "transcription": "/ˈvæljuː/", "translation": "ценность; ценить", "part_of_speech": "noun/verb", "example": "Family is my most important value.", "example_ru": "Семья — моя главная ценность."},
    {"word": "attitude", "transcription": "/ˈætɪtjuːd/", "translation": "отношение, позиция", "part_of_speech": "noun", "example": "Your attitude affects your success.", "example_ru": "Твоё отношение влияет на успех."},
    {"word": "opinion", "transcription": "/əˈpɪnjən/", "translation": "мнение", "part_of_speech": "noun", "example": "In my opinion, this is wrong.", "example_ru": "По моему мнению, это неправильно."},
    {"word": "situation", "transcription": "/ˌsɪtʃuˈeɪʃən/", "translation": "ситуация, положение", "part_of_speech": "noun", "example": "The situation is getting better.", "example_ru": "Ситуация улучшается."},
    {"word": "population", "transcription": "/ˌpɒpjʊˈleɪʃən/", "translation": "население", "part_of_speech": "noun", "example": "The population of this city is growing.", "example_ru": "Население этого города растёт."},
    {"word": "government", "transcription": "/ˈɡʌvənmənt/", "translation": "правительство", "part_of_speech": "noun", "example": "The government announced new laws.", "example_ru": "Правительство объявило о новых законах."},
    {"word": "freedom", "transcription": "/ˈfriːdəm/", "translation": "свобода", "part_of_speech": "noun", "example": "Freedom of speech is important.", "example_ru": "Свобода слова важна."},
    {"word": "justice", "transcription": "/ˈdʒʌstɪs/", "translation": "справедливость, правосудие", "part_of_speech": "noun", "example": "Everyone deserves justice.", "example_ru": "Каждый заслуживает справедливости."},
    {"word": "rights", "transcription": "/raɪts/", "translation": "права", "part_of_speech": "noun", "example": "We must protect human rights.", "example_ru": "Мы должны защищать права человека."},
    {"word": "responsibility", "transcription": "/rɪˌspɒnsɪˈbɪlɪti/", "translation": "ответственность", "part_of_speech": "noun", "example": "It is your responsibility to finish the task.", "example_ru": "Твоя ответственность — завершить задание."},
    {"word": "volunteer", "transcription": "/ˌvɒlənˈtɪər/", "translation": "волонтёр; добровольно участвовать", "part_of_speech": "noun/verb", "example": "She volunteers at the local shelter.", "example_ru": "Она волонтёрит в местном приюте."},
    {"word": "charity", "transcription": "/ˈtʃærɪti/", "translation": "благотворительность", "part_of_speech": "noun", "example": "He donates to charity every year.", "example_ru": "Он каждый год жертвует на благотворительность."},

    # Работа и карьера
    {"word": "profession", "transcription": "/prəˈfeʃən/", "translation": "профессия", "part_of_speech": "noun", "example": "Teaching is a noble profession.", "example_ru": "Преподавание — благородная профессия."},
    {"word": "skills", "transcription": "/skɪlz/", "translation": "навыки, умения", "part_of_speech": "noun", "example": "Good communication skills are essential.", "example_ru": "Навыки общения крайне важны."},
    {"word": "qualification", "transcription": "/ˌkwɒlɪfɪˈkeɪʃən/", "translation": "квалификация, диплом", "part_of_speech": "noun", "example": "Do you have the right qualifications?", "example_ru": "У тебя есть необходимая квалификация?"},
    {"word": "employee", "transcription": "/ɪmˈplɔɪiː/", "translation": "сотрудник, работник", "part_of_speech": "noun", "example": "The company has 200 employees.", "example_ru": "В компании 200 сотрудников."},
    {"word": "employer", "transcription": "/ɪmˈplɔɪər/", "translation": "работодатель", "part_of_speech": "noun", "example": "My employer is very supportive.", "example_ru": "Мой работодатель очень отзывчив."},
    {"word": "promotion", "transcription": "/prəˈməʊʃən/", "translation": "повышение по службе; продвижение", "part_of_speech": "noun", "example": "She got a promotion last month.", "example_ru": "В прошлом месяце её повысили."},
    {"word": "deadline", "transcription": "/ˈdedlaɪn/", "translation": "срок, дедлайн", "part_of_speech": "noun", "example": "The deadline is Friday.", "example_ru": "Дедлайн в пятницу."},
    {"word": "colleague", "transcription": "/ˈkɒliːɡ/", "translation": "коллега", "part_of_speech": "noun", "example": "My colleagues are very helpful.", "example_ru": "Мои коллеги очень отзывчивые."},
    {"word": "industry", "transcription": "/ˈɪndəstri/", "translation": "промышленность, отрасль", "part_of_speech": "noun", "example": "She works in the fashion industry.", "example_ru": "Она работает в индустрии моды."},
    {"word": "technology", "transcription": "/tekˈnɒlədʒi/", "translation": "технология", "part_of_speech": "noun", "example": "Technology changes our lives.", "example_ru": "Технологии меняют нашу жизнь."},
    {"word": "research", "transcription": "/rɪˈsɜːrtʃ/", "translation": "исследование; исследовать", "part_of_speech": "noun/verb", "example": "We need to do more research.", "example_ru": "Нам нужно провести больше исследований."},
    {"word": "project", "transcription": "/ˈprɒdʒekt/", "translation": "проект", "part_of_speech": "noun", "example": "The project was completed on time.", "example_ru": "Проект был завершён вовремя."},
    {"word": "presentation", "transcription": "/ˌprezənˈteɪʃən/", "translation": "презентация", "part_of_speech": "noun", "example": "I have a presentation tomorrow.", "example_ru": "Завтра у меня презентация."},
    {"word": "report", "transcription": "/rɪˈpɔːrt/", "translation": "отчёт, доклад; сообщать", "part_of_speech": "noun/verb", "example": "Please write a report by Monday.", "example_ru": "Пожалуйста, напиши отчёт к понедельнику."},

    # Образование
    {"word": "knowledge", "transcription": "/ˈnɒlɪdʒ/", "translation": "знания, знание", "part_of_speech": "noun", "example": "Knowledge is power.", "example_ru": "Знание — сила."},
    {"word": "education", "transcription": "/ˌedʒʊˈkeɪʃən/", "translation": "образование", "part_of_speech": "noun", "example": "Education is the key to success.", "example_ru": "Образование — ключ к успеху."},
    {"word": "degree", "transcription": "/dɪˈɡriː/", "translation": "степень; диплом", "part_of_speech": "noun", "example": "She has a degree in biology.", "example_ru": "У неё диплом по биологии."},
    {"word": "graduate", "transcription": "/ˈɡrædʒueɪt/", "translation": "выпускник; окончить вуз", "part_of_speech": "noun/verb", "example": "He graduated from university last year.", "example_ru": "В прошлом году он окончил университет."},
    {"word": "essay", "transcription": "/ˈeseɪ/", "translation": "эссе, сочинение", "part_of_speech": "noun", "example": "Write a 500-word essay.", "example_ru": "Напиши эссе на 500 слов."},
    {"word": "assignment", "transcription": "/əˈsaɪnmənt/", "translation": "задание, поручение", "part_of_speech": "noun", "example": "Have you finished the assignment?", "example_ru": "Ты закончил задание?"},
    {"word": "semester", "transcription": "/sɪˈmestər/", "translation": "семестр", "part_of_speech": "noun", "example": "The new semester starts in September.", "example_ru": "Новый семестр начинается в сентябре."},
    {"word": "scholarship", "transcription": "/ˈskɒləʃɪp/", "translation": "стипендия", "part_of_speech": "noun", "example": "She won a scholarship to study abroad.", "example_ru": "Она получила стипендию на учёбу за рубежом."},
    {"word": "scientific", "transcription": "/ˌsaɪənˈtɪfɪk/", "translation": "научный", "part_of_speech": "adjective", "example": "This is a scientific study.", "example_ru": "Это научное исследование."},
    {"word": "theory", "transcription": "/ˈθɪəri/", "translation": "теория", "part_of_speech": "noun", "example": "This is just a theory.", "example_ru": "Это всего лишь теория."},
    {"word": "prove", "transcription": "/pruːv/", "translation": "доказывать", "part_of_speech": "verb", "example": "Can you prove your point?", "example_ru": "Ты можешь доказать свою точку зрения?"},
    {"word": "argument", "transcription": "/ˈɑːrɡjʊmənt/", "translation": "аргумент; спор", "part_of_speech": "noun", "example": "He made a strong argument.", "example_ru": "Он привёл убедительный аргумент."},

    # Здоровье и образ жизни
    {"word": "lifestyle", "transcription": "/ˈlaɪfstaɪl/", "translation": "образ жизни", "part_of_speech": "noun", "example": "A healthy lifestyle is important.", "example_ru": "Здоровый образ жизни важен."},
    {"word": "mental", "transcription": "/ˈmentəl/", "translation": "умственный, психический", "part_of_speech": "adjective", "example": "Mental health matters too.", "example_ru": "Психическое здоровье тоже важно."},
    {"word": "physical", "transcription": "/ˈfɪzɪkəl/", "translation": "физический", "part_of_speech": "adjective", "example": "Regular physical activity is good for you.", "example_ru": "Регулярная физическая активность полезна для тебя."},
    {"word": "diet", "transcription": "/ˈdaɪət/", "translation": "диета, питание", "part_of_speech": "noun", "example": "A balanced diet keeps you healthy.", "example_ru": "Сбалансированная диета поддерживает здоровье."},
    {"word": "stress", "transcription": "/stres/", "translation": "стресс; испытывать стресс", "part_of_speech": "noun/verb", "example": "Too much work causes stress.", "example_ru": "Слишком много работы вызывает стресс."},
    {"word": "relaxation", "transcription": "/ˌriːlækˈseɪʃən/", "translation": "расслабление, отдых", "part_of_speech": "noun", "example": "Yoga is great for relaxation.", "example_ru": "Йога отлично подходит для расслабления."},
    {"word": "habit", "transcription": "/ˈhæbɪt/", "translation": "привычка", "part_of_speech": "noun", "example": "Good habits lead to success.", "example_ru": "Хорошие привычки ведут к успеху."},
    {"word": "addiction", "transcription": "/əˈdɪkʃən/", "translation": "зависимость", "part_of_speech": "noun", "example": "Social media addiction is common today.", "example_ru": "Зависимость от соцсетей распространена сегодня."},
    {"word": "surgery", "transcription": "/ˈsɜːrdʒəri/", "translation": "хирургия, операция", "part_of_speech": "noun", "example": "He had surgery last week.", "example_ru": "На прошлой неделе ему сделали операцию."},
    {"word": "treatment", "transcription": "/ˈtriːtmənt/", "translation": "лечение, обращение", "part_of_speech": "noun", "example": "The treatment is working well.", "example_ru": "Лечение хорошо действует."},
    {"word": "symptom", "transcription": "/ˈsɪmptəm/", "translation": "симптом", "part_of_speech": "noun", "example": "What are the symptoms?", "example_ru": "Каковы симптомы?"},
    {"word": "recovery", "transcription": "/rɪˈkʌvəri/", "translation": "выздоровление, восстановление", "part_of_speech": "noun", "example": "She made a full recovery.", "example_ru": "Она полностью выздоровела."},

    # Природа и экология
    {"word": "climate", "transcription": "/ˈklaɪmɪt/", "translation": "климат", "part_of_speech": "noun", "example": "Climate change is a global issue.", "example_ru": "Изменение климата — глобальная проблема."},
    {"word": "natural", "transcription": "/ˈnætʃərəl/", "translation": "природный, естественный", "part_of_speech": "adjective", "example": "We use only natural ingredients.", "example_ru": "Мы используем только натуральные ингредиенты."},
    {"word": "disaster", "transcription": "/dɪˈzɑːstər/", "translation": "катастрофа, бедствие", "part_of_speech": "noun", "example": "The earthquake was a natural disaster.", "example_ru": "Землетрясение было стихийным бедствием."},
    {"word": "species", "transcription": "/ˈspiːʃiːz/", "translation": "вид (животных/растений)", "part_of_speech": "noun", "example": "Many species are endangered.", "example_ru": "Многие виды находятся под угрозой исчезновения."},
    {"word": "wildlife", "transcription": "/ˈwaɪldlaɪf/", "translation": "дикая природа", "part_of_speech": "noun", "example": "We must protect wildlife.", "example_ru": "Мы должны защищать дикую природу."},
    {"word": "landscape", "transcription": "/ˈlændskeɪp/", "translation": "пейзаж, ландшафт", "part_of_speech": "noun", "example": "The landscape is beautiful here.", "example_ru": "Здесь красивый пейзаж."},
    {"word": "ocean", "transcription": "/ˈəʊʃən/", "translation": "океан", "part_of_speech": "noun", "example": "Plastic pollutes the ocean.", "example_ru": "Пластик загрязняет океан."},
    {"word": "atmosphere", "transcription": "/ˈætməsfɪər/", "translation": "атмосфера", "part_of_speech": "noun", "example": "Carbon dioxide damages the atmosphere.", "example_ru": "Углекислый газ разрушает атмосферу."},
    {"word": "resource", "transcription": "/rɪˈzɔːrs/", "translation": "ресурс", "part_of_speech": "noun", "example": "We must use resources wisely.", "example_ru": "Мы должны разумно использовать ресурсы."},
    {"word": "waste", "transcription": "/weɪst/", "translation": "отходы; тратить впустую", "part_of_speech": "noun/verb", "example": "Don't waste food.", "example_ru": "Не выбрасывай еду впустую."},
    {"word": "recycle", "transcription": "/ˌriːˈsaɪkəl/", "translation": "перерабатывать (отходы)", "part_of_speech": "verb", "example": "We should recycle more.", "example_ru": "Нам следует больше перерабатывать отходы."},
    {"word": "sustainable", "transcription": "/səˈsteɪnəbəl/", "translation": "устойчивый, экологичный", "part_of_speech": "adjective", "example": "We need sustainable energy sources.", "example_ru": "Нам нужны устойчивые источники энергии."},

    # Технологии и медиа
    {"word": "internet", "transcription": "/ˈɪntənet/", "translation": "интернет", "part_of_speech": "noun", "example": "I use the internet every day.", "example_ru": "Я использую интернет каждый день."},
    {"word": "social media", "transcription": "/ˌsəʊʃəl ˈmiːdiə/", "translation": "социальные сети", "part_of_speech": "noun", "example": "Social media can be addictive.", "example_ru": "Социальные сети могут вызывать зависимость."},
    {"word": "application", "transcription": "/ˌæplɪˈkeɪʃən/", "translation": "приложение; заявка", "part_of_speech": "noun", "example": "Download the application on your phone.", "example_ru": "Скачай приложение на телефон."},
    {"word": "device", "transcription": "/dɪˈvaɪs/", "translation": "устройство, прибор", "part_of_speech": "noun", "example": "What device do you use?", "example_ru": "Какое устройство ты используешь?"},
    {"word": "screen", "transcription": "/skriːn/", "translation": "экран; просматривать", "part_of_speech": "noun/verb", "example": "My screen is broken.", "example_ru": "Мой экран сломан."},
    {"word": "network", "transcription": "/ˈnetwɜːrk/", "translation": "сеть; налаживать связи", "part_of_speech": "noun/verb", "example": "We need a stronger network.", "example_ru": "Нам нужна более сильная сеть."},
    {"word": "digital", "transcription": "/ˈdɪdʒɪtəl/", "translation": "цифровой", "part_of_speech": "adjective", "example": "We live in a digital age.", "example_ru": "Мы живём в цифровую эпоху."},
    {"word": "online", "transcription": "/ˈɒnlaɪn/", "translation": "онлайн, в интернете", "part_of_speech": "adjective/adverb", "example": "I shop online every week.", "example_ru": "Я делаю покупки онлайн каждую неделю."},
    {"word": "software", "transcription": "/ˈsɒftweər/", "translation": "программное обеспечение", "part_of_speech": "noun", "example": "Update your software regularly.", "example_ru": "Регулярно обновляй программное обеспечение."},
    {"word": "data", "transcription": "/ˈdeɪtə/", "translation": "данные", "part_of_speech": "noun", "example": "We collect a lot of data.", "example_ru": "Мы собираем много данных."},
    {"word": "password", "transcription": "/ˈpɑːswɜːrd/", "translation": "пароль", "part_of_speech": "noun", "example": "Use a strong password.", "example_ru": "Используй надёжный пароль."},
    {"word": "download", "transcription": "/ˈdaʊnləʊd/", "translation": "скачивать, загружать", "part_of_speech": "verb/noun", "example": "Download the file from the website.", "example_ru": "Скачай файл с сайта."},
    {"word": "upload", "transcription": "/ˈʌpləʊd/", "translation": "загружать (в интернет)", "part_of_speech": "verb/noun", "example": "Upload the photo to your profile.", "example_ru": "Загрузи фото в профиль."},
    {"word": "search", "transcription": "/sɜːrtʃ/", "translation": "искать; поиск", "part_of_speech": "verb/noun", "example": "Search for the answer online.", "example_ru": "Поищи ответ онлайн."},

    # Путешествия
    {"word": "destination", "transcription": "/ˌdestɪˈneɪʃən/", "translation": "пункт назначения", "part_of_speech": "noun", "example": "Paris is my dream destination.", "example_ru": "Париж — моё место мечты."},
    {"word": "passport", "transcription": "/ˈpɑːspɔːrt/", "translation": "паспорт", "part_of_speech": "noun", "example": "Don't forget your passport!", "example_ru": "Не забудь паспорт!"},
    {"word": "luggage", "transcription": "/ˈlʌɡɪdʒ/", "translation": "багаж", "part_of_speech": "noun", "example": "I have too much luggage.", "example_ru": "У меня слишком много багажа."},
    {"word": "reservation", "transcription": "/ˌrezəˈveɪʃən/", "translation": "бронь, резервация", "part_of_speech": "noun", "example": "I made a reservation for two.", "example_ru": "Я забронировал столик на двоих."},
    {"word": "departure", "transcription": "/dɪˈpɑːrtʃər/", "translation": "отправление, отъезд", "part_of_speech": "noun", "example": "What time is the departure?", "example_ru": "В какое время отправление?"},
    {"word": "arrival", "transcription": "/əˈraɪvəl/", "translation": "прибытие, приезд", "part_of_speech": "noun", "example": "The arrival is at 8 pm.", "example_ru": "Прибытие в 20:00."},
    {"word": "customs", "transcription": "/ˈkʌstəmz/", "translation": "таможня", "part_of_speech": "noun", "example": "You must go through customs.", "example_ru": "Ты должен пройти таможню."},
    {"word": "currency", "transcription": "/ˈkʌrənsi/", "translation": "валюта", "part_of_speech": "noun", "example": "What currency do they use?", "example_ru": "Какую валюту они используют?"},
    {"word": "sightseeing", "transcription": "/ˈsaɪtsiːɪŋ/", "translation": "осмотр достопримечательностей", "part_of_speech": "noun", "example": "We spent the day sightseeing.", "example_ru": "Мы провели день, осматривая достопримечательности."},
    {"word": "accommodation", "transcription": "/əˌkɒməˈdeɪʃən/", "translation": "жильё, проживание", "part_of_speech": "noun", "example": "We need to book accommodation.", "example_ru": "Нам нужно забронировать жильё."},
    {"word": "foreign", "transcription": "/ˈfɒrɪn/", "translation": "иностранный, зарубежный", "part_of_speech": "adjective", "example": "She speaks three foreign languages.", "example_ru": "Она говорит на трёх иностранных языках."},

    # Глаголы
    {"word": "achieve", "transcription": "/əˈtʃiːv/", "translation": "достигать", "part_of_speech": "verb", "example": "You can achieve anything with hard work.", "example_ru": "Упорным трудом можно достичь всего."},
    {"word": "establish", "transcription": "/ɪˈstæblɪʃ/", "translation": "основывать, устанавливать", "part_of_speech": "verb", "example": "They established a new company.", "example_ru": "Они основали новую компанию."},
    {"word": "maintain", "transcription": "/meɪnˈteɪn/", "translation": "поддерживать, сохранять", "part_of_speech": "verb", "example": "Maintain a positive attitude.", "example_ru": "Поддерживай позитивный настрой."},
    {"word": "obtain", "transcription": "/əbˈteɪn/", "translation": "получать, добывать", "part_of_speech": "verb", "example": "How did you obtain this information?", "example_ru": "Как ты получил эту информацию?"},
    {"word": "express", "transcription": "/ɪkˈspres/", "translation": "выражать; экспресс", "part_of_speech": "verb/adjective", "example": "Try to express your feelings.", "example_ru": "Попробуй выразить свои чувства."},
    {"word": "assume", "transcription": "/əˈsjuːm/", "translation": "предполагать, принимать", "part_of_speech": "verb", "example": "Don't assume anything.", "example_ru": "Ничего не предполагай."},
    {"word": "claim", "transcription": "/kleɪm/", "translation": "утверждать; требование", "part_of_speech": "verb/noun", "example": "He claims he is innocent.", "example_ru": "Он утверждает, что невиновен."},
    {"word": "confirm", "transcription": "/kənˈfɜːrm/", "translation": "подтверждать", "part_of_speech": "verb", "example": "Please confirm your booking.", "example_ru": "Пожалуйста, подтверди бронь."},
    {"word": "enable", "transcription": "/ɪˈneɪbəl/", "translation": "позволять, давать возможность", "part_of_speech": "verb", "example": "Technology enables remote work.", "example_ru": "Технологии позволяют работать удалённо."},
    {"word": "encounter", "transcription": "/ɪnˈkaʊntər/", "translation": "встречать, сталкиваться", "part_of_speech": "verb/noun", "example": "I encountered a problem today.", "example_ru": "Сегодня я столкнулся с проблемой."},
    {"word": "encourage", "transcription": "/ɪnˈkʌrɪdʒ/", "translation": "поощрять, вдохновлять", "part_of_speech": "verb", "example": "Teachers should encourage students.", "example_ru": "Учителя должны поощрять студентов."},
    {"word": "focus", "transcription": "/ˈfəʊkəs/", "translation": "фокусироваться; фокус", "part_of_speech": "verb/noun", "example": "Focus on one thing at a time.", "example_ru": "Фокусируйся на одном деле за раз."},
    {"word": "identify", "transcription": "/aɪˈdentɪfaɪ/", "translation": "определять, идентифицировать", "part_of_speech": "verb", "example": "Can you identify the problem?", "example_ru": "Ты можешь определить проблему?"},
    {"word": "indicate", "transcription": "/ˈɪndɪkeɪt/", "translation": "указывать, показывать", "part_of_speech": "verb", "example": "The data indicates a trend.", "example_ru": "Данные указывают на тенденцию."},
    {"word": "increase", "transcription": "/ɪnˈkriːs/", "translation": "увеличивать(ся); рост", "part_of_speech": "verb/noun", "example": "Sales increased by 20%.", "example_ru": "Продажи выросли на 20%."},
    {"word": "decrease", "transcription": "/dɪˈkriːs/", "translation": "уменьшать(ся); снижение", "part_of_speech": "verb/noun", "example": "Prices decreased last year.", "example_ru": "Цены снизились в прошлом году."},
    {"word": "tend", "transcription": "/tend/", "translation": "иметь тенденцию, склоняться", "part_of_speech": "verb", "example": "People tend to resist change.", "example_ru": "Люди склонны сопротивляться переменам."},
    {"word": "notice", "transcription": "/ˈnəʊtɪs/", "translation": "замечать; уведомление", "part_of_speech": "verb/noun", "example": "Did you notice anything strange?", "example_ru": "Ты заметил что-нибудь странное?"},
    {"word": "prevent", "transcription": "/prɪˈvent/", "translation": "предотвращать, мешать", "part_of_speech": "verb", "example": "Exercise can prevent illness.", "example_ru": "Физические упражнения могут предотвратить болезнь."},
    {"word": "protect", "transcription": "/prəˈtekt/", "translation": "защищать", "part_of_speech": "verb", "example": "We must protect children.", "example_ru": "Мы должны защищать детей."},
    {"word": "reflect", "transcription": "/rɪˈflekt/", "translation": "отражать; размышлять", "part_of_speech": "verb", "example": "Take time to reflect on your choices.", "example_ru": "Найди время подумать о своих решениях."},
    {"word": "rely", "transcription": "/rɪˈlaɪ/", "translation": "полагаться, зависеть", "part_of_speech": "verb", "example": "You can rely on me.", "example_ru": "Ты можешь на меня положиться."},
    {"word": "succeed", "transcription": "/səkˈsiːd/", "translation": "добиваться успеха", "part_of_speech": "verb", "example": "Work hard and you will succeed.", "example_ru": "Трудись — и ты добьёшься успеха."},

    # Прилагательные
    {"word": "accurate", "transcription": "/ˈækjʊrɪt/", "translation": "точный, правильный", "part_of_speech": "adjective", "example": "The report must be accurate.", "example_ru": "Отчёт должен быть точным."},
    {"word": "appropriate", "transcription": "/əˈprəʊpriɪt/", "translation": "подходящий, уместный", "part_of_speech": "adjective", "example": "Is this behaviour appropriate?", "example_ru": "Уместно ли такое поведение?"},
    {"word": "complex", "transcription": "/ˈkɒmpleks/", "translation": "сложный, комплексный", "part_of_speech": "adjective", "example": "This is a complex issue.", "example_ru": "Это сложный вопрос."},
    {"word": "consistent", "transcription": "/kənˈsɪstənt/", "translation": "последовательный, постоянный", "part_of_speech": "adjective", "example": "Be consistent in your efforts.", "example_ru": "Будь последовательным в своих усилиях."},
    {"word": "creative", "transcription": "/kriˈeɪtɪv/", "translation": "творческий, креативный", "part_of_speech": "adjective", "example": "She is a very creative person.", "example_ru": "Она очень творческий человек."},
    {"word": "critical", "transcription": "/ˈkrɪtɪkəl/", "translation": "критический, важный", "part_of_speech": "adjective", "example": "This is a critical moment.", "example_ru": "Это критический момент."},
    {"word": "current", "transcription": "/ˈkʌrənt/", "translation": "текущий, нынешний", "part_of_speech": "adjective", "example": "What is the current situation?", "example_ru": "Какова текущая ситуация?"},
    {"word": "effective", "transcription": "/ɪˈfektɪv/", "translation": "эффективный, действенный", "part_of_speech": "adjective", "example": "This method is very effective.", "example_ru": "Этот метод очень эффективен."},
    {"word": "efficient", "transcription": "/ɪˈfɪʃənt/", "translation": "эффективный, продуктивный", "part_of_speech": "adjective", "example": "We need an efficient system.", "example_ru": "Нам нужна эффективная система."},
    {"word": "essential", "transcription": "/ɪˈsenʃəl/", "translation": "существенный, необходимый", "part_of_speech": "adjective", "example": "Water is essential for life.", "example_ru": "Вода необходима для жизни."},
    {"word": "flexible", "transcription": "/ˈfleksɪbəl/", "translation": "гибкий", "part_of_speech": "adjective", "example": "Be flexible with your plans.", "example_ru": "Будь гибким в своих планах."},
    {"word": "global", "transcription": "/ˈɡləʊbəl/", "translation": "глобальный, мировой", "part_of_speech": "adjective", "example": "Climate change is a global problem.", "example_ru": "Изменение климата — глобальная проблема."},
    {"word": "logical", "transcription": "/ˈlɒdʒɪkəl/", "translation": "логичный", "part_of_speech": "adjective", "example": "That is a logical conclusion.", "example_ru": "Это логичный вывод."},
    {"word": "obvious", "transcription": "/ˈɒbviəs/", "translation": "очевидный", "part_of_speech": "adjective", "example": "The answer is obvious.", "example_ru": "Ответ очевиден."},
    {"word": "ordinary", "transcription": "/ˈɔːrdɪnəri/", "translation": "обычный, рядовой", "part_of_speech": "adjective", "example": "It was just an ordinary day.", "example_ru": "Это был самый обычный день."},
    {"word": "particular", "transcription": "/pəˈtɪkjʊlər/", "translation": "конкретный, особый", "part_of_speech": "adjective", "example": "Is there a particular reason?", "example_ru": "Есть ли конкретная причина?"},
    {"word": "personal", "transcription": "/ˈpɜːrsənəl/", "translation": "личный, персональный", "part_of_speech": "adjective", "example": "This is a personal matter.", "example_ru": "Это личное дело."},
    {"word": "positive", "transcription": "/ˈpɒzɪtɪv/", "translation": "положительный, позитивный", "part_of_speech": "adjective", "example": "Stay positive!", "example_ru": "Оставайся позитивным!"},
    {"word": "negative", "transcription": "/ˈneɡətɪv/", "translation": "отрицательный, негативный", "part_of_speech": "adjective", "example": "Avoid negative thinking.", "example_ru": "Избегай негативного мышления."},
    {"word": "practical", "transcription": "/ˈpræktɪkəl/", "translation": "практичный, практический", "part_of_speech": "adjective", "example": "Give me a practical example.", "example_ru": "Приведи мне практический пример."},
    {"word": "professional", "transcription": "/prəˈfeʃənəl/", "translation": "профессиональный", "part_of_speech": "adjective/noun", "example": "She is a true professional.", "example_ru": "Она настоящий профессионал."},
    {"word": "realistic", "transcription": "/ˌrɪəˈlɪstɪk/", "translation": "реалистичный", "part_of_speech": "adjective", "example": "Be realistic about your goals.", "example_ru": "Будь реалистичен в своих целях."},
    {"word": "reasonable", "transcription": "/ˈriːzənəbəl/", "translation": "разумный, приемлемый", "part_of_speech": "adjective", "example": "That is a reasonable price.", "example_ru": "Это приемлемая цена."},
    {"word": "responsible", "transcription": "/rɪˈspɒnsɪbəl/", "translation": "ответственный", "part_of_speech": "adjective", "example": "Be responsible for your actions.", "example_ru": "Неси ответственность за свои действия."},
    {"word": "sensitive", "transcription": "/ˈsensɪtɪv/", "translation": "чувствительный, чуткий", "part_of_speech": "adjective", "example": "She is a sensitive person.", "example_ru": "Она чуткий человек."},
    {"word": "typical", "transcription": "/ˈtɪpɪkəl/", "translation": "типичный", "part_of_speech": "adjective", "example": "This is typical weather for autumn.", "example_ru": "Это типичная погода для осени."},
    {"word": "unique", "transcription": "/juːˈniːk/", "translation": "уникальный", "part_of_speech": "adjective", "example": "Every person is unique.", "example_ru": "Каждый человек уникален."},

    # Наречия и связки
    {"word": "generally", "transcription": "/ˈdʒenərəli/", "translation": "вообще, в целом", "part_of_speech": "adverb", "example": "People generally like music.", "example_ru": "В целом люди любят музыку."},
    {"word": "particularly", "transcription": "/pəˈtɪkjʊləli/", "translation": "особенно, в частности", "part_of_speech": "adverb", "example": "I particularly like jazz.", "example_ru": "Мне особенно нравится джаз."},
    {"word": "mainly", "transcription": "/ˈmeɪnli/", "translation": "главным образом, преимущественно", "part_of_speech": "adverb", "example": "The diet consists mainly of rice.", "example_ru": "Диета состоит главным образом из риса."},
    {"word": "largely", "transcription": "/ˈlɑːrdʒli/", "translation": "в значительной мере, по большей части", "part_of_speech": "adverb", "example": "The project was largely successful.", "example_ru": "Проект в значительной мере удался."},
    {"word": "approximately", "transcription": "/əˈprɒksɪmətli/", "translation": "приблизительно, примерно", "part_of_speech": "adverb", "example": "It takes approximately two hours.", "example_ru": "Это занимает примерно два часа."},
    {"word": "gradually", "transcription": "/ˈɡrædʒuəli/", "translation": "постепенно", "part_of_speech": "adverb", "example": "His English improved gradually.", "example_ru": "Его английский постепенно улучшался."},
    {"word": "immediately", "transcription": "/ɪˈmiːdiətli/", "translation": "немедленно, сразу", "part_of_speech": "adverb", "example": "Call me immediately.", "example_ru": "Позвони мне немедленно."},
    {"word": "eventually", "transcription": "/ɪˈventʃuəli/", "translation": "в конце концов, в итоге", "part_of_speech": "adverb", "example": "Eventually, she found a solution.", "example_ru": "В конце концов она нашла решение."},
    {"word": "initially", "transcription": "/ɪˈnɪʃəli/", "translation": "изначально, сначала", "part_of_speech": "adverb", "example": "Initially, I was nervous.", "example_ru": "Изначально я нервничал."},
    {"word": "currently", "transcription": "/ˈkʌrəntli/", "translation": "в настоящее время, сейчас", "part_of_speech": "adverb", "example": "I am currently studying English.", "example_ru": "В настоящее время я изучаю английский."},
    {"word": "previously", "transcription": "/ˈpriːviəsli/", "translation": "ранее, прежде", "part_of_speech": "adverb", "example": "I previously worked in London.", "example_ru": "Ранее я работал в Лондоне."},
    {"word": "unfortunately", "transcription": "/ʌnˈfɔːrtʃənɪtli/", "translation": "к сожалению", "part_of_speech": "adverb", "example": "Unfortunately, I can't come.", "example_ru": "К сожалению, я не могу прийти."},
    {"word": "fortunately", "transcription": "/ˈfɔːrtʃənɪtli/", "translation": "к счастью", "part_of_speech": "adverb", "example": "Fortunately, no one was hurt.", "example_ru": "К счастью, никто не пострадал."},
    {"word": "however", "transcription": "/haʊˈevər/", "translation": "однако, тем не менее", "part_of_speech": "adverb", "example": "It is difficult. However, it is possible.", "example_ru": "Это трудно. Однако это возможно."},
    {"word": "furthermore", "transcription": "/ˌfɜːðəˈmɔːr/", "translation": "кроме того, более того", "part_of_speech": "adverb", "example": "Furthermore, the cost is too high.", "example_ru": "Кроме того, стоимость слишком высока."},
    {"word": "nevertheless", "transcription": "/ˌnevəðəˈles/", "translation": "тем не менее, всё же", "part_of_speech": "adverb", "example": "It was hard. Nevertheless, we succeeded.", "example_ru": "Было трудно. Тем не менее мы справились."},
    {"word": "otherwise", "transcription": "/ˈʌðəwaɪz/", "translation": "иначе, в противном случае", "part_of_speech": "adverb", "example": "Hurry up, otherwise we'll be late.", "example_ru": "Поторопись, иначе опоздаем."},
    {"word": "meanwhile", "transcription": "/ˈmiːnwaɪl/", "translation": "тем временем", "part_of_speech": "adverb", "example": "Meanwhile, cook the vegetables.", "example_ru": "Тем временем приготовь овощи."},

    # Существительные — абстрактные понятия
    {"word": "ability", "transcription": "/əˈbɪlɪti/", "translation": "способность, умение", "part_of_speech": "noun", "example": "She has a natural ability for music.", "example_ru": "У неё природная способность к музыке."},
    {"word": "achievement", "transcription": "/əˈtʃiːvmənt/", "translation": "достижение", "part_of_speech": "noun", "example": "Winning the prize was a great achievement.", "example_ru": "Выиграть приз было большим достижением."},
    {"word": "advantage", "transcription": "/ədˈvɑːntɪdʒ/", "translation": "преимущество", "part_of_speech": "noun", "example": "What are the advantages of this plan?", "example_ru": "Каковы преимущества этого плана?"},
    {"word": "disadvantage", "transcription": "/ˌdɪsədˈvɑːntɪdʒ/", "translation": "недостаток, минус", "part_of_speech": "noun", "example": "Every plan has some disadvantages.", "example_ru": "В каждом плане есть свои недостатки."},
    {"word": "choice", "transcription": "/tʃɔɪs/", "translation": "выбор", "part_of_speech": "noun", "example": "It is your choice.", "example_ru": "Это твой выбор."},
    {"word": "decision", "transcription": "/dɪˈsɪʒən/", "translation": "решение", "part_of_speech": "noun", "example": "It was a difficult decision.", "example_ru": "Это было трудное решение."},
    {"word": "demand", "transcription": "/dɪˈmɑːnd/", "translation": "спрос; требовать", "part_of_speech": "noun/verb", "example": "There is high demand for this product.", "example_ru": "На этот товар большой спрос."},
    {"word": "impact", "transcription": "/ˈɪmpækt/", "translation": "влияние, воздействие", "part_of_speech": "noun", "example": "The decision had a big impact.", "example_ru": "Решение оказало большое влияние."},
    {"word": "lack", "transcription": "/læk/", "translation": "нехватка; не хватать", "part_of_speech": "noun/verb", "example": "There is a lack of funding.", "example_ru": "Не хватает финансирования."},
    {"word": "process", "transcription": "/ˈprəʊses/", "translation": "процесс; обрабатывать", "part_of_speech": "noun/verb", "example": "Learning is a slow process.", "example_ru": "Обучение — медленный процесс."},
    {"word": "progress", "transcription": "/ˈprəʊɡres/", "translation": "прогресс; прогрессировать", "part_of_speech": "noun/verb", "example": "You are making good progress.", "example_ru": "Ты делаешь хорошие успехи."},
    {"word": "range", "transcription": "/reɪndʒ/", "translation": "диапазон, ассортимент", "part_of_speech": "noun", "example": "We offer a wide range of products.", "example_ru": "Мы предлагаем широкий ассортимент товаров."},
    {"word": "rate", "transcription": "/reɪt/", "translation": "скорость; ставка; оценивать", "part_of_speech": "noun/verb", "example": "The crime rate is falling.", "example_ru": "Уровень преступности снижается."},
    {"word": "stage", "transcription": "/steɪdʒ/", "translation": "этап, стадия; сцена", "part_of_speech": "noun", "example": "We are at an early stage.", "example_ru": "Мы находимся на раннем этапе."},
    {"word": "system", "transcription": "/ˈsɪstəm/", "translation": "система", "part_of_speech": "noun", "example": "The system needs improvement.", "example_ru": "Система нуждается в улучшении."},

    # ── дополнительные слова B1 ───────────────────────────────────────────────

    # Экономика и деньги
    {"word": "economy", "transcription": "/ɪˈkɒnəmi/", "translation": "экономика", "part_of_speech": "noun", "example": "The economy is growing steadily.", "example_ru": "Экономика стабильно растёт."},
    {"word": "income", "transcription": "/ˈɪnkʌm/", "translation": "доход", "part_of_speech": "noun", "example": "His income increased last year.", "example_ru": "В прошлом году его доход вырос."},
    {"word": "budget", "transcription": "/ˈbʌdʒɪt/", "translation": "бюджет", "part_of_speech": "noun", "example": "We need to stick to the budget.", "example_ru": "Нам нужно придерживаться бюджета."},
    {"word": "investment", "transcription": "/ɪnˈvestmənt/", "translation": "инвестиция, вложение", "part_of_speech": "noun", "example": "Education is a good investment.", "example_ru": "Образование — хорошая инвестиция."},
    {"word": "profit", "transcription": "/ˈprɒfɪt/", "translation": "прибыль", "part_of_speech": "noun", "example": "The company made a large profit.", "example_ru": "Компания получила большую прибыль."},
    {"word": "tax", "transcription": "/tæks/", "translation": "налог; облагать налогом", "part_of_speech": "noun/verb", "example": "Everyone must pay taxes.", "example_ru": "Все должны платить налоги."},
    {"word": "loan", "transcription": "/ləʊn/", "translation": "заём, кредит", "part_of_speech": "noun", "example": "He took out a bank loan.", "example_ru": "Он взял банковский кредит."},
    {"word": "debt", "transcription": "/det/", "translation": "долг", "part_of_speech": "noun", "example": "She paid off all her debts.", "example_ru": "Она выплатила все долги."},
    {"word": "poverty", "transcription": "/ˈpɒvəti/", "translation": "бедность, нищета", "part_of_speech": "noun", "example": "Poverty is a serious global issue.", "example_ru": "Бедность — серьёзная глобальная проблема."},
    {"word": "wealth", "transcription": "/welθ/", "translation": "богатство", "part_of_speech": "noun", "example": "Health is more important than wealth.", "example_ru": "Здоровье важнее богатства."},

    # Коммуникация
    {"word": "communicate", "transcription": "/kəˈmjuːnɪkeɪt/", "translation": "общаться, передавать", "part_of_speech": "verb", "example": "It is important to communicate clearly.", "example_ru": "Важно общаться чётко."},
    {"word": "discuss", "transcription": "/dɪˈskʌs/", "translation": "обсуждать", "part_of_speech": "verb", "example": "Let's discuss the plan.", "example_ru": "Давай обсудим план."},
    {"word": "debate", "transcription": "/dɪˈbeɪt/", "translation": "дебаты; дискутировать", "part_of_speech": "noun/verb", "example": "The debate was very heated.", "example_ru": "Дебаты были очень жаркими."},
    {"word": "negotiate", "transcription": "/nɪˈɡəʊʃieɪt/", "translation": "переговаривать, договариваться", "part_of_speech": "verb", "example": "They negotiated a better deal.", "example_ru": "Они договорились о лучших условиях."},
    {"word": "persuade", "transcription": "/pəˈsweɪd/", "translation": "убеждать", "part_of_speech": "verb", "example": "Can you persuade him to join us?", "example_ru": "Ты можешь убедить его присоединиться?"},
    {"word": "criticise", "transcription": "/ˈkrɪtɪsaɪz/", "translation": "критиковать", "part_of_speech": "verb", "example": "Don't criticise without offering solutions.", "example_ru": "Не критикуй, не предлагая решений."},
    {"word": "praise", "transcription": "/preɪz/", "translation": "хвалить; похвала", "part_of_speech": "verb/noun", "example": "The teacher praised his work.", "example_ru": "Учитель похвалил его работу."},
    {"word": "apologise", "transcription": "/əˈpɒlədʒaɪz/", "translation": "извиняться", "part_of_speech": "verb", "example": "You should apologise for your mistake.", "example_ru": "Тебе следует извиниться за ошибку."},
    {"word": "recommend", "transcription": "/ˌrekəˈmend/", "translation": "рекомендовать", "part_of_speech": "verb", "example": "Can you recommend a good restaurant?", "example_ru": "Ты можешь порекомендовать хороший ресторан?"},
    {"word": "announce", "transcription": "/əˈnaʊns/", "translation": "объявлять, сообщать", "part_of_speech": "verb", "example": "The company announced new plans.", "example_ru": "Компания объявила о новых планах."},

    # Психология и характер
    {"word": "motivation", "transcription": "/ˌməʊtɪˈveɪʃən/", "translation": "мотивация", "part_of_speech": "noun", "example": "What is your motivation?", "example_ru": "Какова твоя мотивация?"},
    {"word": "ambition", "transcription": "/æmˈbɪʃən/", "translation": "амбиция, честолюбие", "part_of_speech": "noun", "example": "She has great ambition.", "example_ru": "У неё большие амбиции."},
    {"word": "curiosity", "transcription": "/ˌkjʊəriˈɒsɪti/", "translation": "любопытство", "part_of_speech": "noun", "example": "Curiosity is key to learning.", "example_ru": "Любопытство — ключ к обучению."},
    {"word": "courage", "transcription": "/ˈkʌrɪdʒ/", "translation": "смелость, храбрость", "part_of_speech": "noun", "example": "It takes courage to change.", "example_ru": "Для перемен нужна смелость."},
    {"word": "determination", "transcription": "/dɪˌtɜːrmɪˈneɪʃən/", "translation": "решимость, настойчивость", "part_of_speech": "noun", "example": "Success requires determination.", "example_ru": "Успех требует настойчивости."},
    {"word": "patience", "transcription": "/ˈpeɪʃəns/", "translation": "терпение", "part_of_speech": "noun", "example": "Patience is a virtue.", "example_ru": "Терпение — это добродетель."},
    {"word": "confidence", "transcription": "/ˈkɒnfɪdəns/", "translation": "уверенность", "part_of_speech": "noun", "example": "Build your confidence step by step.", "example_ru": "Укрепляй уверенность шаг за шагом."},
    {"word": "jealousy", "transcription": "/ˈdʒeləsi/", "translation": "ревность, зависть", "part_of_speech": "noun", "example": "Jealousy destroys relationships.", "example_ru": "Ревность разрушает отношения."},
    {"word": "disappointment", "transcription": "/ˌdɪsəˈpɔɪntmənt/", "translation": "разочарование", "part_of_speech": "noun", "example": "I felt deep disappointment.", "example_ru": "Я почувствовал глубокое разочарование."},
    {"word": "satisfaction", "transcription": "/ˌsætɪsˈfækʃən/", "translation": "удовлетворение", "part_of_speech": "noun", "example": "Job satisfaction is very important.", "example_ru": "Удовлетворение от работы очень важно."},

    # Политика и общество
    {"word": "election", "transcription": "/ɪˈlekʃən/", "translation": "выборы", "part_of_speech": "noun", "example": "Elections are held every four years.", "example_ru": "Выборы проводятся каждые четыре года."},
    {"word": "democracy", "transcription": "/dɪˈmɒkrəsi/", "translation": "демократия", "part_of_speech": "noun", "example": "Democracy gives people a voice.", "example_ru": "Демократия даёт людям голос."},
    {"word": "protest", "transcription": "/ˈprəʊtest/", "translation": "протест; протестовать", "part_of_speech": "noun/verb", "example": "Thousands joined the protest.", "example_ru": "Тысячи людей приняли участие в протесте."},
    {"word": "law", "transcription": "/lɔː/", "translation": "закон", "part_of_speech": "noun", "example": "Everyone must obey the law.", "example_ru": "Все должны соблюдать закон."},
    {"word": "policy", "transcription": "/ˈpɒlɪsi/", "translation": "политика, курс", "part_of_speech": "noun", "example": "The company has a strict privacy policy.", "example_ru": "У компании строгая политика конфиденциальности."},
    {"word": "conflict", "transcription": "/ˈkɒnflɪkt/", "translation": "конфликт", "part_of_speech": "noun", "example": "We must resolve the conflict.", "example_ru": "Мы должны разрешить конфликт."},
    {"word": "crisis", "transcription": "/ˈkraɪsɪs/", "translation": "кризис", "part_of_speech": "noun", "example": "The country faces an economic crisis.", "example_ru": "Страна переживает экономический кризис."},
    {"word": "issue", "transcription": "/ˈɪʃuː/", "translation": "проблема, вопрос; выпускать", "part_of_speech": "noun/verb", "example": "This is a serious issue.", "example_ru": "Это серьёзная проблема."},
    {"word": "debate", "transcription": "/dɪˈbeɪt/", "translation": "дискуссия; обсуждать", "part_of_speech": "noun/verb", "example": "There is a debate about education reform.", "example_ru": "Ведётся дискуссия о реформе образования."},
    {"word": "media", "transcription": "/ˈmiːdiə/", "translation": "средства массовой информации", "part_of_speech": "noun", "example": "The media reported the story.", "example_ru": "СМИ сообщили об этой истории."},

    # Разные полезные слова
    {"word": "approach", "transcription": "/əˈprəʊtʃ/", "translation": "подход; приближаться", "part_of_speech": "noun/verb", "example": "We need a new approach.", "example_ru": "Нам нужен новый подход."},
    {"word": "aspect", "transcription": "/ˈæspekt/", "translation": "аспект, сторона", "part_of_speech": "noun", "example": "Consider every aspect of the problem.", "example_ru": "Рассмотри каждый аспект проблемы."},
    {"word": "category", "transcription": "/ˈkætɪɡəri/", "translation": "категория", "part_of_speech": "noun", "example": "Which category does this belong to?", "example_ru": "К какой категории это относится?"},
    {"word": "concept", "transcription": "/ˈkɒnsept/", "translation": "концепция, понятие", "part_of_speech": "noun", "example": "This is a complex concept.", "example_ru": "Это сложное понятие."},
    {"word": "context", "transcription": "/ˈkɒntekst/", "translation": "контекст", "part_of_speech": "noun", "example": "You need to understand the context.", "example_ru": "Тебе нужно понять контекст."},
    {"word": "factor", "transcription": "/ˈfæktər/", "translation": "фактор", "part_of_speech": "noun", "example": "Price is an important factor.", "example_ru": "Цена — важный фактор."},
    {"word": "feature", "transcription": "/ˈfiːtʃər/", "translation": "особенность, функция", "part_of_speech": "noun", "example": "What are the main features?", "example_ru": "Каковы основные особенности?"},
    {"word": "method", "transcription": "/ˈmeθəd/", "translation": "метод, способ", "part_of_speech": "noun", "example": "Try a different method.", "example_ru": "Попробуй другой метод."},
    {"word": "pattern", "transcription": "/ˈpætərn/", "translation": "шаблон, закономерность", "part_of_speech": "noun", "example": "I see a pattern here.", "example_ru": "Я вижу здесь закономерность."},
    {"word": "principle", "transcription": "/ˈprɪnsɪpəl/", "translation": "принцип", "part_of_speech": "noun", "example": "Stick to your principles.", "example_ru": "Придерживайся своих принципов."},
    {"word": "structure", "transcription": "/ˈstrʌktʃər/", "translation": "структура; строить", "part_of_speech": "noun/verb", "example": "The structure of the essay is clear.", "example_ru": "Структура эссе чёткая."},
    {"word": "evidence", "transcription": "/ˈevɪdəns/", "translation": "доказательство, свидетельство", "part_of_speech": "noun", "example": "There is no evidence for that claim.", "example_ru": "Нет доказательств в пользу этого утверждения."},
    {"word": "effect", "transcription": "/ɪˈfekt/", "translation": "эффект, последствие", "part_of_speech": "noun", "example": "What is the effect of this medicine?", "example_ru": "Каков эффект этого лекарства?"},
    {"word": "cause", "transcription": "/kɔːz/", "translation": "причина; вызывать", "part_of_speech": "noun/verb", "example": "What is the cause of the problem?", "example_ru": "Какова причина проблемы?"},
    {"word": "relationship", "transcription": "/rɪˈleɪʃənʃɪp/", "translation": "отношения, связь", "part_of_speech": "noun", "example": "They have a strong relationship.", "example_ru": "У них крепкие отношения."},
    {"word": "connection", "transcription": "/kəˈnekʃən/", "translation": "связь, соединение", "part_of_speech": "noun", "example": "There is a clear connection here.", "example_ru": "Здесь есть явная связь."},
    {"word": "condition", "transcription": "/kənˈdɪʃən/", "translation": "условие; состояние", "part_of_speech": "noun", "example": "The condition of the car is good.", "example_ru": "Состояние машины хорошее."},
    {"word": "potential", "transcription": "/pəˈtenʃəl/", "translation": "потенциал; потенциальный", "part_of_speech": "noun/adjective", "example": "She has great potential.", "example_ru": "У неё большой потенциал."},
    {"word": "alternative", "transcription": "/ɔːlˈtɜːrnətɪv/", "translation": "альтернатива; альтернативный", "part_of_speech": "noun/adjective", "example": "Is there an alternative solution?", "example_ru": "Есть ли альтернативное решение?"},
    {"word": "priority", "transcription": "/praɪˈɒrɪti/", "translation": "приоритет", "part_of_speech": "noun", "example": "Family is my top priority.", "example_ru": "Семья — мой главный приоритет."},
    {"word": "outcome", "transcription": "/ˈaʊtkʌm/", "translation": "результат, итог", "part_of_speech": "noun", "example": "What was the outcome of the meeting?", "example_ru": "Каков итог встречи?"},
    {"word": "generation", "transcription": "/ˌdʒenəˈreɪʃən/", "translation": "поколение; генерация", "part_of_speech": "noun", "example": "The younger generation uses more technology.", "example_ru": "Молодое поколение больше использует технологии."},
    {"word": "gender", "transcription": "/ˈdʒendər/", "translation": "пол, гендер", "part_of_speech": "noun", "example": "Gender equality is important.", "example_ru": "Гендерное равенство важно."},
    {"word": "minority", "transcription": "/maɪˈnɒrɪti/", "translation": "меньшинство", "part_of_speech": "noun", "example": "Minorities deserve equal rights.", "example_ru": "Меньшинства заслуживают равных прав."},
    {"word": "majority", "transcription": "/məˈdʒɒrɪti/", "translation": "большинство", "part_of_speech": "noun", "example": "The majority voted yes.", "example_ru": "Большинство проголосовало «за»."},
    {"word": "statistics", "transcription": "/stəˈtɪstɪks/", "translation": "статистика", "part_of_speech": "noun", "example": "The statistics are alarming.", "example_ru": "Статистика тревожная."},
    {"word": "survey", "transcription": "/ˈsɜːrveɪ/", "translation": "опрос; обследование", "part_of_speech": "noun/verb", "example": "We conducted a survey.", "example_ru": "Мы провели опрос."},
    {"word": "trend", "transcription": "/trend/", "translation": "тенденция, тренд", "part_of_speech": "noun", "example": "This is a growing trend.", "example_ru": "Это растущая тенденция."},
    {"word": "perspective", "transcription": "/pəˈspektɪv/", "translation": "перспектива, точка зрения", "part_of_speech": "noun", "example": "Consider it from a different perspective.", "example_ru": "Рассмотри это с другой точки зрения."},
    {"word": "assumption", "transcription": "/əˈsʌmpʃən/", "translation": "предположение", "part_of_speech": "noun", "example": "Don't make assumptions.", "example_ru": "Не делай предположений."},
    {"word": "exception", "transcription": "/ɪkˈsepʃən/", "translation": "исключение", "part_of_speech": "noun", "example": "There is always an exception.", "example_ru": "Всегда есть исключение."},
    {"word": "contrast", "transcription": "/ˈkɒntrɑːst/", "translation": "контраст; контрастировать", "part_of_speech": "noun/verb", "example": "In contrast, the other team won.", "example_ru": "Напротив, другая команда выиграла."},
    {"word": "combination", "transcription": "/ˌkɒmbɪˈneɪʃən/", "translation": "комбинация, сочетание", "part_of_speech": "noun", "example": "A combination of skills is needed.", "example_ru": "Необходимо сочетание навыков."},
    {"word": "variety", "transcription": "/vəˈraɪɪti/", "translation": "разнообразие, ассортимент", "part_of_speech": "noun", "example": "There is a variety of options.", "example_ru": "Есть разнообразие вариантов."},
    {"word": "opportunity", "transcription": "/ˌɒpəˈtjuːnɪti/", "translation": "возможность, шанс", "part_of_speech": "noun", "example": "Don't miss this opportunity.", "example_ru": "Не упусти эту возможность."},
    {"word": "circumstance", "transcription": "/ˈsɜːrkəmstæns/", "translation": "обстоятельство", "part_of_speech": "noun", "example": "Under the circumstances, we did well.", "example_ru": "При данных обстоятельствах мы справились."},
    {"word": "contribution", "transcription": "/ˌkɒntrɪˈbjuːʃən/", "translation": "вклад, взнос", "part_of_speech": "noun", "example": "Thank you for your contribution.", "example_ru": "Спасибо за твой вклад."},
    {"word": "recognition", "transcription": "/ˌrekəɡˈnɪʃən/", "translation": "признание", "part_of_speech": "noun", "example": "She deserves recognition for her work.", "example_ru": "Она заслуживает признания за свою работу."},
    {"word": "innovation", "transcription": "/ˌɪnəˈveɪʃən/", "translation": "инновация, новшество", "part_of_speech": "noun", "example": "Innovation drives progress.", "example_ru": "Инновации движут прогресс."},
    {"word": "interaction", "transcription": "/ˌɪntərˈækʃən/", "translation": "взаимодействие", "part_of_speech": "noun", "example": "Positive interaction builds trust.", "example_ru": "Позитивное взаимодействие строит доверие."},
]
